// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/admin.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/LIRYC-IHU/ecg-hub/internal/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "grpc.api.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceGetStatsProcedure is the fully-qualified name of the AdminService's GetStats RPC.
	AdminServiceGetStatsProcedure = "/grpc.api.v1.AdminService/GetStats"
	// AdminServiceGetStorageMetricsProcedure is the fully-qualified name of the AdminService's
	// GetStorageMetrics RPC.
	AdminServiceGetStorageMetricsProcedure = "/grpc.api.v1.AdminService/GetStorageMetrics"
	// AdminServiceGetRecentErrorsProcedure is the fully-qualified name of the AdminService's
	// GetRecentErrors RPC.
	AdminServiceGetRecentErrorsProcedure = "/grpc.api.v1.AdminService/GetRecentErrors"
	// AdminServiceListAuditLogsProcedure is the fully-qualified name of the AdminService's
	// ListAuditLogs RPC.
	AdminServiceListAuditLogsProcedure = "/grpc.api.v1.AdminService/ListAuditLogs"
	// AdminServiceGetUserDefaultsProcedure is the fully-qualified name of the AdminService's
	// GetUserDefaults RPC.
	AdminServiceGetUserDefaultsProcedure = "/grpc.api.v1.AdminService/GetUserDefaults"
	// AdminServiceSetUserDefaultsProcedure is the fully-qualified name of the AdminService's
	// SetUserDefaults RPC.
	AdminServiceSetUserDefaultsProcedure = "/grpc.api.v1.AdminService/SetUserDefaults"
	// AdminServiceListRolesProcedure is the fully-qualified name of the AdminService's ListRoles RPC.
	AdminServiceListRolesProcedure = "/grpc.api.v1.AdminService/ListRoles"
	// AdminServiceCreateRoleProcedure is the fully-qualified name of the AdminService's CreateRole RPC.
	AdminServiceCreateRoleProcedure = "/grpc.api.v1.AdminService/CreateRole"
	// AdminServiceUpdateRoleProcedure is the fully-qualified name of the AdminService's UpdateRole RPC.
	AdminServiceUpdateRoleProcedure = "/grpc.api.v1.AdminService/UpdateRole"
	// AdminServiceDeleteRoleProcedure is the fully-qualified name of the AdminService's DeleteRole RPC.
	AdminServiceDeleteRoleProcedure = "/grpc.api.v1.AdminService/DeleteRole"
	// AdminServiceListAppUsersProcedure is the fully-qualified name of the AdminService's ListAppUsers
	// RPC.
	AdminServiceListAppUsersProcedure = "/grpc.api.v1.AdminService/ListAppUsers"
	// AdminServiceSetAppUserRoleProcedure is the fully-qualified name of the AdminService's
	// SetAppUserRole RPC.
	AdminServiceSetAppUserRoleProcedure = "/grpc.api.v1.AdminService/SetAppUserRole"
	// AdminServiceDeleteAppUserProcedure is the fully-qualified name of the AdminService's
	// DeleteAppUser RPC.
	AdminServiceDeleteAppUserProcedure = "/grpc.api.v1.AdminService/DeleteAppUser"
	// AdminServiceListQuarantineProcedure is the fully-qualified name of the AdminService's
	// ListQuarantine RPC.
	AdminServiceListQuarantineProcedure = "/grpc.api.v1.AdminService/ListQuarantine"
	// AdminServiceDeleteQuarantineProcedure is the fully-qualified name of the AdminService's
	// DeleteQuarantine RPC.
	AdminServiceDeleteQuarantineProcedure = "/grpc.api.v1.AdminService/DeleteQuarantine"
	// AdminServiceAssignQuarantineProcedure is the fully-qualified name of the AdminService's
	// AssignQuarantine RPC.
	AdminServiceAssignQuarantineProcedure = "/grpc.api.v1.AdminService/AssignQuarantine"
)

// AdminServiceClient is a client for the grpc.api.v1.AdminService service.
type AdminServiceClient interface {
	GetStats(context.Context, *v1.GetStatsRequest) (*v1.GetStatsResponse, error)
	GetStorageMetrics(context.Context, *v1.GetStorageMetricsRequest) (*v1.GetStorageMetricsResponse, error)
	GetRecentErrors(context.Context, *v1.GetRecentErrorsRequest) (*v1.GetRecentErrorsResponse, error)
	ListAuditLogs(context.Context, *v1.ListAuditLogsRequest) (*v1.ListAuditLogsResponse, error)
	GetUserDefaults(context.Context, *v1.GetUserDefaultsRequest) (*v1.GetUserDefaultsResponse, error)
	SetUserDefaults(context.Context, *v1.SetUserDefaultsRequest) (*v1.SetUserDefaultsResponse, error)
	ListRoles(context.Context, *v1.ListRolesRequest) (*v1.ListRolesResponse, error)
	CreateRole(context.Context, *v1.CreateRoleRequest) (*v1.CreateRoleResponse, error)
	UpdateRole(context.Context, *v1.UpdateRoleRequest) (*v1.UpdateRoleResponse, error)
	DeleteRole(context.Context, *v1.DeleteRoleRequest) (*v1.DeleteRoleResponse, error)
	ListAppUsers(context.Context, *v1.ListAppUsersRequest) (*v1.ListAppUsersResponse, error)
	SetAppUserRole(context.Context, *v1.SetAppUserRoleRequest) (*v1.SetAppUserRoleResponse, error)
	DeleteAppUser(context.Context, *v1.DeleteAppUserRequest) (*v1.DeleteAppUserResponse, error)
	ListQuarantine(context.Context, *v1.ListQuarantineRequest) (*v1.ListQuarantineResponse, error)
	DeleteQuarantine(context.Context, *v1.DeleteQuarantineRequest) (*v1.DeleteQuarantineResponse, error)
	AssignQuarantine(context.Context, *v1.AssignQuarantineRequest) (*v1.AssignQuarantineResponse, error)
}

// NewAdminServiceClient constructs a client for the grpc.api.v1.AdminService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_v1_admin_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		getStats: connect.NewClient[v1.GetStatsRequest, v1.GetStatsResponse](
			httpClient,
			baseURL+AdminServiceGetStatsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetStats")),
			connect.WithClientOptions(opts...),
		),
		getStorageMetrics: connect.NewClient[v1.GetStorageMetricsRequest, v1.GetStorageMetricsResponse](
			httpClient,
			baseURL+AdminServiceGetStorageMetricsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetStorageMetrics")),
			connect.WithClientOptions(opts...),
		),
		getRecentErrors: connect.NewClient[v1.GetRecentErrorsRequest, v1.GetRecentErrorsResponse](
			httpClient,
			baseURL+AdminServiceGetRecentErrorsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetRecentErrors")),
			connect.WithClientOptions(opts...),
		),
		listAuditLogs: connect.NewClient[v1.ListAuditLogsRequest, v1.ListAuditLogsResponse](
			httpClient,
			baseURL+AdminServiceListAuditLogsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListAuditLogs")),
			connect.WithClientOptions(opts...),
		),
		getUserDefaults: connect.NewClient[v1.GetUserDefaultsRequest, v1.GetUserDefaultsResponse](
			httpClient,
			baseURL+AdminServiceGetUserDefaultsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetUserDefaults")),
			connect.WithClientOptions(opts...),
		),
		setUserDefaults: connect.NewClient[v1.SetUserDefaultsRequest, v1.SetUserDefaultsResponse](
			httpClient,
			baseURL+AdminServiceSetUserDefaultsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("SetUserDefaults")),
			connect.WithClientOptions(opts...),
		),
		listRoles: connect.NewClient[v1.ListRolesRequest, v1.ListRolesResponse](
			httpClient,
			baseURL+AdminServiceListRolesProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		createRole: connect.NewClient[v1.CreateRoleRequest, v1.CreateRoleResponse](
			httpClient,
			baseURL+AdminServiceCreateRoleProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateRole")),
			connect.WithClientOptions(opts...),
		),
		updateRole: connect.NewClient[v1.UpdateRoleRequest, v1.UpdateRoleResponse](
			httpClient,
			baseURL+AdminServiceUpdateRoleProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateRole")),
			connect.WithClientOptions(opts...),
		),
		deleteRole: connect.NewClient[v1.DeleteRoleRequest, v1.DeleteRoleResponse](
			httpClient,
			baseURL+AdminServiceDeleteRoleProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteRole")),
			connect.WithClientOptions(opts...),
		),
		listAppUsers: connect.NewClient[v1.ListAppUsersRequest, v1.ListAppUsersResponse](
			httpClient,
			baseURL+AdminServiceListAppUsersProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListAppUsers")),
			connect.WithClientOptions(opts...),
		),
		setAppUserRole: connect.NewClient[v1.SetAppUserRoleRequest, v1.SetAppUserRoleResponse](
			httpClient,
			baseURL+AdminServiceSetAppUserRoleProcedure,
			connect.WithSchema(adminServiceMethods.ByName("SetAppUserRole")),
			connect.WithClientOptions(opts...),
		),
		deleteAppUser: connect.NewClient[v1.DeleteAppUserRequest, v1.DeleteAppUserResponse](
			httpClient,
			baseURL+AdminServiceDeleteAppUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteAppUser")),
			connect.WithClientOptions(opts...),
		),
		listQuarantine: connect.NewClient[v1.ListQuarantineRequest, v1.ListQuarantineResponse](
			httpClient,
			baseURL+AdminServiceListQuarantineProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListQuarantine")),
			connect.WithClientOptions(opts...),
		),
		deleteQuarantine: connect.NewClient[v1.DeleteQuarantineRequest, v1.DeleteQuarantineResponse](
			httpClient,
			baseURL+AdminServiceDeleteQuarantineProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteQuarantine")),
			connect.WithClientOptions(opts...),
		),
		assignQuarantine: connect.NewClient[v1.AssignQuarantineRequest, v1.AssignQuarantineResponse](
			httpClient,
			baseURL+AdminServiceAssignQuarantineProcedure,
			connect.WithSchema(adminServiceMethods.ByName("AssignQuarantine")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	getStats          *connect.Client[v1.GetStatsRequest, v1.GetStatsResponse]
	getStorageMetrics *connect.Client[v1.GetStorageMetricsRequest, v1.GetStorageMetricsResponse]
	getRecentErrors   *connect.Client[v1.GetRecentErrorsRequest, v1.GetRecentErrorsResponse]
	listAuditLogs     *connect.Client[v1.ListAuditLogsRequest, v1.ListAuditLogsResponse]
	getUserDefaults   *connect.Client[v1.GetUserDefaultsRequest, v1.GetUserDefaultsResponse]
	setUserDefaults   *connect.Client[v1.SetUserDefaultsRequest, v1.SetUserDefaultsResponse]
	listRoles         *connect.Client[v1.ListRolesRequest, v1.ListRolesResponse]
	createRole        *connect.Client[v1.CreateRoleRequest, v1.CreateRoleResponse]
	updateRole        *connect.Client[v1.UpdateRoleRequest, v1.UpdateRoleResponse]
	deleteRole        *connect.Client[v1.DeleteRoleRequest, v1.DeleteRoleResponse]
	listAppUsers      *connect.Client[v1.ListAppUsersRequest, v1.ListAppUsersResponse]
	setAppUserRole    *connect.Client[v1.SetAppUserRoleRequest, v1.SetAppUserRoleResponse]
	deleteAppUser     *connect.Client[v1.DeleteAppUserRequest, v1.DeleteAppUserResponse]
	listQuarantine    *connect.Client[v1.ListQuarantineRequest, v1.ListQuarantineResponse]
	deleteQuarantine  *connect.Client[v1.DeleteQuarantineRequest, v1.DeleteQuarantineResponse]
	assignQuarantine  *connect.Client[v1.AssignQuarantineRequest, v1.AssignQuarantineResponse]
}

// GetStats calls grpc.api.v1.AdminService.GetStats.
func (c *adminServiceClient) GetStats(ctx context.Context, req *v1.GetStatsRequest) (*v1.GetStatsResponse, error) {
	response, err := c.getStats.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetStorageMetrics calls grpc.api.v1.AdminService.GetStorageMetrics.
func (c *adminServiceClient) GetStorageMetrics(ctx context.Context, req *v1.GetStorageMetricsRequest) (*v1.GetStorageMetricsResponse, error) {
	response, err := c.getStorageMetrics.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetRecentErrors calls grpc.api.v1.AdminService.GetRecentErrors.
func (c *adminServiceClient) GetRecentErrors(ctx context.Context, req *v1.GetRecentErrorsRequest) (*v1.GetRecentErrorsResponse, error) {
	response, err := c.getRecentErrors.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListAuditLogs calls grpc.api.v1.AdminService.ListAuditLogs.
func (c *adminServiceClient) ListAuditLogs(ctx context.Context, req *v1.ListAuditLogsRequest) (*v1.ListAuditLogsResponse, error) {
	response, err := c.listAuditLogs.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetUserDefaults calls grpc.api.v1.AdminService.GetUserDefaults.
func (c *adminServiceClient) GetUserDefaults(ctx context.Context, req *v1.GetUserDefaultsRequest) (*v1.GetUserDefaultsResponse, error) {
	response, err := c.getUserDefaults.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SetUserDefaults calls grpc.api.v1.AdminService.SetUserDefaults.
func (c *adminServiceClient) SetUserDefaults(ctx context.Context, req *v1.SetUserDefaultsRequest) (*v1.SetUserDefaultsResponse, error) {
	response, err := c.setUserDefaults.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListRoles calls grpc.api.v1.AdminService.ListRoles.
func (c *adminServiceClient) ListRoles(ctx context.Context, req *v1.ListRolesRequest) (*v1.ListRolesResponse, error) {
	response, err := c.listRoles.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateRole calls grpc.api.v1.AdminService.CreateRole.
func (c *adminServiceClient) CreateRole(ctx context.Context, req *v1.CreateRoleRequest) (*v1.CreateRoleResponse, error) {
	response, err := c.createRole.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateRole calls grpc.api.v1.AdminService.UpdateRole.
func (c *adminServiceClient) UpdateRole(ctx context.Context, req *v1.UpdateRoleRequest) (*v1.UpdateRoleResponse, error) {
	response, err := c.updateRole.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteRole calls grpc.api.v1.AdminService.DeleteRole.
func (c *adminServiceClient) DeleteRole(ctx context.Context, req *v1.DeleteRoleRequest) (*v1.DeleteRoleResponse, error) {
	response, err := c.deleteRole.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListAppUsers calls grpc.api.v1.AdminService.ListAppUsers.
func (c *adminServiceClient) ListAppUsers(ctx context.Context, req *v1.ListAppUsersRequest) (*v1.ListAppUsersResponse, error) {
	response, err := c.listAppUsers.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SetAppUserRole calls grpc.api.v1.AdminService.SetAppUserRole.
func (c *adminServiceClient) SetAppUserRole(ctx context.Context, req *v1.SetAppUserRoleRequest) (*v1.SetAppUserRoleResponse, error) {
	response, err := c.setAppUserRole.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteAppUser calls grpc.api.v1.AdminService.DeleteAppUser.
func (c *adminServiceClient) DeleteAppUser(ctx context.Context, req *v1.DeleteAppUserRequest) (*v1.DeleteAppUserResponse, error) {
	response, err := c.deleteAppUser.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListQuarantine calls grpc.api.v1.AdminService.ListQuarantine.
func (c *adminServiceClient) ListQuarantine(ctx context.Context, req *v1.ListQuarantineRequest) (*v1.ListQuarantineResponse, error) {
	response, err := c.listQuarantine.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteQuarantine calls grpc.api.v1.AdminService.DeleteQuarantine.
func (c *adminServiceClient) DeleteQuarantine(ctx context.Context, req *v1.DeleteQuarantineRequest) (*v1.DeleteQuarantineResponse, error) {
	response, err := c.deleteQuarantine.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AssignQuarantine calls grpc.api.v1.AdminService.AssignQuarantine.
func (c *adminServiceClient) AssignQuarantine(ctx context.Context, req *v1.AssignQuarantineRequest) (*v1.AssignQuarantineResponse, error) {
	response, err := c.assignQuarantine.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// AdminServiceHandler is an implementation of the grpc.api.v1.AdminService service.
type AdminServiceHandler interface {
	GetStats(context.Context, *v1.GetStatsRequest) (*v1.GetStatsResponse, error)
	GetStorageMetrics(context.Context, *v1.GetStorageMetricsRequest) (*v1.GetStorageMetricsResponse, error)
	GetRecentErrors(context.Context, *v1.GetRecentErrorsRequest) (*v1.GetRecentErrorsResponse, error)
	ListAuditLogs(context.Context, *v1.ListAuditLogsRequest) (*v1.ListAuditLogsResponse, error)
	GetUserDefaults(context.Context, *v1.GetUserDefaultsRequest) (*v1.GetUserDefaultsResponse, error)
	SetUserDefaults(context.Context, *v1.SetUserDefaultsRequest) (*v1.SetUserDefaultsResponse, error)
	ListRoles(context.Context, *v1.ListRolesRequest) (*v1.ListRolesResponse, error)
	CreateRole(context.Context, *v1.CreateRoleRequest) (*v1.CreateRoleResponse, error)
	UpdateRole(context.Context, *v1.UpdateRoleRequest) (*v1.UpdateRoleResponse, error)
	DeleteRole(context.Context, *v1.DeleteRoleRequest) (*v1.DeleteRoleResponse, error)
	ListAppUsers(context.Context, *v1.ListAppUsersRequest) (*v1.ListAppUsersResponse, error)
	SetAppUserRole(context.Context, *v1.SetAppUserRoleRequest) (*v1.SetAppUserRoleResponse, error)
	DeleteAppUser(context.Context, *v1.DeleteAppUserRequest) (*v1.DeleteAppUserResponse, error)
	ListQuarantine(context.Context, *v1.ListQuarantineRequest) (*v1.ListQuarantineResponse, error)
	DeleteQuarantine(context.Context, *v1.DeleteQuarantineRequest) (*v1.DeleteQuarantineResponse, error)
	AssignQuarantine(context.Context, *v1.AssignQuarantineRequest) (*v1.AssignQuarantineResponse, error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_v1_admin_proto.Services().ByName("AdminService").Methods()
	adminServiceGetStatsHandler := connect.NewUnaryHandlerSimple(
		AdminServiceGetStatsProcedure,
		svc.GetStats,
		connect.WithSchema(adminServiceMethods.ByName("GetStats")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceGetStorageMetricsHandler := connect.NewUnaryHandlerSimple(
		AdminServiceGetStorageMetricsProcedure,
		svc.GetStorageMetrics,
		connect.WithSchema(adminServiceMethods.ByName("GetStorageMetrics")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceGetRecentErrorsHandler := connect.NewUnaryHandlerSimple(
		AdminServiceGetRecentErrorsProcedure,
		svc.GetRecentErrors,
		connect.WithSchema(adminServiceMethods.ByName("GetRecentErrors")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListAuditLogsHandler := connect.NewUnaryHandlerSimple(
		AdminServiceListAuditLogsProcedure,
		svc.ListAuditLogs,
		connect.WithSchema(adminServiceMethods.ByName("ListAuditLogs")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceGetUserDefaultsHandler := connect.NewUnaryHandlerSimple(
		AdminServiceGetUserDefaultsProcedure,
		svc.GetUserDefaults,
		connect.WithSchema(adminServiceMethods.ByName("GetUserDefaults")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceSetUserDefaultsHandler := connect.NewUnaryHandlerSimple(
		AdminServiceSetUserDefaultsProcedure,
		svc.SetUserDefaults,
		connect.WithSchema(adminServiceMethods.ByName("SetUserDefaults")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListRolesHandler := connect.NewUnaryHandlerSimple(
		AdminServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(adminServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateRoleHandler := connect.NewUnaryHandlerSimple(
		AdminServiceCreateRoleProcedure,
		svc.CreateRole,
		connect.WithSchema(adminServiceMethods.ByName("CreateRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateRoleHandler := connect.NewUnaryHandlerSimple(
		AdminServiceUpdateRoleProcedure,
		svc.UpdateRole,
		connect.WithSchema(adminServiceMethods.ByName("UpdateRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteRoleHandler := connect.NewUnaryHandlerSimple(
		AdminServiceDeleteRoleProcedure,
		svc.DeleteRole,
		connect.WithSchema(adminServiceMethods.ByName("DeleteRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListAppUsersHandler := connect.NewUnaryHandlerSimple(
		AdminServiceListAppUsersProcedure,
		svc.ListAppUsers,
		connect.WithSchema(adminServiceMethods.ByName("ListAppUsers")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceSetAppUserRoleHandler := connect.NewUnaryHandlerSimple(
		AdminServiceSetAppUserRoleProcedure,
		svc.SetAppUserRole,
		connect.WithSchema(adminServiceMethods.ByName("SetAppUserRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteAppUserHandler := connect.NewUnaryHandlerSimple(
		AdminServiceDeleteAppUserProcedure,
		svc.DeleteAppUser,
		connect.WithSchema(adminServiceMethods.ByName("DeleteAppUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListQuarantineHandler := connect.NewUnaryHandlerSimple(
		AdminServiceListQuarantineProcedure,
		svc.ListQuarantine,
		connect.WithSchema(adminServiceMethods.ByName("ListQuarantine")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteQuarantineHandler := connect.NewUnaryHandlerSimple(
		AdminServiceDeleteQuarantineProcedure,
		svc.DeleteQuarantine,
		connect.WithSchema(adminServiceMethods.ByName("DeleteQuarantine")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceAssignQuarantineHandler := connect.NewUnaryHandlerSimple(
		AdminServiceAssignQuarantineProcedure,
		svc.AssignQuarantine,
		connect.WithSchema(adminServiceMethods.ByName("AssignQuarantine")),
		connect.WithHandlerOptions(opts...),
	)
	return "/grpc.api.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceGetStatsProcedure:
			adminServiceGetStatsHandler.ServeHTTP(w, r)
		case AdminServiceGetStorageMetricsProcedure:
			adminServiceGetStorageMetricsHandler.ServeHTTP(w, r)
		case AdminServiceGetRecentErrorsProcedure:
			adminServiceGetRecentErrorsHandler.ServeHTTP(w, r)
		case AdminServiceListAuditLogsProcedure:
			adminServiceListAuditLogsHandler.ServeHTTP(w, r)
		case AdminServiceGetUserDefaultsProcedure:
			adminServiceGetUserDefaultsHandler.ServeHTTP(w, r)
		case AdminServiceSetUserDefaultsProcedure:
			adminServiceSetUserDefaultsHandler.ServeHTTP(w, r)
		case AdminServiceListRolesProcedure:
			adminServiceListRolesHandler.ServeHTTP(w, r)
		case AdminServiceCreateRoleProcedure:
			adminServiceCreateRoleHandler.ServeHTTP(w, r)
		case AdminServiceUpdateRoleProcedure:
			adminServiceUpdateRoleHandler.ServeHTTP(w, r)
		case AdminServiceDeleteRoleProcedure:
			adminServiceDeleteRoleHandler.ServeHTTP(w, r)
		case AdminServiceListAppUsersProcedure:
			adminServiceListAppUsersHandler.ServeHTTP(w, r)
		case AdminServiceSetAppUserRoleProcedure:
			adminServiceSetAppUserRoleHandler.ServeHTTP(w, r)
		case AdminServiceDeleteAppUserProcedure:
			adminServiceDeleteAppUserHandler.ServeHTTP(w, r)
		case AdminServiceListQuarantineProcedure:
			adminServiceListQuarantineHandler.ServeHTTP(w, r)
		case AdminServiceDeleteQuarantineProcedure:
			adminServiceDeleteQuarantineHandler.ServeHTTP(w, r)
		case AdminServiceAssignQuarantineProcedure:
			adminServiceAssignQuarantineHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) GetStats(context.Context, *v1.GetStatsRequest) (*v1.GetStatsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.GetStats is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetStorageMetrics(context.Context, *v1.GetStorageMetricsRequest) (*v1.GetStorageMetricsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.GetStorageMetrics is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetRecentErrors(context.Context, *v1.GetRecentErrorsRequest) (*v1.GetRecentErrorsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.GetRecentErrors is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListAuditLogs(context.Context, *v1.ListAuditLogsRequest) (*v1.ListAuditLogsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.ListAuditLogs is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetUserDefaults(context.Context, *v1.GetUserDefaultsRequest) (*v1.GetUserDefaultsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.GetUserDefaults is not implemented"))
}

func (UnimplementedAdminServiceHandler) SetUserDefaults(context.Context, *v1.SetUserDefaultsRequest) (*v1.SetUserDefaultsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.SetUserDefaults is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListRoles(context.Context, *v1.ListRolesRequest) (*v1.ListRolesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.ListRoles is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateRole(context.Context, *v1.CreateRoleRequest) (*v1.CreateRoleResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.CreateRole is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateRole(context.Context, *v1.UpdateRoleRequest) (*v1.UpdateRoleResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.UpdateRole is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteRole(context.Context, *v1.DeleteRoleRequest) (*v1.DeleteRoleResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.DeleteRole is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListAppUsers(context.Context, *v1.ListAppUsersRequest) (*v1.ListAppUsersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.ListAppUsers is not implemented"))
}

func (UnimplementedAdminServiceHandler) SetAppUserRole(context.Context, *v1.SetAppUserRoleRequest) (*v1.SetAppUserRoleResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.SetAppUserRole is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteAppUser(context.Context, *v1.DeleteAppUserRequest) (*v1.DeleteAppUserResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.DeleteAppUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListQuarantine(context.Context, *v1.ListQuarantineRequest) (*v1.ListQuarantineResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.ListQuarantine is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteQuarantine(context.Context, *v1.DeleteQuarantineRequest) (*v1.DeleteQuarantineResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.DeleteQuarantine is not implemented"))
}

func (UnimplementedAdminServiceHandler) AssignQuarantine(context.Context, *v1.AssignQuarantineRequest) (*v1.AssignQuarantineResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.AdminService.AssignQuarantine is not implemented"))
}
