// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/apikey.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/LIRYC-IHU/ecg-hub/internal/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// APIKeyServiceName is the fully-qualified name of the APIKeyService service.
	APIKeyServiceName = "grpc.api.v1.APIKeyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// APIKeyServiceListApiKeysProcedure is the fully-qualified name of the APIKeyService's ListApiKeys
	// RPC.
	APIKeyServiceListApiKeysProcedure = "/grpc.api.v1.APIKeyService/ListApiKeys"
	// APIKeyServiceCreateApiKeyProcedure is the fully-qualified name of the APIKeyService's
	// CreateApiKey RPC.
	APIKeyServiceCreateApiKeyProcedure = "/grpc.api.v1.APIKeyService/CreateApiKey"
	// APIKeyServiceDeleteApiKeyProcedure is the fully-qualified name of the APIKeyService's
	// DeleteApiKey RPC.
	APIKeyServiceDeleteApiKeyProcedure = "/grpc.api.v1.APIKeyService/DeleteApiKey"
)

// APIKeyServiceClient is a client for the grpc.api.v1.APIKeyService service.
type APIKeyServiceClient interface {
	ListApiKeys(context.Context, *v1.ListApiKeysRequest) (*v1.ListApiKeysResponse, error)
	CreateApiKey(context.Context, *v1.CreateApiKeyRequest) (*v1.CreateApiKeyResponse, error)
	DeleteApiKey(context.Context, *v1.DeleteApiKeyRequest) (*v1.DeleteApiKeyResponse, error)
}

// NewAPIKeyServiceClient constructs a client for the grpc.api.v1.APIKeyService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAPIKeyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) APIKeyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	aPIKeyServiceMethods := v1.File_v1_apikey_proto.Services().ByName("APIKeyService").Methods()
	return &aPIKeyServiceClient{
		listApiKeys: connect.NewClient[v1.ListApiKeysRequest, v1.ListApiKeysResponse](
			httpClient,
			baseURL+APIKeyServiceListApiKeysProcedure,
			connect.WithSchema(aPIKeyServiceMethods.ByName("ListApiKeys")),
			connect.WithClientOptions(opts...),
		),
		createApiKey: connect.NewClient[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse](
			httpClient,
			baseURL+APIKeyServiceCreateApiKeyProcedure,
			connect.WithSchema(aPIKeyServiceMethods.ByName("CreateApiKey")),
			connect.WithClientOptions(opts...),
		),
		deleteApiKey: connect.NewClient[v1.DeleteApiKeyRequest, v1.DeleteApiKeyResponse](
			httpClient,
			baseURL+APIKeyServiceDeleteApiKeyProcedure,
			connect.WithSchema(aPIKeyServiceMethods.ByName("DeleteApiKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// aPIKeyServiceClient implements APIKeyServiceClient.
type aPIKeyServiceClient struct {
	listApiKeys  *connect.Client[v1.ListApiKeysRequest, v1.ListApiKeysResponse]
	createApiKey *connect.Client[v1.CreateApiKeyRequest, v1.CreateApiKeyResponse]
	deleteApiKey *connect.Client[v1.DeleteApiKeyRequest, v1.DeleteApiKeyResponse]
}

// ListApiKeys calls grpc.api.v1.APIKeyService.ListApiKeys.
func (c *aPIKeyServiceClient) ListApiKeys(ctx context.Context, req *v1.ListApiKeysRequest) (*v1.ListApiKeysResponse, error) {
	response, err := c.listApiKeys.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateApiKey calls grpc.api.v1.APIKeyService.CreateApiKey.
func (c *aPIKeyServiceClient) CreateApiKey(ctx context.Context, req *v1.CreateApiKeyRequest) (*v1.CreateApiKeyResponse, error) {
	response, err := c.createApiKey.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteApiKey calls grpc.api.v1.APIKeyService.DeleteApiKey.
func (c *aPIKeyServiceClient) DeleteApiKey(ctx context.Context, req *v1.DeleteApiKeyRequest) (*v1.DeleteApiKeyResponse, error) {
	response, err := c.deleteApiKey.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// APIKeyServiceHandler is an implementation of the grpc.api.v1.APIKeyService service.
type APIKeyServiceHandler interface {
	ListApiKeys(context.Context, *v1.ListApiKeysRequest) (*v1.ListApiKeysResponse, error)
	CreateApiKey(context.Context, *v1.CreateApiKeyRequest) (*v1.CreateApiKeyResponse, error)
	DeleteApiKey(context.Context, *v1.DeleteApiKeyRequest) (*v1.DeleteApiKeyResponse, error)
}

// NewAPIKeyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAPIKeyServiceHandler(svc APIKeyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	aPIKeyServiceMethods := v1.File_v1_apikey_proto.Services().ByName("APIKeyService").Methods()
	aPIKeyServiceListApiKeysHandler := connect.NewUnaryHandlerSimple(
		APIKeyServiceListApiKeysProcedure,
		svc.ListApiKeys,
		connect.WithSchema(aPIKeyServiceMethods.ByName("ListApiKeys")),
		connect.WithHandlerOptions(opts...),
	)
	aPIKeyServiceCreateApiKeyHandler := connect.NewUnaryHandlerSimple(
		APIKeyServiceCreateApiKeyProcedure,
		svc.CreateApiKey,
		connect.WithSchema(aPIKeyServiceMethods.ByName("CreateApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	aPIKeyServiceDeleteApiKeyHandler := connect.NewUnaryHandlerSimple(
		APIKeyServiceDeleteApiKeyProcedure,
		svc.DeleteApiKey,
		connect.WithSchema(aPIKeyServiceMethods.ByName("DeleteApiKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/grpc.api.v1.APIKeyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case APIKeyServiceListApiKeysProcedure:
			aPIKeyServiceListApiKeysHandler.ServeHTTP(w, r)
		case APIKeyServiceCreateApiKeyProcedure:
			aPIKeyServiceCreateApiKeyHandler.ServeHTTP(w, r)
		case APIKeyServiceDeleteApiKeyProcedure:
			aPIKeyServiceDeleteApiKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAPIKeyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAPIKeyServiceHandler struct{}

func (UnimplementedAPIKeyServiceHandler) ListApiKeys(context.Context, *v1.ListApiKeysRequest) (*v1.ListApiKeysResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.APIKeyService.ListApiKeys is not implemented"))
}

func (UnimplementedAPIKeyServiceHandler) CreateApiKey(context.Context, *v1.CreateApiKeyRequest) (*v1.CreateApiKeyResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.APIKeyService.CreateApiKey is not implemented"))
}

func (UnimplementedAPIKeyServiceHandler) DeleteApiKey(context.Context, *v1.DeleteApiKeyRequest) (*v1.DeleteApiKeyResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.APIKeyService.DeleteApiKey is not implemented"))
}
