// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/branding.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/LIRYC-IHU/ecg-hub/internal/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BrandingServiceName is the fully-qualified name of the BrandingService service.
	BrandingServiceName = "grpc.api.v1.BrandingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BrandingServiceGetBrandingProcedure is the fully-qualified name of the BrandingService's
	// GetBranding RPC.
	BrandingServiceGetBrandingProcedure = "/grpc.api.v1.BrandingService/GetBranding"
)

// BrandingServiceClient is a client for the grpc.api.v1.BrandingService service.
type BrandingServiceClient interface {
	GetBranding(context.Context, *v1.GetBrandingRequest) (*v1.GetBrandingResponse, error)
}

// NewBrandingServiceClient constructs a client for the grpc.api.v1.BrandingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBrandingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BrandingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	brandingServiceMethods := v1.File_v1_branding_proto.Services().ByName("BrandingService").Methods()
	return &brandingServiceClient{
		getBranding: connect.NewClient[v1.GetBrandingRequest, v1.GetBrandingResponse](
			httpClient,
			baseURL+BrandingServiceGetBrandingProcedure,
			connect.WithSchema(brandingServiceMethods.ByName("GetBranding")),
			connect.WithClientOptions(opts...),
		),
	}
}

// brandingServiceClient implements BrandingServiceClient.
type brandingServiceClient struct {
	getBranding *connect.Client[v1.GetBrandingRequest, v1.GetBrandingResponse]
}

// GetBranding calls grpc.api.v1.BrandingService.GetBranding.
func (c *brandingServiceClient) GetBranding(ctx context.Context, req *v1.GetBrandingRequest) (*v1.GetBrandingResponse, error) {
	response, err := c.getBranding.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// BrandingServiceHandler is an implementation of the grpc.api.v1.BrandingService service.
type BrandingServiceHandler interface {
	GetBranding(context.Context, *v1.GetBrandingRequest) (*v1.GetBrandingResponse, error)
}

// NewBrandingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBrandingServiceHandler(svc BrandingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	brandingServiceMethods := v1.File_v1_branding_proto.Services().ByName("BrandingService").Methods()
	brandingServiceGetBrandingHandler := connect.NewUnaryHandlerSimple(
		BrandingServiceGetBrandingProcedure,
		svc.GetBranding,
		connect.WithSchema(brandingServiceMethods.ByName("GetBranding")),
		connect.WithHandlerOptions(opts...),
	)
	return "/grpc.api.v1.BrandingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BrandingServiceGetBrandingProcedure:
			brandingServiceGetBrandingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBrandingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBrandingServiceHandler struct{}

func (UnimplementedBrandingServiceHandler) GetBranding(context.Context, *v1.GetBrandingRequest) (*v1.GetBrandingResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.BrandingService.GetBranding is not implemented"))
}
