// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/device.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/LIRYC-IHU/ecg-hub/internal/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DeviceServiceName is the fully-qualified name of the DeviceService service.
	DeviceServiceName = "grpc.api.v1.DeviceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeviceServiceListDevicesProcedure is the fully-qualified name of the DeviceService's ListDevices
	// RPC.
	DeviceServiceListDevicesProcedure = "/grpc.api.v1.DeviceService/ListDevices"
	// DeviceServiceGetSettingsProcedure is the fully-qualified name of the DeviceService's GetSettings
	// RPC.
	DeviceServiceGetSettingsProcedure = "/grpc.api.v1.DeviceService/GetSettings"
	// DeviceServiceUpdateSettingsProcedure is the fully-qualified name of the DeviceService's
	// UpdateSettings RPC.
	DeviceServiceUpdateSettingsProcedure = "/grpc.api.v1.DeviceService/UpdateSettings"
	// DeviceServiceApproveDeviceProcedure is the fully-qualified name of the DeviceService's
	// ApproveDevice RPC.
	DeviceServiceApproveDeviceProcedure = "/grpc.api.v1.DeviceService/ApproveDevice"
	// DeviceServiceRevokeDeviceProcedure is the fully-qualified name of the DeviceService's
	// RevokeDevice RPC.
	DeviceServiceRevokeDeviceProcedure = "/grpc.api.v1.DeviceService/RevokeDevice"
	// DeviceServiceDeleteDeviceProcedure is the fully-qualified name of the DeviceService's
	// DeleteDevice RPC.
	DeviceServiceDeleteDeviceProcedure = "/grpc.api.v1.DeviceService/DeleteDevice"
	// DeviceServiceSubscribeDevicesProcedure is the fully-qualified name of the DeviceService's
	// SubscribeDevices RPC.
	DeviceServiceSubscribeDevicesProcedure = "/grpc.api.v1.DeviceService/SubscribeDevices"
)

// DeviceServiceClient is a client for the grpc.api.v1.DeviceService service.
type DeviceServiceClient interface {
	ListDevices(context.Context, *v1.ListDevicesRequest) (*v1.ListDevicesResponse, error)
	GetSettings(context.Context, *v1.GetDeviceSettingsRequest) (*v1.GetDeviceSettingsResponse, error)
	UpdateSettings(context.Context, *v1.UpdateDeviceSettingsRequest) (*v1.UpdateDeviceSettingsResponse, error)
	ApproveDevice(context.Context, *v1.ApproveDeviceRequest) (*v1.ApproveDeviceResponse, error)
	RevokeDevice(context.Context, *v1.RevokeDeviceRequest) (*v1.RevokeDeviceResponse, error)
	DeleteDevice(context.Context, *v1.DeleteDeviceRequest) (*v1.DeleteDeviceResponse, error)
	SubscribeDevices(context.Context, *v1.SubscribeDevicesRequest) (*connect.ServerStreamForClient[v1.DeviceEvent], error)
}

// NewDeviceServiceClient constructs a client for the grpc.api.v1.DeviceService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeviceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeviceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deviceServiceMethods := v1.File_v1_device_proto.Services().ByName("DeviceService").Methods()
	return &deviceServiceClient{
		listDevices: connect.NewClient[v1.ListDevicesRequest, v1.ListDevicesResponse](
			httpClient,
			baseURL+DeviceServiceListDevicesProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("ListDevices")),
			connect.WithClientOptions(opts...),
		),
		getSettings: connect.NewClient[v1.GetDeviceSettingsRequest, v1.GetDeviceSettingsResponse](
			httpClient,
			baseURL+DeviceServiceGetSettingsProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("GetSettings")),
			connect.WithClientOptions(opts...),
		),
		updateSettings: connect.NewClient[v1.UpdateDeviceSettingsRequest, v1.UpdateDeviceSettingsResponse](
			httpClient,
			baseURL+DeviceServiceUpdateSettingsProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("UpdateSettings")),
			connect.WithClientOptions(opts...),
		),
		approveDevice: connect.NewClient[v1.ApproveDeviceRequest, v1.ApproveDeviceResponse](
			httpClient,
			baseURL+DeviceServiceApproveDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("ApproveDevice")),
			connect.WithClientOptions(opts...),
		),
		revokeDevice: connect.NewClient[v1.RevokeDeviceRequest, v1.RevokeDeviceResponse](
			httpClient,
			baseURL+DeviceServiceRevokeDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("RevokeDevice")),
			connect.WithClientOptions(opts...),
		),
		deleteDevice: connect.NewClient[v1.DeleteDeviceRequest, v1.DeleteDeviceResponse](
			httpClient,
			baseURL+DeviceServiceDeleteDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("DeleteDevice")),
			connect.WithClientOptions(opts...),
		),
		subscribeDevices: connect.NewClient[v1.SubscribeDevicesRequest, v1.DeviceEvent](
			httpClient,
			baseURL+DeviceServiceSubscribeDevicesProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("SubscribeDevices")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deviceServiceClient implements DeviceServiceClient.
type deviceServiceClient struct {
	listDevices      *connect.Client[v1.ListDevicesRequest, v1.ListDevicesResponse]
	getSettings      *connect.Client[v1.GetDeviceSettingsRequest, v1.GetDeviceSettingsResponse]
	updateSettings   *connect.Client[v1.UpdateDeviceSettingsRequest, v1.UpdateDeviceSettingsResponse]
	approveDevice    *connect.Client[v1.ApproveDeviceRequest, v1.ApproveDeviceResponse]
	revokeDevice     *connect.Client[v1.RevokeDeviceRequest, v1.RevokeDeviceResponse]
	deleteDevice     *connect.Client[v1.DeleteDeviceRequest, v1.DeleteDeviceResponse]
	subscribeDevices *connect.Client[v1.SubscribeDevicesRequest, v1.DeviceEvent]
}

// ListDevices calls grpc.api.v1.DeviceService.ListDevices.
func (c *deviceServiceClient) ListDevices(ctx context.Context, req *v1.ListDevicesRequest) (*v1.ListDevicesResponse, error) {
	response, err := c.listDevices.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetSettings calls grpc.api.v1.DeviceService.GetSettings.
func (c *deviceServiceClient) GetSettings(ctx context.Context, req *v1.GetDeviceSettingsRequest) (*v1.GetDeviceSettingsResponse, error) {
	response, err := c.getSettings.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateSettings calls grpc.api.v1.DeviceService.UpdateSettings.
func (c *deviceServiceClient) UpdateSettings(ctx context.Context, req *v1.UpdateDeviceSettingsRequest) (*v1.UpdateDeviceSettingsResponse, error) {
	response, err := c.updateSettings.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ApproveDevice calls grpc.api.v1.DeviceService.ApproveDevice.
func (c *deviceServiceClient) ApproveDevice(ctx context.Context, req *v1.ApproveDeviceRequest) (*v1.ApproveDeviceResponse, error) {
	response, err := c.approveDevice.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RevokeDevice calls grpc.api.v1.DeviceService.RevokeDevice.
func (c *deviceServiceClient) RevokeDevice(ctx context.Context, req *v1.RevokeDeviceRequest) (*v1.RevokeDeviceResponse, error) {
	response, err := c.revokeDevice.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteDevice calls grpc.api.v1.DeviceService.DeleteDevice.
func (c *deviceServiceClient) DeleteDevice(ctx context.Context, req *v1.DeleteDeviceRequest) (*v1.DeleteDeviceResponse, error) {
	response, err := c.deleteDevice.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SubscribeDevices calls grpc.api.v1.DeviceService.SubscribeDevices.
func (c *deviceServiceClient) SubscribeDevices(ctx context.Context, req *v1.SubscribeDevicesRequest) (*connect.ServerStreamForClient[v1.DeviceEvent], error) {
	return c.subscribeDevices.CallServerStream(ctx, connect.NewRequest(req))
}

// DeviceServiceHandler is an implementation of the grpc.api.v1.DeviceService service.
type DeviceServiceHandler interface {
	ListDevices(context.Context, *v1.ListDevicesRequest) (*v1.ListDevicesResponse, error)
	GetSettings(context.Context, *v1.GetDeviceSettingsRequest) (*v1.GetDeviceSettingsResponse, error)
	UpdateSettings(context.Context, *v1.UpdateDeviceSettingsRequest) (*v1.UpdateDeviceSettingsResponse, error)
	ApproveDevice(context.Context, *v1.ApproveDeviceRequest) (*v1.ApproveDeviceResponse, error)
	RevokeDevice(context.Context, *v1.RevokeDeviceRequest) (*v1.RevokeDeviceResponse, error)
	DeleteDevice(context.Context, *v1.DeleteDeviceRequest) (*v1.DeleteDeviceResponse, error)
	SubscribeDevices(context.Context, *v1.SubscribeDevicesRequest, *connect.ServerStream[v1.DeviceEvent]) error
}

// NewDeviceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeviceServiceHandler(svc DeviceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deviceServiceMethods := v1.File_v1_device_proto.Services().ByName("DeviceService").Methods()
	deviceServiceListDevicesHandler := connect.NewUnaryHandlerSimple(
		DeviceServiceListDevicesProcedure,
		svc.ListDevices,
		connect.WithSchema(deviceServiceMethods.ByName("ListDevices")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceGetSettingsHandler := connect.NewUnaryHandlerSimple(
		DeviceServiceGetSettingsProcedure,
		svc.GetSettings,
		connect.WithSchema(deviceServiceMethods.ByName("GetSettings")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceUpdateSettingsHandler := connect.NewUnaryHandlerSimple(
		DeviceServiceUpdateSettingsProcedure,
		svc.UpdateSettings,
		connect.WithSchema(deviceServiceMethods.ByName("UpdateSettings")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceApproveDeviceHandler := connect.NewUnaryHandlerSimple(
		DeviceServiceApproveDeviceProcedure,
		svc.ApproveDevice,
		connect.WithSchema(deviceServiceMethods.ByName("ApproveDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceRevokeDeviceHandler := connect.NewUnaryHandlerSimple(
		DeviceServiceRevokeDeviceProcedure,
		svc.RevokeDevice,
		connect.WithSchema(deviceServiceMethods.ByName("RevokeDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceDeleteDeviceHandler := connect.NewUnaryHandlerSimple(
		DeviceServiceDeleteDeviceProcedure,
		svc.DeleteDevice,
		connect.WithSchema(deviceServiceMethods.ByName("DeleteDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceSubscribeDevicesHandler := connect.NewServerStreamHandlerSimple(
		DeviceServiceSubscribeDevicesProcedure,
		svc.SubscribeDevices,
		connect.WithSchema(deviceServiceMethods.ByName("SubscribeDevices")),
		connect.WithHandlerOptions(opts...),
	)
	return "/grpc.api.v1.DeviceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeviceServiceListDevicesProcedure:
			deviceServiceListDevicesHandler.ServeHTTP(w, r)
		case DeviceServiceGetSettingsProcedure:
			deviceServiceGetSettingsHandler.ServeHTTP(w, r)
		case DeviceServiceUpdateSettingsProcedure:
			deviceServiceUpdateSettingsHandler.ServeHTTP(w, r)
		case DeviceServiceApproveDeviceProcedure:
			deviceServiceApproveDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceRevokeDeviceProcedure:
			deviceServiceRevokeDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceDeleteDeviceProcedure:
			deviceServiceDeleteDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceSubscribeDevicesProcedure:
			deviceServiceSubscribeDevicesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeviceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDeviceServiceHandler struct{}

func (UnimplementedDeviceServiceHandler) ListDevices(context.Context, *v1.ListDevicesRequest) (*v1.ListDevicesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.DeviceService.ListDevices is not implemented"))
}

func (UnimplementedDeviceServiceHandler) GetSettings(context.Context, *v1.GetDeviceSettingsRequest) (*v1.GetDeviceSettingsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.DeviceService.GetSettings is not implemented"))
}

func (UnimplementedDeviceServiceHandler) UpdateSettings(context.Context, *v1.UpdateDeviceSettingsRequest) (*v1.UpdateDeviceSettingsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.DeviceService.UpdateSettings is not implemented"))
}

func (UnimplementedDeviceServiceHandler) ApproveDevice(context.Context, *v1.ApproveDeviceRequest) (*v1.ApproveDeviceResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.DeviceService.ApproveDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) RevokeDevice(context.Context, *v1.RevokeDeviceRequest) (*v1.RevokeDeviceResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.DeviceService.RevokeDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) DeleteDevice(context.Context, *v1.DeleteDeviceRequest) (*v1.DeleteDeviceResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.DeviceService.DeleteDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) SubscribeDevices(context.Context, *v1.SubscribeDevicesRequest, *connect.ServerStream[v1.DeviceEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.DeviceService.SubscribeDevices is not implemented"))
}
