// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/ecg.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/LIRYC-IHU/ecg-hub/internal/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ECGServiceName is the fully-qualified name of the ECGService service.
	ECGServiceName = "grpc.api.v1.ECGService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ECGServiceGetFiltersProcedure is the fully-qualified name of the ECGService's GetFilters RPC.
	ECGServiceGetFiltersProcedure = "/grpc.api.v1.ECGService/GetFilters"
	// ECGServiceListAllProcedure is the fully-qualified name of the ECGService's ListAll RPC.
	ECGServiceListAllProcedure = "/grpc.api.v1.ECGService/ListAll"
	// ECGServiceGetMetadataProcedure is the fully-qualified name of the ECGService's GetMetadata RPC.
	ECGServiceGetMetadataProcedure = "/grpc.api.v1.ECGService/GetMetadata"
	// ECGServiceUpdateMetadataProcedure is the fully-qualified name of the ECGService's UpdateMetadata
	// RPC.
	ECGServiceUpdateMetadataProcedure = "/grpc.api.v1.ECGService/UpdateMetadata"
)

// ECGServiceClient is a client for the grpc.api.v1.ECGService service.
type ECGServiceClient interface {
	GetFilters(context.Context, *v1.GetFiltersRequest) (*v1.GetFiltersResponse, error)
	ListAll(context.Context, *v1.ListAllRequest) (*v1.ListAllResponse, error)
	GetMetadata(context.Context, *v1.GetMetadataRequest) (*v1.GetMetadataResponse, error)
	UpdateMetadata(context.Context, *v1.UpdateMetadataRequest) (*v1.UpdateMetadataResponse, error)
}

// NewECGServiceClient constructs a client for the grpc.api.v1.ECGService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewECGServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ECGServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eCGServiceMethods := v1.File_v1_ecg_proto.Services().ByName("ECGService").Methods()
	return &eCGServiceClient{
		getFilters: connect.NewClient[v1.GetFiltersRequest, v1.GetFiltersResponse](
			httpClient,
			baseURL+ECGServiceGetFiltersProcedure,
			connect.WithSchema(eCGServiceMethods.ByName("GetFilters")),
			connect.WithClientOptions(opts...),
		),
		listAll: connect.NewClient[v1.ListAllRequest, v1.ListAllResponse](
			httpClient,
			baseURL+ECGServiceListAllProcedure,
			connect.WithSchema(eCGServiceMethods.ByName("ListAll")),
			connect.WithClientOptions(opts...),
		),
		getMetadata: connect.NewClient[v1.GetMetadataRequest, v1.GetMetadataResponse](
			httpClient,
			baseURL+ECGServiceGetMetadataProcedure,
			connect.WithSchema(eCGServiceMethods.ByName("GetMetadata")),
			connect.WithClientOptions(opts...),
		),
		updateMetadata: connect.NewClient[v1.UpdateMetadataRequest, v1.UpdateMetadataResponse](
			httpClient,
			baseURL+ECGServiceUpdateMetadataProcedure,
			connect.WithSchema(eCGServiceMethods.ByName("UpdateMetadata")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eCGServiceClient implements ECGServiceClient.
type eCGServiceClient struct {
	getFilters     *connect.Client[v1.GetFiltersRequest, v1.GetFiltersResponse]
	listAll        *connect.Client[v1.ListAllRequest, v1.ListAllResponse]
	getMetadata    *connect.Client[v1.GetMetadataRequest, v1.GetMetadataResponse]
	updateMetadata *connect.Client[v1.UpdateMetadataRequest, v1.UpdateMetadataResponse]
}

// GetFilters calls grpc.api.v1.ECGService.GetFilters.
func (c *eCGServiceClient) GetFilters(ctx context.Context, req *v1.GetFiltersRequest) (*v1.GetFiltersResponse, error) {
	response, err := c.getFilters.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListAll calls grpc.api.v1.ECGService.ListAll.
func (c *eCGServiceClient) ListAll(ctx context.Context, req *v1.ListAllRequest) (*v1.ListAllResponse, error) {
	response, err := c.listAll.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetMetadata calls grpc.api.v1.ECGService.GetMetadata.
func (c *eCGServiceClient) GetMetadata(ctx context.Context, req *v1.GetMetadataRequest) (*v1.GetMetadataResponse, error) {
	response, err := c.getMetadata.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateMetadata calls grpc.api.v1.ECGService.UpdateMetadata.
func (c *eCGServiceClient) UpdateMetadata(ctx context.Context, req *v1.UpdateMetadataRequest) (*v1.UpdateMetadataResponse, error) {
	response, err := c.updateMetadata.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ECGServiceHandler is an implementation of the grpc.api.v1.ECGService service.
type ECGServiceHandler interface {
	GetFilters(context.Context, *v1.GetFiltersRequest) (*v1.GetFiltersResponse, error)
	ListAll(context.Context, *v1.ListAllRequest) (*v1.ListAllResponse, error)
	GetMetadata(context.Context, *v1.GetMetadataRequest) (*v1.GetMetadataResponse, error)
	UpdateMetadata(context.Context, *v1.UpdateMetadataRequest) (*v1.UpdateMetadataResponse, error)
}

// NewECGServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewECGServiceHandler(svc ECGServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eCGServiceMethods := v1.File_v1_ecg_proto.Services().ByName("ECGService").Methods()
	eCGServiceGetFiltersHandler := connect.NewUnaryHandlerSimple(
		ECGServiceGetFiltersProcedure,
		svc.GetFilters,
		connect.WithSchema(eCGServiceMethods.ByName("GetFilters")),
		connect.WithHandlerOptions(opts...),
	)
	eCGServiceListAllHandler := connect.NewUnaryHandlerSimple(
		ECGServiceListAllProcedure,
		svc.ListAll,
		connect.WithSchema(eCGServiceMethods.ByName("ListAll")),
		connect.WithHandlerOptions(opts...),
	)
	eCGServiceGetMetadataHandler := connect.NewUnaryHandlerSimple(
		ECGServiceGetMetadataProcedure,
		svc.GetMetadata,
		connect.WithSchema(eCGServiceMethods.ByName("GetMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	eCGServiceUpdateMetadataHandler := connect.NewUnaryHandlerSimple(
		ECGServiceUpdateMetadataProcedure,
		svc.UpdateMetadata,
		connect.WithSchema(eCGServiceMethods.ByName("UpdateMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	return "/grpc.api.v1.ECGService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ECGServiceGetFiltersProcedure:
			eCGServiceGetFiltersHandler.ServeHTTP(w, r)
		case ECGServiceListAllProcedure:
			eCGServiceListAllHandler.ServeHTTP(w, r)
		case ECGServiceGetMetadataProcedure:
			eCGServiceGetMetadataHandler.ServeHTTP(w, r)
		case ECGServiceUpdateMetadataProcedure:
			eCGServiceUpdateMetadataHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedECGServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedECGServiceHandler struct{}

func (UnimplementedECGServiceHandler) GetFilters(context.Context, *v1.GetFiltersRequest) (*v1.GetFiltersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.ECGService.GetFilters is not implemented"))
}

func (UnimplementedECGServiceHandler) ListAll(context.Context, *v1.ListAllRequest) (*v1.ListAllResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.ECGService.ListAll is not implemented"))
}

func (UnimplementedECGServiceHandler) GetMetadata(context.Context, *v1.GetMetadataRequest) (*v1.GetMetadataResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.ECGService.GetMetadata is not implemented"))
}

func (UnimplementedECGServiceHandler) UpdateMetadata(context.Context, *v1.UpdateMetadataRequest) (*v1.UpdateMetadataResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.ECGService.UpdateMetadata is not implemented"))
}
