// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/hl7admin.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/LIRYC-IHU/ecg-hub/internal/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HL7AdminServiceName is the fully-qualified name of the HL7AdminService service.
	HL7AdminServiceName = "grpc.api.v1.HL7AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HL7AdminServiceListPresetsProcedure is the fully-qualified name of the HL7AdminService's
	// ListPresets RPC.
	HL7AdminServiceListPresetsProcedure = "/grpc.api.v1.HL7AdminService/ListPresets"
	// HL7AdminServiceCreatePresetProcedure is the fully-qualified name of the HL7AdminService's
	// CreatePreset RPC.
	HL7AdminServiceCreatePresetProcedure = "/grpc.api.v1.HL7AdminService/CreatePreset"
	// HL7AdminServiceActivatePresetProcedure is the fully-qualified name of the HL7AdminService's
	// ActivatePreset RPC.
	HL7AdminServiceActivatePresetProcedure = "/grpc.api.v1.HL7AdminService/ActivatePreset"
	// HL7AdminServiceDeletePresetProcedure is the fully-qualified name of the HL7AdminService's
	// DeletePreset RPC.
	HL7AdminServiceDeletePresetProcedure = "/grpc.api.v1.HL7AdminService/DeletePreset"
	// HL7AdminServiceSavePresetMappingsProcedure is the fully-qualified name of the HL7AdminService's
	// SavePresetMappings RPC.
	HL7AdminServiceSavePresetMappingsProcedure = "/grpc.api.v1.HL7AdminService/SavePresetMappings"
	// HL7AdminServiceGetActiveMappingsProcedure is the fully-qualified name of the HL7AdminService's
	// GetActiveMappings RPC.
	HL7AdminServiceGetActiveMappingsProcedure = "/grpc.api.v1.HL7AdminService/GetActiveMappings"
	// HL7AdminServiceTestQueryProcedure is the fully-qualified name of the HL7AdminService's TestQuery
	// RPC.
	HL7AdminServiceTestQueryProcedure = "/grpc.api.v1.HL7AdminService/TestQuery"
	// HL7AdminServicePingProcedure is the fully-qualified name of the HL7AdminService's Ping RPC.
	HL7AdminServicePingProcedure = "/grpc.api.v1.HL7AdminService/Ping"
	// HL7AdminServiceGetSettingsProcedure is the fully-qualified name of the HL7AdminService's
	// GetSettings RPC.
	HL7AdminServiceGetSettingsProcedure = "/grpc.api.v1.HL7AdminService/GetSettings"
	// HL7AdminServiceUpdateSettingsProcedure is the fully-qualified name of the HL7AdminService's
	// UpdateSettings RPC.
	HL7AdminServiceUpdateSettingsProcedure = "/grpc.api.v1.HL7AdminService/UpdateSettings"
	// HL7AdminServiceForceRunProcedure is the fully-qualified name of the HL7AdminService's ForceRun
	// RPC.
	HL7AdminServiceForceRunProcedure = "/grpc.api.v1.HL7AdminService/ForceRun"
	// HL7AdminServiceBulkRetryProcedure is the fully-qualified name of the HL7AdminService's BulkRetry
	// RPC.
	HL7AdminServiceBulkRetryProcedure = "/grpc.api.v1.HL7AdminService/BulkRetry"
)

// HL7AdminServiceClient is a client for the grpc.api.v1.HL7AdminService service.
type HL7AdminServiceClient interface {
	ListPresets(context.Context, *v1.ListHL7PresetsRequest) (*v1.ListHL7PresetsResponse, error)
	CreatePreset(context.Context, *v1.CreateHL7PresetRequest) (*v1.CreateHL7PresetResponse, error)
	ActivatePreset(context.Context, *v1.ActivateHL7PresetRequest) (*v1.ActivateHL7PresetResponse, error)
	DeletePreset(context.Context, *v1.DeleteHL7PresetRequest) (*v1.DeleteHL7PresetResponse, error)
	SavePresetMappings(context.Context, *v1.SaveHL7PresetMappingsRequest) (*v1.SaveHL7PresetMappingsResponse, error)
	GetActiveMappings(context.Context, *v1.GetActiveHL7MappingsRequest) (*v1.GetActiveHL7MappingsResponse, error)
	TestQuery(context.Context, *v1.HL7TestQueryRequest) (*v1.HL7TestQueryResponse, error)
	Ping(context.Context, *v1.HL7PingRequest) (*v1.HL7PingResponse, error)
	GetSettings(context.Context, *v1.GetHL7SettingsRequest) (*v1.GetHL7SettingsResponse, error)
	UpdateSettings(context.Context, *v1.UpdateHL7SettingsRequest) (*v1.UpdateHL7SettingsResponse, error)
	ForceRun(context.Context, *v1.ForceHL7RunRequest) (*v1.ForceHL7RunResponse, error)
	BulkRetry(context.Context, *v1.BulkRetryHL7Request) (*v1.BulkRetryHL7Response, error)
}

// NewHL7AdminServiceClient constructs a client for the grpc.api.v1.HL7AdminService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHL7AdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HL7AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	hL7AdminServiceMethods := v1.File_v1_hl7admin_proto.Services().ByName("HL7AdminService").Methods()
	return &hL7AdminServiceClient{
		listPresets: connect.NewClient[v1.ListHL7PresetsRequest, v1.ListHL7PresetsResponse](
			httpClient,
			baseURL+HL7AdminServiceListPresetsProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("ListPresets")),
			connect.WithClientOptions(opts...),
		),
		createPreset: connect.NewClient[v1.CreateHL7PresetRequest, v1.CreateHL7PresetResponse](
			httpClient,
			baseURL+HL7AdminServiceCreatePresetProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("CreatePreset")),
			connect.WithClientOptions(opts...),
		),
		activatePreset: connect.NewClient[v1.ActivateHL7PresetRequest, v1.ActivateHL7PresetResponse](
			httpClient,
			baseURL+HL7AdminServiceActivatePresetProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("ActivatePreset")),
			connect.WithClientOptions(opts...),
		),
		deletePreset: connect.NewClient[v1.DeleteHL7PresetRequest, v1.DeleteHL7PresetResponse](
			httpClient,
			baseURL+HL7AdminServiceDeletePresetProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("DeletePreset")),
			connect.WithClientOptions(opts...),
		),
		savePresetMappings: connect.NewClient[v1.SaveHL7PresetMappingsRequest, v1.SaveHL7PresetMappingsResponse](
			httpClient,
			baseURL+HL7AdminServiceSavePresetMappingsProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("SavePresetMappings")),
			connect.WithClientOptions(opts...),
		),
		getActiveMappings: connect.NewClient[v1.GetActiveHL7MappingsRequest, v1.GetActiveHL7MappingsResponse](
			httpClient,
			baseURL+HL7AdminServiceGetActiveMappingsProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("GetActiveMappings")),
			connect.WithClientOptions(opts...),
		),
		testQuery: connect.NewClient[v1.HL7TestQueryRequest, v1.HL7TestQueryResponse](
			httpClient,
			baseURL+HL7AdminServiceTestQueryProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("TestQuery")),
			connect.WithClientOptions(opts...),
		),
		ping: connect.NewClient[v1.HL7PingRequest, v1.HL7PingResponse](
			httpClient,
			baseURL+HL7AdminServicePingProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		getSettings: connect.NewClient[v1.GetHL7SettingsRequest, v1.GetHL7SettingsResponse](
			httpClient,
			baseURL+HL7AdminServiceGetSettingsProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("GetSettings")),
			connect.WithClientOptions(opts...),
		),
		updateSettings: connect.NewClient[v1.UpdateHL7SettingsRequest, v1.UpdateHL7SettingsResponse](
			httpClient,
			baseURL+HL7AdminServiceUpdateSettingsProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("UpdateSettings")),
			connect.WithClientOptions(opts...),
		),
		forceRun: connect.NewClient[v1.ForceHL7RunRequest, v1.ForceHL7RunResponse](
			httpClient,
			baseURL+HL7AdminServiceForceRunProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("ForceRun")),
			connect.WithClientOptions(opts...),
		),
		bulkRetry: connect.NewClient[v1.BulkRetryHL7Request, v1.BulkRetryHL7Response](
			httpClient,
			baseURL+HL7AdminServiceBulkRetryProcedure,
			connect.WithSchema(hL7AdminServiceMethods.ByName("BulkRetry")),
			connect.WithClientOptions(opts...),
		),
	}
}

// hL7AdminServiceClient implements HL7AdminServiceClient.
type hL7AdminServiceClient struct {
	listPresets        *connect.Client[v1.ListHL7PresetsRequest, v1.ListHL7PresetsResponse]
	createPreset       *connect.Client[v1.CreateHL7PresetRequest, v1.CreateHL7PresetResponse]
	activatePreset     *connect.Client[v1.ActivateHL7PresetRequest, v1.ActivateHL7PresetResponse]
	deletePreset       *connect.Client[v1.DeleteHL7PresetRequest, v1.DeleteHL7PresetResponse]
	savePresetMappings *connect.Client[v1.SaveHL7PresetMappingsRequest, v1.SaveHL7PresetMappingsResponse]
	getActiveMappings  *connect.Client[v1.GetActiveHL7MappingsRequest, v1.GetActiveHL7MappingsResponse]
	testQuery          *connect.Client[v1.HL7TestQueryRequest, v1.HL7TestQueryResponse]
	ping               *connect.Client[v1.HL7PingRequest, v1.HL7PingResponse]
	getSettings        *connect.Client[v1.GetHL7SettingsRequest, v1.GetHL7SettingsResponse]
	updateSettings     *connect.Client[v1.UpdateHL7SettingsRequest, v1.UpdateHL7SettingsResponse]
	forceRun           *connect.Client[v1.ForceHL7RunRequest, v1.ForceHL7RunResponse]
	bulkRetry          *connect.Client[v1.BulkRetryHL7Request, v1.BulkRetryHL7Response]
}

// ListPresets calls grpc.api.v1.HL7AdminService.ListPresets.
func (c *hL7AdminServiceClient) ListPresets(ctx context.Context, req *v1.ListHL7PresetsRequest) (*v1.ListHL7PresetsResponse, error) {
	response, err := c.listPresets.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreatePreset calls grpc.api.v1.HL7AdminService.CreatePreset.
func (c *hL7AdminServiceClient) CreatePreset(ctx context.Context, req *v1.CreateHL7PresetRequest) (*v1.CreateHL7PresetResponse, error) {
	response, err := c.createPreset.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ActivatePreset calls grpc.api.v1.HL7AdminService.ActivatePreset.
func (c *hL7AdminServiceClient) ActivatePreset(ctx context.Context, req *v1.ActivateHL7PresetRequest) (*v1.ActivateHL7PresetResponse, error) {
	response, err := c.activatePreset.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeletePreset calls grpc.api.v1.HL7AdminService.DeletePreset.
func (c *hL7AdminServiceClient) DeletePreset(ctx context.Context, req *v1.DeleteHL7PresetRequest) (*v1.DeleteHL7PresetResponse, error) {
	response, err := c.deletePreset.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SavePresetMappings calls grpc.api.v1.HL7AdminService.SavePresetMappings.
func (c *hL7AdminServiceClient) SavePresetMappings(ctx context.Context, req *v1.SaveHL7PresetMappingsRequest) (*v1.SaveHL7PresetMappingsResponse, error) {
	response, err := c.savePresetMappings.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetActiveMappings calls grpc.api.v1.HL7AdminService.GetActiveMappings.
func (c *hL7AdminServiceClient) GetActiveMappings(ctx context.Context, req *v1.GetActiveHL7MappingsRequest) (*v1.GetActiveHL7MappingsResponse, error) {
	response, err := c.getActiveMappings.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// TestQuery calls grpc.api.v1.HL7AdminService.TestQuery.
func (c *hL7AdminServiceClient) TestQuery(ctx context.Context, req *v1.HL7TestQueryRequest) (*v1.HL7TestQueryResponse, error) {
	response, err := c.testQuery.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Ping calls grpc.api.v1.HL7AdminService.Ping.
func (c *hL7AdminServiceClient) Ping(ctx context.Context, req *v1.HL7PingRequest) (*v1.HL7PingResponse, error) {
	response, err := c.ping.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetSettings calls grpc.api.v1.HL7AdminService.GetSettings.
func (c *hL7AdminServiceClient) GetSettings(ctx context.Context, req *v1.GetHL7SettingsRequest) (*v1.GetHL7SettingsResponse, error) {
	response, err := c.getSettings.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateSettings calls grpc.api.v1.HL7AdminService.UpdateSettings.
func (c *hL7AdminServiceClient) UpdateSettings(ctx context.Context, req *v1.UpdateHL7SettingsRequest) (*v1.UpdateHL7SettingsResponse, error) {
	response, err := c.updateSettings.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ForceRun calls grpc.api.v1.HL7AdminService.ForceRun.
func (c *hL7AdminServiceClient) ForceRun(ctx context.Context, req *v1.ForceHL7RunRequest) (*v1.ForceHL7RunResponse, error) {
	response, err := c.forceRun.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// BulkRetry calls grpc.api.v1.HL7AdminService.BulkRetry.
func (c *hL7AdminServiceClient) BulkRetry(ctx context.Context, req *v1.BulkRetryHL7Request) (*v1.BulkRetryHL7Response, error) {
	response, err := c.bulkRetry.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// HL7AdminServiceHandler is an implementation of the grpc.api.v1.HL7AdminService service.
type HL7AdminServiceHandler interface {
	ListPresets(context.Context, *v1.ListHL7PresetsRequest) (*v1.ListHL7PresetsResponse, error)
	CreatePreset(context.Context, *v1.CreateHL7PresetRequest) (*v1.CreateHL7PresetResponse, error)
	ActivatePreset(context.Context, *v1.ActivateHL7PresetRequest) (*v1.ActivateHL7PresetResponse, error)
	DeletePreset(context.Context, *v1.DeleteHL7PresetRequest) (*v1.DeleteHL7PresetResponse, error)
	SavePresetMappings(context.Context, *v1.SaveHL7PresetMappingsRequest) (*v1.SaveHL7PresetMappingsResponse, error)
	GetActiveMappings(context.Context, *v1.GetActiveHL7MappingsRequest) (*v1.GetActiveHL7MappingsResponse, error)
	TestQuery(context.Context, *v1.HL7TestQueryRequest) (*v1.HL7TestQueryResponse, error)
	Ping(context.Context, *v1.HL7PingRequest) (*v1.HL7PingResponse, error)
	GetSettings(context.Context, *v1.GetHL7SettingsRequest) (*v1.GetHL7SettingsResponse, error)
	UpdateSettings(context.Context, *v1.UpdateHL7SettingsRequest) (*v1.UpdateHL7SettingsResponse, error)
	ForceRun(context.Context, *v1.ForceHL7RunRequest) (*v1.ForceHL7RunResponse, error)
	BulkRetry(context.Context, *v1.BulkRetryHL7Request) (*v1.BulkRetryHL7Response, error)
}

// NewHL7AdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHL7AdminServiceHandler(svc HL7AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	hL7AdminServiceMethods := v1.File_v1_hl7admin_proto.Services().ByName("HL7AdminService").Methods()
	hL7AdminServiceListPresetsHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceListPresetsProcedure,
		svc.ListPresets,
		connect.WithSchema(hL7AdminServiceMethods.ByName("ListPresets")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceCreatePresetHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceCreatePresetProcedure,
		svc.CreatePreset,
		connect.WithSchema(hL7AdminServiceMethods.ByName("CreatePreset")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceActivatePresetHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceActivatePresetProcedure,
		svc.ActivatePreset,
		connect.WithSchema(hL7AdminServiceMethods.ByName("ActivatePreset")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceDeletePresetHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceDeletePresetProcedure,
		svc.DeletePreset,
		connect.WithSchema(hL7AdminServiceMethods.ByName("DeletePreset")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceSavePresetMappingsHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceSavePresetMappingsProcedure,
		svc.SavePresetMappings,
		connect.WithSchema(hL7AdminServiceMethods.ByName("SavePresetMappings")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceGetActiveMappingsHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceGetActiveMappingsProcedure,
		svc.GetActiveMappings,
		connect.WithSchema(hL7AdminServiceMethods.ByName("GetActiveMappings")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceTestQueryHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceTestQueryProcedure,
		svc.TestQuery,
		connect.WithSchema(hL7AdminServiceMethods.ByName("TestQuery")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServicePingHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServicePingProcedure,
		svc.Ping,
		connect.WithSchema(hL7AdminServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceGetSettingsHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceGetSettingsProcedure,
		svc.GetSettings,
		connect.WithSchema(hL7AdminServiceMethods.ByName("GetSettings")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceUpdateSettingsHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceUpdateSettingsProcedure,
		svc.UpdateSettings,
		connect.WithSchema(hL7AdminServiceMethods.ByName("UpdateSettings")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceForceRunHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceForceRunProcedure,
		svc.ForceRun,
		connect.WithSchema(hL7AdminServiceMethods.ByName("ForceRun")),
		connect.WithHandlerOptions(opts...),
	)
	hL7AdminServiceBulkRetryHandler := connect.NewUnaryHandlerSimple(
		HL7AdminServiceBulkRetryProcedure,
		svc.BulkRetry,
		connect.WithSchema(hL7AdminServiceMethods.ByName("BulkRetry")),
		connect.WithHandlerOptions(opts...),
	)
	return "/grpc.api.v1.HL7AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HL7AdminServiceListPresetsProcedure:
			hL7AdminServiceListPresetsHandler.ServeHTTP(w, r)
		case HL7AdminServiceCreatePresetProcedure:
			hL7AdminServiceCreatePresetHandler.ServeHTTP(w, r)
		case HL7AdminServiceActivatePresetProcedure:
			hL7AdminServiceActivatePresetHandler.ServeHTTP(w, r)
		case HL7AdminServiceDeletePresetProcedure:
			hL7AdminServiceDeletePresetHandler.ServeHTTP(w, r)
		case HL7AdminServiceSavePresetMappingsProcedure:
			hL7AdminServiceSavePresetMappingsHandler.ServeHTTP(w, r)
		case HL7AdminServiceGetActiveMappingsProcedure:
			hL7AdminServiceGetActiveMappingsHandler.ServeHTTP(w, r)
		case HL7AdminServiceTestQueryProcedure:
			hL7AdminServiceTestQueryHandler.ServeHTTP(w, r)
		case HL7AdminServicePingProcedure:
			hL7AdminServicePingHandler.ServeHTTP(w, r)
		case HL7AdminServiceGetSettingsProcedure:
			hL7AdminServiceGetSettingsHandler.ServeHTTP(w, r)
		case HL7AdminServiceUpdateSettingsProcedure:
			hL7AdminServiceUpdateSettingsHandler.ServeHTTP(w, r)
		case HL7AdminServiceForceRunProcedure:
			hL7AdminServiceForceRunHandler.ServeHTTP(w, r)
		case HL7AdminServiceBulkRetryProcedure:
			hL7AdminServiceBulkRetryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHL7AdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHL7AdminServiceHandler struct{}

func (UnimplementedHL7AdminServiceHandler) ListPresets(context.Context, *v1.ListHL7PresetsRequest) (*v1.ListHL7PresetsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.ListPresets is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) CreatePreset(context.Context, *v1.CreateHL7PresetRequest) (*v1.CreateHL7PresetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.CreatePreset is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) ActivatePreset(context.Context, *v1.ActivateHL7PresetRequest) (*v1.ActivateHL7PresetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.ActivatePreset is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) DeletePreset(context.Context, *v1.DeleteHL7PresetRequest) (*v1.DeleteHL7PresetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.DeletePreset is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) SavePresetMappings(context.Context, *v1.SaveHL7PresetMappingsRequest) (*v1.SaveHL7PresetMappingsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.SavePresetMappings is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) GetActiveMappings(context.Context, *v1.GetActiveHL7MappingsRequest) (*v1.GetActiveHL7MappingsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.GetActiveMappings is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) TestQuery(context.Context, *v1.HL7TestQueryRequest) (*v1.HL7TestQueryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.TestQuery is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) Ping(context.Context, *v1.HL7PingRequest) (*v1.HL7PingResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.Ping is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) GetSettings(context.Context, *v1.GetHL7SettingsRequest) (*v1.GetHL7SettingsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.GetSettings is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) UpdateSettings(context.Context, *v1.UpdateHL7SettingsRequest) (*v1.UpdateHL7SettingsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.UpdateSettings is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) ForceRun(context.Context, *v1.ForceHL7RunRequest) (*v1.ForceHL7RunResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.ForceRun is not implemented"))
}

func (UnimplementedHL7AdminServiceHandler) BulkRetry(context.Context, *v1.BulkRetryHL7Request) (*v1.BulkRetryHL7Response, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.HL7AdminService.BulkRetry is not implemented"))
}
