// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/patient.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/LIRYC-IHU/ecg-hub/internal/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PatientServiceName is the fully-qualified name of the PatientService service.
	PatientServiceName = "grpc.api.v1.PatientService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PatientServiceSearchProcedure is the fully-qualified name of the PatientService's Search RPC.
	PatientServiceSearchProcedure = "/grpc.api.v1.PatientService/Search"
	// PatientServiceMarkECGsViewedProcedure is the fully-qualified name of the PatientService's
	// MarkECGsViewed RPC.
	PatientServiceMarkECGsViewedProcedure = "/grpc.api.v1.PatientService/MarkECGsViewed"
	// PatientServiceListECGsProcedure is the fully-qualified name of the PatientService's ListECGs RPC.
	PatientServiceListECGsProcedure = "/grpc.api.v1.PatientService/ListECGs"
)

// PatientServiceClient is a client for the grpc.api.v1.PatientService service.
type PatientServiceClient interface {
	Search(context.Context, *v1.SearchRequest) (*v1.SearchResponse, error)
	MarkECGsViewed(context.Context, *v1.MarkECGsViewedRequest) (*v1.MarkECGsViewedResponse, error)
	ListECGs(context.Context, *v1.ListECGsRequest) (*v1.ListECGsResponse, error)
}

// NewPatientServiceClient constructs a client for the grpc.api.v1.PatientService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPatientServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PatientServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	patientServiceMethods := v1.File_v1_patient_proto.Services().ByName("PatientService").Methods()
	return &patientServiceClient{
		search: connect.NewClient[v1.SearchRequest, v1.SearchResponse](
			httpClient,
			baseURL+PatientServiceSearchProcedure,
			connect.WithSchema(patientServiceMethods.ByName("Search")),
			connect.WithClientOptions(opts...),
		),
		markECGsViewed: connect.NewClient[v1.MarkECGsViewedRequest, v1.MarkECGsViewedResponse](
			httpClient,
			baseURL+PatientServiceMarkECGsViewedProcedure,
			connect.WithSchema(patientServiceMethods.ByName("MarkECGsViewed")),
			connect.WithClientOptions(opts...),
		),
		listECGs: connect.NewClient[v1.ListECGsRequest, v1.ListECGsResponse](
			httpClient,
			baseURL+PatientServiceListECGsProcedure,
			connect.WithSchema(patientServiceMethods.ByName("ListECGs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// patientServiceClient implements PatientServiceClient.
type patientServiceClient struct {
	search         *connect.Client[v1.SearchRequest, v1.SearchResponse]
	markECGsViewed *connect.Client[v1.MarkECGsViewedRequest, v1.MarkECGsViewedResponse]
	listECGs       *connect.Client[v1.ListECGsRequest, v1.ListECGsResponse]
}

// Search calls grpc.api.v1.PatientService.Search.
func (c *patientServiceClient) Search(ctx context.Context, req *v1.SearchRequest) (*v1.SearchResponse, error) {
	response, err := c.search.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// MarkECGsViewed calls grpc.api.v1.PatientService.MarkECGsViewed.
func (c *patientServiceClient) MarkECGsViewed(ctx context.Context, req *v1.MarkECGsViewedRequest) (*v1.MarkECGsViewedResponse, error) {
	response, err := c.markECGsViewed.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListECGs calls grpc.api.v1.PatientService.ListECGs.
func (c *patientServiceClient) ListECGs(ctx context.Context, req *v1.ListECGsRequest) (*v1.ListECGsResponse, error) {
	response, err := c.listECGs.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// PatientServiceHandler is an implementation of the grpc.api.v1.PatientService service.
type PatientServiceHandler interface {
	Search(context.Context, *v1.SearchRequest) (*v1.SearchResponse, error)
	MarkECGsViewed(context.Context, *v1.MarkECGsViewedRequest) (*v1.MarkECGsViewedResponse, error)
	ListECGs(context.Context, *v1.ListECGsRequest) (*v1.ListECGsResponse, error)
}

// NewPatientServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPatientServiceHandler(svc PatientServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	patientServiceMethods := v1.File_v1_patient_proto.Services().ByName("PatientService").Methods()
	patientServiceSearchHandler := connect.NewUnaryHandlerSimple(
		PatientServiceSearchProcedure,
		svc.Search,
		connect.WithSchema(patientServiceMethods.ByName("Search")),
		connect.WithHandlerOptions(opts...),
	)
	patientServiceMarkECGsViewedHandler := connect.NewUnaryHandlerSimple(
		PatientServiceMarkECGsViewedProcedure,
		svc.MarkECGsViewed,
		connect.WithSchema(patientServiceMethods.ByName("MarkECGsViewed")),
		connect.WithHandlerOptions(opts...),
	)
	patientServiceListECGsHandler := connect.NewUnaryHandlerSimple(
		PatientServiceListECGsProcedure,
		svc.ListECGs,
		connect.WithSchema(patientServiceMethods.ByName("ListECGs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/grpc.api.v1.PatientService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PatientServiceSearchProcedure:
			patientServiceSearchHandler.ServeHTTP(w, r)
		case PatientServiceMarkECGsViewedProcedure:
			patientServiceMarkECGsViewedHandler.ServeHTTP(w, r)
		case PatientServiceListECGsProcedure:
			patientServiceListECGsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPatientServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPatientServiceHandler struct{}

func (UnimplementedPatientServiceHandler) Search(context.Context, *v1.SearchRequest) (*v1.SearchResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.PatientService.Search is not implemented"))
}

func (UnimplementedPatientServiceHandler) MarkECGsViewed(context.Context, *v1.MarkECGsViewedRequest) (*v1.MarkECGsViewedResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.PatientService.MarkECGsViewed is not implemented"))
}

func (UnimplementedPatientServiceHandler) ListECGs(context.Context, *v1.ListECGsRequest) (*v1.ListECGsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.PatientService.ListECGs is not implemented"))
}
