// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/tag.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/LIRYC-IHU/ecg-hub/internal/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TagServiceName is the fully-qualified name of the TagService service.
	TagServiceName = "grpc.api.v1.TagService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TagServiceListTagsProcedure is the fully-qualified name of the TagService's ListTags RPC.
	TagServiceListTagsProcedure = "/grpc.api.v1.TagService/ListTags"
	// TagServiceCreateTagProcedure is the fully-qualified name of the TagService's CreateTag RPC.
	TagServiceCreateTagProcedure = "/grpc.api.v1.TagService/CreateTag"
	// TagServiceUpdateTagProcedure is the fully-qualified name of the TagService's UpdateTag RPC.
	TagServiceUpdateTagProcedure = "/grpc.api.v1.TagService/UpdateTag"
	// TagServiceDeleteTagProcedure is the fully-qualified name of the TagService's DeleteTag RPC.
	TagServiceDeleteTagProcedure = "/grpc.api.v1.TagService/DeleteTag"
	// TagServiceTagPatientProcedure is the fully-qualified name of the TagService's TagPatient RPC.
	TagServiceTagPatientProcedure = "/grpc.api.v1.TagService/TagPatient"
	// TagServiceUntagPatientProcedure is the fully-qualified name of the TagService's UntagPatient RPC.
	TagServiceUntagPatientProcedure = "/grpc.api.v1.TagService/UntagPatient"
	// TagServiceListPatientTagsProcedure is the fully-qualified name of the TagService's
	// ListPatientTags RPC.
	TagServiceListPatientTagsProcedure = "/grpc.api.v1.TagService/ListPatientTags"
	// TagServiceTagEcgProcedure is the fully-qualified name of the TagService's TagEcg RPC.
	TagServiceTagEcgProcedure = "/grpc.api.v1.TagService/TagEcg"
	// TagServiceUntagEcgProcedure is the fully-qualified name of the TagService's UntagEcg RPC.
	TagServiceUntagEcgProcedure = "/grpc.api.v1.TagService/UntagEcg"
	// TagServiceListEcgTagsProcedure is the fully-qualified name of the TagService's ListEcgTags RPC.
	TagServiceListEcgTagsProcedure = "/grpc.api.v1.TagService/ListEcgTags"
	// TagServiceBatchGetPatientTagsProcedure is the fully-qualified name of the TagService's
	// BatchGetPatientTags RPC.
	TagServiceBatchGetPatientTagsProcedure = "/grpc.api.v1.TagService/BatchGetPatientTags"
	// TagServiceBatchGetEcgTagsProcedure is the fully-qualified name of the TagService's
	// BatchGetEcgTags RPC.
	TagServiceBatchGetEcgTagsProcedure = "/grpc.api.v1.TagService/BatchGetEcgTags"
)

// TagServiceClient is a client for the grpc.api.v1.TagService service.
type TagServiceClient interface {
	ListTags(context.Context, *v1.ListTagsRequest) (*v1.ListTagsResponse, error)
	CreateTag(context.Context, *v1.CreateTagRequest) (*v1.CreateTagResponse, error)
	UpdateTag(context.Context, *v1.UpdateTagRequest) (*v1.UpdateTagResponse, error)
	DeleteTag(context.Context, *v1.DeleteTagRequest) (*v1.DeleteTagResponse, error)
	TagPatient(context.Context, *v1.TagPatientRequest) (*v1.TagPatientResponse, error)
	UntagPatient(context.Context, *v1.UntagPatientRequest) (*v1.UntagPatientResponse, error)
	ListPatientTags(context.Context, *v1.ListPatientTagsRequest) (*v1.ListPatientTagsResponse, error)
	TagEcg(context.Context, *v1.TagEcgRequest) (*v1.TagEcgResponse, error)
	UntagEcg(context.Context, *v1.UntagEcgRequest) (*v1.UntagEcgResponse, error)
	ListEcgTags(context.Context, *v1.ListEcgTagsRequest) (*v1.ListEcgTagsResponse, error)
	BatchGetPatientTags(context.Context, *v1.BatchGetPatientTagsRequest) (*v1.BatchGetPatientTagsResponse, error)
	BatchGetEcgTags(context.Context, *v1.BatchGetEcgTagsRequest) (*v1.BatchGetEcgTagsResponse, error)
}

// NewTagServiceClient constructs a client for the grpc.api.v1.TagService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTagServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TagServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tagServiceMethods := v1.File_v1_tag_proto.Services().ByName("TagService").Methods()
	return &tagServiceClient{
		listTags: connect.NewClient[v1.ListTagsRequest, v1.ListTagsResponse](
			httpClient,
			baseURL+TagServiceListTagsProcedure,
			connect.WithSchema(tagServiceMethods.ByName("ListTags")),
			connect.WithClientOptions(opts...),
		),
		createTag: connect.NewClient[v1.CreateTagRequest, v1.CreateTagResponse](
			httpClient,
			baseURL+TagServiceCreateTagProcedure,
			connect.WithSchema(tagServiceMethods.ByName("CreateTag")),
			connect.WithClientOptions(opts...),
		),
		updateTag: connect.NewClient[v1.UpdateTagRequest, v1.UpdateTagResponse](
			httpClient,
			baseURL+TagServiceUpdateTagProcedure,
			connect.WithSchema(tagServiceMethods.ByName("UpdateTag")),
			connect.WithClientOptions(opts...),
		),
		deleteTag: connect.NewClient[v1.DeleteTagRequest, v1.DeleteTagResponse](
			httpClient,
			baseURL+TagServiceDeleteTagProcedure,
			connect.WithSchema(tagServiceMethods.ByName("DeleteTag")),
			connect.WithClientOptions(opts...),
		),
		tagPatient: connect.NewClient[v1.TagPatientRequest, v1.TagPatientResponse](
			httpClient,
			baseURL+TagServiceTagPatientProcedure,
			connect.WithSchema(tagServiceMethods.ByName("TagPatient")),
			connect.WithClientOptions(opts...),
		),
		untagPatient: connect.NewClient[v1.UntagPatientRequest, v1.UntagPatientResponse](
			httpClient,
			baseURL+TagServiceUntagPatientProcedure,
			connect.WithSchema(tagServiceMethods.ByName("UntagPatient")),
			connect.WithClientOptions(opts...),
		),
		listPatientTags: connect.NewClient[v1.ListPatientTagsRequest, v1.ListPatientTagsResponse](
			httpClient,
			baseURL+TagServiceListPatientTagsProcedure,
			connect.WithSchema(tagServiceMethods.ByName("ListPatientTags")),
			connect.WithClientOptions(opts...),
		),
		tagEcg: connect.NewClient[v1.TagEcgRequest, v1.TagEcgResponse](
			httpClient,
			baseURL+TagServiceTagEcgProcedure,
			connect.WithSchema(tagServiceMethods.ByName("TagEcg")),
			connect.WithClientOptions(opts...),
		),
		untagEcg: connect.NewClient[v1.UntagEcgRequest, v1.UntagEcgResponse](
			httpClient,
			baseURL+TagServiceUntagEcgProcedure,
			connect.WithSchema(tagServiceMethods.ByName("UntagEcg")),
			connect.WithClientOptions(opts...),
		),
		listEcgTags: connect.NewClient[v1.ListEcgTagsRequest, v1.ListEcgTagsResponse](
			httpClient,
			baseURL+TagServiceListEcgTagsProcedure,
			connect.WithSchema(tagServiceMethods.ByName("ListEcgTags")),
			connect.WithClientOptions(opts...),
		),
		batchGetPatientTags: connect.NewClient[v1.BatchGetPatientTagsRequest, v1.BatchGetPatientTagsResponse](
			httpClient,
			baseURL+TagServiceBatchGetPatientTagsProcedure,
			connect.WithSchema(tagServiceMethods.ByName("BatchGetPatientTags")),
			connect.WithClientOptions(opts...),
		),
		batchGetEcgTags: connect.NewClient[v1.BatchGetEcgTagsRequest, v1.BatchGetEcgTagsResponse](
			httpClient,
			baseURL+TagServiceBatchGetEcgTagsProcedure,
			connect.WithSchema(tagServiceMethods.ByName("BatchGetEcgTags")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tagServiceClient implements TagServiceClient.
type tagServiceClient struct {
	listTags            *connect.Client[v1.ListTagsRequest, v1.ListTagsResponse]
	createTag           *connect.Client[v1.CreateTagRequest, v1.CreateTagResponse]
	updateTag           *connect.Client[v1.UpdateTagRequest, v1.UpdateTagResponse]
	deleteTag           *connect.Client[v1.DeleteTagRequest, v1.DeleteTagResponse]
	tagPatient          *connect.Client[v1.TagPatientRequest, v1.TagPatientResponse]
	untagPatient        *connect.Client[v1.UntagPatientRequest, v1.UntagPatientResponse]
	listPatientTags     *connect.Client[v1.ListPatientTagsRequest, v1.ListPatientTagsResponse]
	tagEcg              *connect.Client[v1.TagEcgRequest, v1.TagEcgResponse]
	untagEcg            *connect.Client[v1.UntagEcgRequest, v1.UntagEcgResponse]
	listEcgTags         *connect.Client[v1.ListEcgTagsRequest, v1.ListEcgTagsResponse]
	batchGetPatientTags *connect.Client[v1.BatchGetPatientTagsRequest, v1.BatchGetPatientTagsResponse]
	batchGetEcgTags     *connect.Client[v1.BatchGetEcgTagsRequest, v1.BatchGetEcgTagsResponse]
}

// ListTags calls grpc.api.v1.TagService.ListTags.
func (c *tagServiceClient) ListTags(ctx context.Context, req *v1.ListTagsRequest) (*v1.ListTagsResponse, error) {
	response, err := c.listTags.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateTag calls grpc.api.v1.TagService.CreateTag.
func (c *tagServiceClient) CreateTag(ctx context.Context, req *v1.CreateTagRequest) (*v1.CreateTagResponse, error) {
	response, err := c.createTag.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateTag calls grpc.api.v1.TagService.UpdateTag.
func (c *tagServiceClient) UpdateTag(ctx context.Context, req *v1.UpdateTagRequest) (*v1.UpdateTagResponse, error) {
	response, err := c.updateTag.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteTag calls grpc.api.v1.TagService.DeleteTag.
func (c *tagServiceClient) DeleteTag(ctx context.Context, req *v1.DeleteTagRequest) (*v1.DeleteTagResponse, error) {
	response, err := c.deleteTag.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// TagPatient calls grpc.api.v1.TagService.TagPatient.
func (c *tagServiceClient) TagPatient(ctx context.Context, req *v1.TagPatientRequest) (*v1.TagPatientResponse, error) {
	response, err := c.tagPatient.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UntagPatient calls grpc.api.v1.TagService.UntagPatient.
func (c *tagServiceClient) UntagPatient(ctx context.Context, req *v1.UntagPatientRequest) (*v1.UntagPatientResponse, error) {
	response, err := c.untagPatient.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListPatientTags calls grpc.api.v1.TagService.ListPatientTags.
func (c *tagServiceClient) ListPatientTags(ctx context.Context, req *v1.ListPatientTagsRequest) (*v1.ListPatientTagsResponse, error) {
	response, err := c.listPatientTags.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// TagEcg calls grpc.api.v1.TagService.TagEcg.
func (c *tagServiceClient) TagEcg(ctx context.Context, req *v1.TagEcgRequest) (*v1.TagEcgResponse, error) {
	response, err := c.tagEcg.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UntagEcg calls grpc.api.v1.TagService.UntagEcg.
func (c *tagServiceClient) UntagEcg(ctx context.Context, req *v1.UntagEcgRequest) (*v1.UntagEcgResponse, error) {
	response, err := c.untagEcg.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListEcgTags calls grpc.api.v1.TagService.ListEcgTags.
func (c *tagServiceClient) ListEcgTags(ctx context.Context, req *v1.ListEcgTagsRequest) (*v1.ListEcgTagsResponse, error) {
	response, err := c.listEcgTags.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// BatchGetPatientTags calls grpc.api.v1.TagService.BatchGetPatientTags.
func (c *tagServiceClient) BatchGetPatientTags(ctx context.Context, req *v1.BatchGetPatientTagsRequest) (*v1.BatchGetPatientTagsResponse, error) {
	response, err := c.batchGetPatientTags.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// BatchGetEcgTags calls grpc.api.v1.TagService.BatchGetEcgTags.
func (c *tagServiceClient) BatchGetEcgTags(ctx context.Context, req *v1.BatchGetEcgTagsRequest) (*v1.BatchGetEcgTagsResponse, error) {
	response, err := c.batchGetEcgTags.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// TagServiceHandler is an implementation of the grpc.api.v1.TagService service.
type TagServiceHandler interface {
	ListTags(context.Context, *v1.ListTagsRequest) (*v1.ListTagsResponse, error)
	CreateTag(context.Context, *v1.CreateTagRequest) (*v1.CreateTagResponse, error)
	UpdateTag(context.Context, *v1.UpdateTagRequest) (*v1.UpdateTagResponse, error)
	DeleteTag(context.Context, *v1.DeleteTagRequest) (*v1.DeleteTagResponse, error)
	TagPatient(context.Context, *v1.TagPatientRequest) (*v1.TagPatientResponse, error)
	UntagPatient(context.Context, *v1.UntagPatientRequest) (*v1.UntagPatientResponse, error)
	ListPatientTags(context.Context, *v1.ListPatientTagsRequest) (*v1.ListPatientTagsResponse, error)
	TagEcg(context.Context, *v1.TagEcgRequest) (*v1.TagEcgResponse, error)
	UntagEcg(context.Context, *v1.UntagEcgRequest) (*v1.UntagEcgResponse, error)
	ListEcgTags(context.Context, *v1.ListEcgTagsRequest) (*v1.ListEcgTagsResponse, error)
	BatchGetPatientTags(context.Context, *v1.BatchGetPatientTagsRequest) (*v1.BatchGetPatientTagsResponse, error)
	BatchGetEcgTags(context.Context, *v1.BatchGetEcgTagsRequest) (*v1.BatchGetEcgTagsResponse, error)
}

// NewTagServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTagServiceHandler(svc TagServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tagServiceMethods := v1.File_v1_tag_proto.Services().ByName("TagService").Methods()
	tagServiceListTagsHandler := connect.NewUnaryHandlerSimple(
		TagServiceListTagsProcedure,
		svc.ListTags,
		connect.WithSchema(tagServiceMethods.ByName("ListTags")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceCreateTagHandler := connect.NewUnaryHandlerSimple(
		TagServiceCreateTagProcedure,
		svc.CreateTag,
		connect.WithSchema(tagServiceMethods.ByName("CreateTag")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceUpdateTagHandler := connect.NewUnaryHandlerSimple(
		TagServiceUpdateTagProcedure,
		svc.UpdateTag,
		connect.WithSchema(tagServiceMethods.ByName("UpdateTag")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceDeleteTagHandler := connect.NewUnaryHandlerSimple(
		TagServiceDeleteTagProcedure,
		svc.DeleteTag,
		connect.WithSchema(tagServiceMethods.ByName("DeleteTag")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceTagPatientHandler := connect.NewUnaryHandlerSimple(
		TagServiceTagPatientProcedure,
		svc.TagPatient,
		connect.WithSchema(tagServiceMethods.ByName("TagPatient")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceUntagPatientHandler := connect.NewUnaryHandlerSimple(
		TagServiceUntagPatientProcedure,
		svc.UntagPatient,
		connect.WithSchema(tagServiceMethods.ByName("UntagPatient")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceListPatientTagsHandler := connect.NewUnaryHandlerSimple(
		TagServiceListPatientTagsProcedure,
		svc.ListPatientTags,
		connect.WithSchema(tagServiceMethods.ByName("ListPatientTags")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceTagEcgHandler := connect.NewUnaryHandlerSimple(
		TagServiceTagEcgProcedure,
		svc.TagEcg,
		connect.WithSchema(tagServiceMethods.ByName("TagEcg")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceUntagEcgHandler := connect.NewUnaryHandlerSimple(
		TagServiceUntagEcgProcedure,
		svc.UntagEcg,
		connect.WithSchema(tagServiceMethods.ByName("UntagEcg")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceListEcgTagsHandler := connect.NewUnaryHandlerSimple(
		TagServiceListEcgTagsProcedure,
		svc.ListEcgTags,
		connect.WithSchema(tagServiceMethods.ByName("ListEcgTags")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceBatchGetPatientTagsHandler := connect.NewUnaryHandlerSimple(
		TagServiceBatchGetPatientTagsProcedure,
		svc.BatchGetPatientTags,
		connect.WithSchema(tagServiceMethods.ByName("BatchGetPatientTags")),
		connect.WithHandlerOptions(opts...),
	)
	tagServiceBatchGetEcgTagsHandler := connect.NewUnaryHandlerSimple(
		TagServiceBatchGetEcgTagsProcedure,
		svc.BatchGetEcgTags,
		connect.WithSchema(tagServiceMethods.ByName("BatchGetEcgTags")),
		connect.WithHandlerOptions(opts...),
	)
	return "/grpc.api.v1.TagService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TagServiceListTagsProcedure:
			tagServiceListTagsHandler.ServeHTTP(w, r)
		case TagServiceCreateTagProcedure:
			tagServiceCreateTagHandler.ServeHTTP(w, r)
		case TagServiceUpdateTagProcedure:
			tagServiceUpdateTagHandler.ServeHTTP(w, r)
		case TagServiceDeleteTagProcedure:
			tagServiceDeleteTagHandler.ServeHTTP(w, r)
		case TagServiceTagPatientProcedure:
			tagServiceTagPatientHandler.ServeHTTP(w, r)
		case TagServiceUntagPatientProcedure:
			tagServiceUntagPatientHandler.ServeHTTP(w, r)
		case TagServiceListPatientTagsProcedure:
			tagServiceListPatientTagsHandler.ServeHTTP(w, r)
		case TagServiceTagEcgProcedure:
			tagServiceTagEcgHandler.ServeHTTP(w, r)
		case TagServiceUntagEcgProcedure:
			tagServiceUntagEcgHandler.ServeHTTP(w, r)
		case TagServiceListEcgTagsProcedure:
			tagServiceListEcgTagsHandler.ServeHTTP(w, r)
		case TagServiceBatchGetPatientTagsProcedure:
			tagServiceBatchGetPatientTagsHandler.ServeHTTP(w, r)
		case TagServiceBatchGetEcgTagsProcedure:
			tagServiceBatchGetEcgTagsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTagServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTagServiceHandler struct{}

func (UnimplementedTagServiceHandler) ListTags(context.Context, *v1.ListTagsRequest) (*v1.ListTagsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.ListTags is not implemented"))
}

func (UnimplementedTagServiceHandler) CreateTag(context.Context, *v1.CreateTagRequest) (*v1.CreateTagResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.CreateTag is not implemented"))
}

func (UnimplementedTagServiceHandler) UpdateTag(context.Context, *v1.UpdateTagRequest) (*v1.UpdateTagResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.UpdateTag is not implemented"))
}

func (UnimplementedTagServiceHandler) DeleteTag(context.Context, *v1.DeleteTagRequest) (*v1.DeleteTagResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.DeleteTag is not implemented"))
}

func (UnimplementedTagServiceHandler) TagPatient(context.Context, *v1.TagPatientRequest) (*v1.TagPatientResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.TagPatient is not implemented"))
}

func (UnimplementedTagServiceHandler) UntagPatient(context.Context, *v1.UntagPatientRequest) (*v1.UntagPatientResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.UntagPatient is not implemented"))
}

func (UnimplementedTagServiceHandler) ListPatientTags(context.Context, *v1.ListPatientTagsRequest) (*v1.ListPatientTagsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.ListPatientTags is not implemented"))
}

func (UnimplementedTagServiceHandler) TagEcg(context.Context, *v1.TagEcgRequest) (*v1.TagEcgResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.TagEcg is not implemented"))
}

func (UnimplementedTagServiceHandler) UntagEcg(context.Context, *v1.UntagEcgRequest) (*v1.UntagEcgResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.UntagEcg is not implemented"))
}

func (UnimplementedTagServiceHandler) ListEcgTags(context.Context, *v1.ListEcgTagsRequest) (*v1.ListEcgTagsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.ListEcgTags is not implemented"))
}

func (UnimplementedTagServiceHandler) BatchGetPatientTags(context.Context, *v1.BatchGetPatientTagsRequest) (*v1.BatchGetPatientTagsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.BatchGetPatientTags is not implemented"))
}

func (UnimplementedTagServiceHandler) BatchGetEcgTags(context.Context, *v1.BatchGetEcgTagsRequest) (*v1.BatchGetEcgTagsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc.api.v1.TagService.BatchGetEcgTags is not implemented"))
}
