// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/admin.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{1}
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // kept for the audit trail; the name itself is immutable
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{6}
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{8}
}

type AppUser struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId      string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Provider        string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	RoleName        string                 `protobuf:"bytes,4,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleManuallySet bool                   `protobuf:"varint,5,opt,name=role_manually_set,json=roleManuallySet,proto3" json:"role_manually_set,omitempty"`
	LastLogin       string                 `protobuf:"bytes,6,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"` // RFC3339
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppUser) Reset() {
	*x = AppUser{}
	mi := &file_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppUser) ProtoMessage() {}

func (x *AppUser) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppUser.ProtoReflect.Descriptor instead.
func (*AppUser) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AppUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppUser) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *AppUser) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AppUser) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *AppUser) GetRoleManuallySet() bool {
	if x != nil {
		return x.RoleManuallySet
	}
	return false
}

func (x *AppUser) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

type ListAppUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppUsersRequest) Reset() {
	*x = ListAppUsersRequest{}
	mi := &file_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppUsersRequest) ProtoMessage() {}

func (x *ListAppUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppUsersRequest.ProtoReflect.Descriptor instead.
func (*ListAppUsersRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{10}
}

type ListAppUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*AppUser             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppUsersResponse) Reset() {
	*x = ListAppUsersResponse{}
	mi := &file_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppUsersResponse) ProtoMessage() {}

func (x *ListAppUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppUsersResponse.ProtoReflect.Descriptor instead.
func (*ListAppUsersResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListAppUsersResponse) GetUsers() []*AppUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListAppUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SetAppUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppUserRoleRequest) Reset() {
	*x = SetAppUserRoleRequest{}
	mi := &file_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppUserRoleRequest) ProtoMessage() {}

func (x *SetAppUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppUserRoleRequest.ProtoReflect.Descriptor instead.
func (*SetAppUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *SetAppUserRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetAppUserRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SetAppUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppUserRoleResponse) Reset() {
	*x = SetAppUserRoleResponse{}
	mi := &file_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppUserRoleResponse) ProtoMessage() {}

func (x *SetAppUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppUserRoleResponse.ProtoReflect.Descriptor instead.
func (*SetAppUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{13}
}

type DeleteAppUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppUserRequest) Reset() {
	*x = DeleteAppUserRequest{}
	mi := &file_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppUserRequest) ProtoMessage() {}

func (x *DeleteAppUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteAppUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAppUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppUserResponse) Reset() {
	*x = DeleteAppUserResponse{}
	mi := &file_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppUserResponse) ProtoMessage() {}

func (x *DeleteAppUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{15}
}

// CreateLocalUser adds a username/password account. Only meaningful when the
// local provider is enabled; sites on OIDC/LDAP provision users there.
type CreateLocalUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocalUserRequest) Reset() {
	*x = CreateLocalUserRequest{}
	mi := &file_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocalUserRequest) ProtoMessage() {}

func (x *CreateLocalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocalUserRequest.ProtoReflect.Descriptor instead.
func (*CreateLocalUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *CreateLocalUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateLocalUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateLocalUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateLocalUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ecg_hub_users.id — the identity the app keys on
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocalUserResponse) Reset() {
	*x = CreateLocalUserResponse{}
	mi := &file_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocalUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocalUserResponse) ProtoMessage() {}

func (x *CreateLocalUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocalUserResponse.ProtoReflect.Descriptor instead.
func (*CreateLocalUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *CreateLocalUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLocalUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateLocalUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 UTC
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"` // resolved display name; empty if unknown
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ResourceId    string                 `protobuf:"bytes,6,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,7,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"` // JSONB passthrough, "{}" when empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AuditLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditLog) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditLog) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

type ListAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"` // YYYY-MM-DD inclusive
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`     // YYYY-MM-DD inclusive
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,6,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsRequest) Reset() {
	*x = ListAuditLogsRequest{}
	mi := &file_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest) ProtoMessage() {}

func (x *ListAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *ListAuditLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAuditLogsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListAuditLogsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ListAuditLogsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ListAuditLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuditLogsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*AuditLog            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsResponse) Reset() {
	*x = ListAuditLogsResponse{}
	mi := &file_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsResponse) ProtoMessage() {}

func (x *ListAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListAuditLogsResponse) GetData() []*AuditLog {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListAuditLogsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAuditLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuditLogsResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{21}
}

type GetStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hl7Pending      int64                  `protobuf:"varint,1,opt,name=hl7_pending,json=hl7Pending,proto3" json:"hl7_pending,omitempty"`
	Hl7Success      int64                  `protobuf:"varint,2,opt,name=hl7_success,json=hl7Success,proto3" json:"hl7_success,omitempty"`
	Hl7Exhausted    int64                  `protobuf:"varint,3,opt,name=hl7_exhausted,json=hl7Exhausted,proto3" json:"hl7_exhausted,omitempty"`
	TotalEcgs       int64                  `protobuf:"varint,4,opt,name=total_ecgs,json=totalEcgs,proto3" json:"total_ecgs,omitempty"`
	TotalPatients   int64                  `protobuf:"varint,5,opt,name=total_patients,json=totalPatients,proto3" json:"total_patients,omitempty"`
	QuarantineCount int64                  `protobuf:"varint,6,opt,name=quarantine_count,json=quarantineCount,proto3" json:"quarantine_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *GetStatsResponse) GetHl7Pending() int64 {
	if x != nil {
		return x.Hl7Pending
	}
	return 0
}

func (x *GetStatsResponse) GetHl7Success() int64 {
	if x != nil {
		return x.Hl7Success
	}
	return 0
}

func (x *GetStatsResponse) GetHl7Exhausted() int64 {
	if x != nil {
		return x.Hl7Exhausted
	}
	return 0
}

func (x *GetStatsResponse) GetTotalEcgs() int64 {
	if x != nil {
		return x.TotalEcgs
	}
	return 0
}

func (x *GetStatsResponse) GetTotalPatients() int64 {
	if x != nil {
		return x.TotalPatients
	}
	return 0
}

func (x *GetStatsResponse) GetQuarantineCount() int64 {
	if x != nil {
		return x.QuarantineCount
	}
	return 0
}

type VolumeMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Available     int64                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	MaxSize       string                 `protobuf:"bytes,4,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMetric) Reset() {
	*x = VolumeMetric{}
	mi := &file_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMetric) ProtoMessage() {}

func (x *VolumeMetric) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMetric.ProtoReflect.Descriptor instead.
func (*VolumeMetric) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *VolumeMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeMetric) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *VolumeMetric) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *VolumeMetric) GetMaxSize() string {
	if x != nil {
		return x.MaxSize
	}
	return ""
}

type GetStorageMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageMetricsRequest) Reset() {
	*x = GetStorageMetricsRequest{}
	mi := &file_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageMetricsRequest) ProtoMessage() {}

func (x *GetStorageMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetStorageMetricsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{24}
}

type GetStorageMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*VolumeMetric        `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Backend       *StorageBackendInfo    `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageMetricsResponse) Reset() {
	*x = GetStorageMetricsResponse{}
	mi := &file_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageMetricsResponse) ProtoMessage() {}

func (x *GetStorageMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetStorageMetricsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *GetStorageMetricsResponse) GetVolumes() []*VolumeMetric {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *GetStorageMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetStorageMetricsResponse) GetBackend() *StorageBackendInfo {
	if x != nil {
		return x.Backend
	}
	return nil
}

// StorageBackendInfo tells the admin screen where files actually live. With an
// object-storage backend the local volume above is only the upload spool, so
// showing its size as "ECG storage" would misreport both what is stored and
// what the free space means.
type StorageBackendInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Kind     string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // "local" | "s3"
	Bucket   string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Endpoint string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Files written locally and not yet uploaded, and the age of the oldest.
	// A backlog that does not shrink means the bucket is unreachable.
	PendingUploads       int64 `protobuf:"varint,4,opt,name=pending_uploads,json=pendingUploads,proto3" json:"pending_uploads,omitempty"`
	OldestPendingSeconds int64 `protobuf:"varint,5,opt,name=oldest_pending_seconds,json=oldestPendingSeconds,proto3" json:"oldest_pending_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StorageBackendInfo) Reset() {
	*x = StorageBackendInfo{}
	mi := &file_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBackendInfo) ProtoMessage() {}

func (x *StorageBackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBackendInfo.ProtoReflect.Descriptor instead.
func (*StorageBackendInfo) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *StorageBackendInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StorageBackendInfo) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *StorageBackendInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *StorageBackendInfo) GetPendingUploads() int64 {
	if x != nil {
		return x.PendingUploads
	}
	return 0
}

func (x *StorageBackendInfo) GetOldestPendingSeconds() int64 {
	if x != nil {
		return x.OldestPendingSeconds
	}
	return 0
}

type ErrorEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Route         string                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	RequestUri    string                 `protobuf:"bytes,6,opt,name=request_uri,json=requestUri,proto3" json:"request_uri,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DurationMs    float64                `protobuf:"fixed64,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEntry) Reset() {
	*x = ErrorEntry{}
	mi := &file_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEntry) ProtoMessage() {}

func (x *ErrorEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEntry.ProtoReflect.Descriptor instead.
func (*ErrorEntry) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *ErrorEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ErrorEntry) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ErrorEntry) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *ErrorEntry) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ErrorEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorEntry) GetRequestUri() string {
	if x != nil {
		return x.RequestUri
	}
	return ""
}

func (x *ErrorEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ErrorEntry) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type GetRecentErrorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentErrorsRequest) Reset() {
	*x = GetRecentErrorsRequest{}
	mi := &file_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentErrorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentErrorsRequest) ProtoMessage() {}

func (x *GetRecentErrorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentErrorsRequest.ProtoReflect.Descriptor instead.
func (*GetRecentErrorsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *GetRecentErrorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecentErrorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*ErrorEntry          `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentErrorsResponse) Reset() {
	*x = GetRecentErrorsResponse{}
	mi := &file_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentErrorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentErrorsResponse) ProtoMessage() {}

func (x *GetRecentErrorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentErrorsResponse.ProtoReflect.Descriptor instead.
func (*GetRecentErrorsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *GetRecentErrorsResponse) GetErrors() []*ErrorEntry {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetUserDefaultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDefaultsRequest) Reset() {
	*x = GetUserDefaultsRequest{}
	mi := &file_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDefaultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDefaultsRequest) ProtoMessage() {}

func (x *GetUserDefaultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDefaultsRequest.ProtoReflect.Descriptor instead.
func (*GetUserDefaultsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{30}
}

type GetUserDefaultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultRole   string                 `protobuf:"bytes,1,opt,name=default_role,json=defaultRole,proto3" json:"default_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDefaultsResponse) Reset() {
	*x = GetUserDefaultsResponse{}
	mi := &file_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDefaultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDefaultsResponse) ProtoMessage() {}

func (x *GetUserDefaultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDefaultsResponse.ProtoReflect.Descriptor instead.
func (*GetUserDefaultsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *GetUserDefaultsResponse) GetDefaultRole() string {
	if x != nil {
		return x.DefaultRole
	}
	return ""
}

type SetUserDefaultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultRole   string                 `protobuf:"bytes,1,opt,name=default_role,json=defaultRole,proto3" json:"default_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserDefaultsRequest) Reset() {
	*x = SetUserDefaultsRequest{}
	mi := &file_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDefaultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDefaultsRequest) ProtoMessage() {}

func (x *SetUserDefaultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDefaultsRequest.ProtoReflect.Descriptor instead.
func (*SetUserDefaultsRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{32}
}

func (x *SetUserDefaultsRequest) GetDefaultRole() string {
	if x != nil {
		return x.DefaultRole
	}
	return ""
}

type SetUserDefaultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultRole   string                 `protobuf:"bytes,1,opt,name=default_role,json=defaultRole,proto3" json:"default_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserDefaultsResponse) Reset() {
	*x = SetUserDefaultsResponse{}
	mi := &file_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDefaultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDefaultsResponse) ProtoMessage() {}

func (x *SetUserDefaultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDefaultsResponse.ProtoReflect.Descriptor instead.
func (*SetUserDefaultsResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{33}
}

func (x *SetUserDefaultsResponse) GetDefaultRole() string {
	if x != nil {
		return x.DefaultRole
	}
	return ""
}

type QuarantineEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ReceivedAt    string                 `protobuf:"bytes,4,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"` // RFC3339
	ErrorReason   string                 `protobuf:"bytes,5,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"` // "error" | "unidentified"
	Vendor        string                 `protobuf:"bytes,7,opt,name=vendor,proto3" json:"vendor,omitempty"`
	RecordedAt    string                 `protobuf:"bytes,8,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`       // RFC3339, unidentified only
	MetadataJson  string                 `protobuf:"bytes,9,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"` // extracted demographics, unidentified only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuarantineEntry) Reset() {
	*x = QuarantineEntry{}
	mi := &file_v1_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuarantineEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuarantineEntry) ProtoMessage() {}

func (x *QuarantineEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuarantineEntry.ProtoReflect.Descriptor instead.
func (*QuarantineEntry) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{34}
}

func (x *QuarantineEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuarantineEntry) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *QuarantineEntry) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *QuarantineEntry) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *QuarantineEntry) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *QuarantineEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *QuarantineEntry) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *QuarantineEntry) GetRecordedAt() string {
	if x != nil {
		return x.RecordedAt
	}
	return ""
}

func (x *QuarantineEntry) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type ListQuarantineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuarantineRequest) Reset() {
	*x = ListQuarantineRequest{}
	mi := &file_v1_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuarantineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuarantineRequest) ProtoMessage() {}

func (x *ListQuarantineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuarantineRequest.ProtoReflect.Descriptor instead.
func (*ListQuarantineRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{35}
}

func (x *ListQuarantineRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListQuarantineRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListQuarantineRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListQuarantineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*QuarantineEntry     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuarantineResponse) Reset() {
	*x = ListQuarantineResponse{}
	mi := &file_v1_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuarantineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuarantineResponse) ProtoMessage() {}

func (x *ListQuarantineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuarantineResponse.ProtoReflect.Descriptor instead.
func (*ListQuarantineResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{36}
}

func (x *ListQuarantineResponse) GetData() []*QuarantineEntry {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListQuarantineResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListQuarantineResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListQuarantineResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type DeleteQuarantineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuarantineRequest) Reset() {
	*x = DeleteQuarantineRequest{}
	mi := &file_v1_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuarantineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuarantineRequest) ProtoMessage() {}

func (x *DeleteQuarantineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuarantineRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuarantineRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteQuarantineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteQuarantineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuarantineResponse) Reset() {
	*x = DeleteQuarantineResponse{}
	mi := &file_v1_admin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuarantineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuarantineResponse) ProtoMessage() {}

func (x *DeleteQuarantineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuarantineResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuarantineResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{38}
}

type AssignQuarantineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	CreateNew     bool                   `protobuf:"varint,3,opt,name=create_new,json=createNew,proto3" json:"create_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignQuarantineRequest) Reset() {
	*x = AssignQuarantineRequest{}
	mi := &file_v1_admin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignQuarantineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignQuarantineRequest) ProtoMessage() {}

func (x *AssignQuarantineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignQuarantineRequest.ProtoReflect.Descriptor instead.
func (*AssignQuarantineRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{39}
}

func (x *AssignQuarantineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignQuarantineRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AssignQuarantineRequest) GetCreateNew() bool {
	if x != nil {
		return x.CreateNew
	}
	return false
}

type AssignQuarantineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignQuarantineResponse) Reset() {
	*x = AssignQuarantineResponse{}
	mi := &file_v1_admin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignQuarantineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignQuarantineResponse) ProtoMessage() {}

func (x *AssignQuarantineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignQuarantineResponse.ProtoReflect.Descriptor instead.
func (*AssignQuarantineResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_proto_rawDescGZIP(), []int{40}
}

func (x *AssignQuarantineResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignQuarantineResponse) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AssignQuarantineResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_v1_admin_proto protoreflect.FileDescriptor

const file_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/admin.proto\x12\vgrpc.api.v1\"n\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\"\x12\n" +
	"\x10ListRolesRequest\"R\n" +
	"\x11ListRolesResponse\x12'\n" +
	"\x05roles\x18\x01 \x03(\v2\x11.grpc.api.v1.RoleR\x05roles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"k\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\";\n" +
	"\x12CreateRoleResponse\x12%\n" +
	"\x04role\x18\x01 \x01(\v2\x11.grpc.api.v1.RoleR\x04role\"{\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\"\x14\n" +
	"\x12UpdateRoleResponse\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteRoleResponse\"\xbe\x01\n" +
	"\aAppUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x1b\n" +
	"\trole_name\x18\x04 \x01(\tR\broleName\x12*\n" +
	"\x11role_manually_set\x18\x05 \x01(\bR\x0froleManuallySet\x12\x1d\n" +
	"\n" +
	"last_login\x18\x06 \x01(\tR\tlastLogin\"\x15\n" +
	"\x13ListAppUsersRequest\"X\n" +
	"\x14ListAppUsersResponse\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.grpc.api.v1.AppUserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\";\n" +
	"\x15SetAppUserRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x18\n" +
	"\x16SetAppUserRoleResponse\"&\n" +
	"\x14DeleteAppUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteAppUserResponse\"d\n" +
	"\x16CreateLocalUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"Y\n" +
	"\x17CreateLocalUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xca\x01\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1f\n" +
	"\vresource_id\x18\x06 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fdetails_json\x18\a \x01(\tR\vdetailsJson\"\x9a\x01\n" +
	"\x14ListAuditLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x06 \x01(\x05R\aperPage\"\x87\x01\n" +
	"\x15ListAuditLogsResponse\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.grpc.api.v1.AuditLogR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"\x11\n" +
	"\x0fGetStatsRequest\"\xea\x01\n" +
	"\x10GetStatsResponse\x12\x1f\n" +
	"\vhl7_pending\x18\x01 \x01(\x03R\n" +
	"hl7Pending\x12\x1f\n" +
	"\vhl7_success\x18\x02 \x01(\x03R\n" +
	"hl7Success\x12#\n" +
	"\rhl7_exhausted\x18\x03 \x01(\x03R\fhl7Exhausted\x12\x1d\n" +
	"\n" +
	"total_ecgs\x18\x04 \x01(\x03R\ttotalEcgs\x12%\n" +
	"\x0etotal_patients\x18\x05 \x01(\x03R\rtotalPatients\x12)\n" +
	"\x10quarantine_count\x18\x06 \x01(\x03R\x0fquarantineCount\"q\n" +
	"\fVolumeMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x03R\tavailable\x12\x19\n" +
	"\bmax_size\x18\x04 \x01(\tR\amaxSize\"\x1a\n" +
	"\x18GetStorageMetricsRequest\"\xa1\x01\n" +
	"\x19GetStorageMetricsResponse\x123\n" +
	"\avolumes\x18\x01 \x03(\v2\x19.grpc.api.v1.VolumeMetricR\avolumes\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.grpc.api.v1.StorageBackendInfoR\abackend\"\xbb\x01\n" +
	"\x12StorageBackendInfo\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12'\n" +
	"\x0fpending_uploads\x18\x04 \x01(\x03R\x0ependingUploads\x124\n" +
	"\x16oldest_pending_seconds\x18\x05 \x01(\x03R\x14oldestPendingSeconds\"\xe1\x01\n" +
	"\n" +
	"ErrorEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x14\n" +
	"\x05route\x18\x03 \x01(\tR\x05route\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vrequest_uri\x18\x06 \x01(\tR\n" +
	"requestUri\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x01R\n" +
	"durationMs\".\n" +
	"\x16GetRecentErrorsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"J\n" +
	"\x17GetRecentErrorsResponse\x12/\n" +
	"\x06errors\x18\x01 \x03(\v2\x17.grpc.api.v1.ErrorEntryR\x06errors\"\x18\n" +
	"\x16GetUserDefaultsRequest\"<\n" +
	"\x17GetUserDefaultsResponse\x12!\n" +
	"\fdefault_role\x18\x01 \x01(\tR\vdefaultRole\";\n" +
	"\x16SetUserDefaultsRequest\x12!\n" +
	"\fdefault_role\x18\x01 \x01(\tR\vdefaultRole\"<\n" +
	"\x17SetUserDefaultsResponse\x12!\n" +
	"\fdefault_role\x18\x01 \x01(\tR\vdefaultRole\"\x98\x02\n" +
	"\x0fQuarantineEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vreceived_at\x18\x04 \x01(\tR\n" +
	"receivedAt\x12!\n" +
	"\ferror_reason\x18\x05 \x01(\tR\verrorReason\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x16\n" +
	"\x06vendor\x18\a \x01(\tR\x06vendor\x12\x1f\n" +
	"\vrecorded_at\x18\b \x01(\tR\n" +
	"recordedAt\x12#\n" +
	"\rmetadata_json\x18\t \x01(\tR\fmetadataJson\"b\n" +
	"\x15ListQuarantineRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"\x8f\x01\n" +
	"\x16ListQuarantineResponse\x120\n" +
	"\x04data\x18\x01 \x03(\v2\x1c.grpc.api.v1.QuarantineEntryR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\")\n" +
	"\x17DeleteQuarantineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18DeleteQuarantineResponse\"g\n" +
	"\x17AssignQuarantineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1d\n" +
	"\n" +
	"create_new\x18\x03 \x01(\bR\tcreateNew\"a\n" +
	"\x18AssignQuarantineResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\x8b\f\n" +
	"\fAdminService\x12I\n" +
	"\bGetStats\x12\x1c.grpc.api.v1.GetStatsRequest\x1a\x1d.grpc.api.v1.GetStatsResponse\"\x00\x12d\n" +
	"\x11GetStorageMetrics\x12%.grpc.api.v1.GetStorageMetricsRequest\x1a&.grpc.api.v1.GetStorageMetricsResponse\"\x00\x12^\n" +
	"\x0fGetRecentErrors\x12#.grpc.api.v1.GetRecentErrorsRequest\x1a$.grpc.api.v1.GetRecentErrorsResponse\"\x00\x12X\n" +
	"\rListAuditLogs\x12!.grpc.api.v1.ListAuditLogsRequest\x1a\".grpc.api.v1.ListAuditLogsResponse\"\x00\x12^\n" +
	"\x0fGetUserDefaults\x12#.grpc.api.v1.GetUserDefaultsRequest\x1a$.grpc.api.v1.GetUserDefaultsResponse\"\x00\x12^\n" +
	"\x0fSetUserDefaults\x12#.grpc.api.v1.SetUserDefaultsRequest\x1a$.grpc.api.v1.SetUserDefaultsResponse\"\x00\x12L\n" +
	"\tListRoles\x12\x1d.grpc.api.v1.ListRolesRequest\x1a\x1e.grpc.api.v1.ListRolesResponse\"\x00\x12O\n" +
	"\n" +
	"CreateRole\x12\x1e.grpc.api.v1.CreateRoleRequest\x1a\x1f.grpc.api.v1.CreateRoleResponse\"\x00\x12O\n" +
	"\n" +
	"UpdateRole\x12\x1e.grpc.api.v1.UpdateRoleRequest\x1a\x1f.grpc.api.v1.UpdateRoleResponse\"\x00\x12O\n" +
	"\n" +
	"DeleteRole\x12\x1e.grpc.api.v1.DeleteRoleRequest\x1a\x1f.grpc.api.v1.DeleteRoleResponse\"\x00\x12U\n" +
	"\fListAppUsers\x12 .grpc.api.v1.ListAppUsersRequest\x1a!.grpc.api.v1.ListAppUsersResponse\"\x00\x12[\n" +
	"\x0eSetAppUserRole\x12\".grpc.api.v1.SetAppUserRoleRequest\x1a#.grpc.api.v1.SetAppUserRoleResponse\"\x00\x12X\n" +
	"\rDeleteAppUser\x12!.grpc.api.v1.DeleteAppUserRequest\x1a\".grpc.api.v1.DeleteAppUserResponse\"\x00\x12^\n" +
	"\x0fCreateLocalUser\x12#.grpc.api.v1.CreateLocalUserRequest\x1a$.grpc.api.v1.CreateLocalUserResponse\"\x00\x12[\n" +
	"\x0eListQuarantine\x12\".grpc.api.v1.ListQuarantineRequest\x1a#.grpc.api.v1.ListQuarantineResponse\"\x00\x12a\n" +
	"\x10DeleteQuarantine\x12$.grpc.api.v1.DeleteQuarantineRequest\x1a%.grpc.api.v1.DeleteQuarantineResponse\"\x00\x12a\n" +
	"\x10AssignQuarantine\x12$.grpc.api.v1.AssignQuarantineRequest\x1a%.grpc.api.v1.AssignQuarantineResponse\"\x00B\x9f\x01\n" +
	"\x0fcom.grpc.api.v1B\n" +
	"AdminProtoP\x01Z2github.com/LIRYC-IHU/ecg-hub/internal/api/v1;apiv1\xa2\x02\x03GAX\xaa\x02\vGrpc.Api.V1\xca\x02\vGrpc\\Api\\V1\xe2\x02\x17Grpc\\Api\\V1\\GPBMetadata\xea\x02\rGrpc::Api::V1b\x06proto3"

var (
	file_v1_admin_proto_rawDescOnce sync.Once
	file_v1_admin_proto_rawDescData []byte
)

func file_v1_admin_proto_rawDescGZIP() []byte {
	file_v1_admin_proto_rawDescOnce.Do(func() {
		file_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)))
	})
	return file_v1_admin_proto_rawDescData
}

var file_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_v1_admin_proto_goTypes = []any{
	(*Role)(nil),                      // 0: grpc.api.v1.Role
	(*ListRolesRequest)(nil),          // 1: grpc.api.v1.ListRolesRequest
	(*ListRolesResponse)(nil),         // 2: grpc.api.v1.ListRolesResponse
	(*CreateRoleRequest)(nil),         // 3: grpc.api.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),        // 4: grpc.api.v1.CreateRoleResponse
	(*UpdateRoleRequest)(nil),         // 5: grpc.api.v1.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),        // 6: grpc.api.v1.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),         // 7: grpc.api.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),        // 8: grpc.api.v1.DeleteRoleResponse
	(*AppUser)(nil),                   // 9: grpc.api.v1.AppUser
	(*ListAppUsersRequest)(nil),       // 10: grpc.api.v1.ListAppUsersRequest
	(*ListAppUsersResponse)(nil),      // 11: grpc.api.v1.ListAppUsersResponse
	(*SetAppUserRoleRequest)(nil),     // 12: grpc.api.v1.SetAppUserRoleRequest
	(*SetAppUserRoleResponse)(nil),    // 13: grpc.api.v1.SetAppUserRoleResponse
	(*DeleteAppUserRequest)(nil),      // 14: grpc.api.v1.DeleteAppUserRequest
	(*DeleteAppUserResponse)(nil),     // 15: grpc.api.v1.DeleteAppUserResponse
	(*CreateLocalUserRequest)(nil),    // 16: grpc.api.v1.CreateLocalUserRequest
	(*CreateLocalUserResponse)(nil),   // 17: grpc.api.v1.CreateLocalUserResponse
	(*AuditLog)(nil),                  // 18: grpc.api.v1.AuditLog
	(*ListAuditLogsRequest)(nil),      // 19: grpc.api.v1.ListAuditLogsRequest
	(*ListAuditLogsResponse)(nil),     // 20: grpc.api.v1.ListAuditLogsResponse
	(*GetStatsRequest)(nil),           // 21: grpc.api.v1.GetStatsRequest
	(*GetStatsResponse)(nil),          // 22: grpc.api.v1.GetStatsResponse
	(*VolumeMetric)(nil),              // 23: grpc.api.v1.VolumeMetric
	(*GetStorageMetricsRequest)(nil),  // 24: grpc.api.v1.GetStorageMetricsRequest
	(*GetStorageMetricsResponse)(nil), // 25: grpc.api.v1.GetStorageMetricsResponse
	(*StorageBackendInfo)(nil),        // 26: grpc.api.v1.StorageBackendInfo
	(*ErrorEntry)(nil),                // 27: grpc.api.v1.ErrorEntry
	(*GetRecentErrorsRequest)(nil),    // 28: grpc.api.v1.GetRecentErrorsRequest
	(*GetRecentErrorsResponse)(nil),   // 29: grpc.api.v1.GetRecentErrorsResponse
	(*GetUserDefaultsRequest)(nil),    // 30: grpc.api.v1.GetUserDefaultsRequest
	(*GetUserDefaultsResponse)(nil),   // 31: grpc.api.v1.GetUserDefaultsResponse
	(*SetUserDefaultsRequest)(nil),    // 32: grpc.api.v1.SetUserDefaultsRequest
	(*SetUserDefaultsResponse)(nil),   // 33: grpc.api.v1.SetUserDefaultsResponse
	(*QuarantineEntry)(nil),           // 34: grpc.api.v1.QuarantineEntry
	(*ListQuarantineRequest)(nil),     // 35: grpc.api.v1.ListQuarantineRequest
	(*ListQuarantineResponse)(nil),    // 36: grpc.api.v1.ListQuarantineResponse
	(*DeleteQuarantineRequest)(nil),   // 37: grpc.api.v1.DeleteQuarantineRequest
	(*DeleteQuarantineResponse)(nil),  // 38: grpc.api.v1.DeleteQuarantineResponse
	(*AssignQuarantineRequest)(nil),   // 39: grpc.api.v1.AssignQuarantineRequest
	(*AssignQuarantineResponse)(nil),  // 40: grpc.api.v1.AssignQuarantineResponse
}
var file_v1_admin_proto_depIdxs = []int32{
	0,  // 0: grpc.api.v1.ListRolesResponse.roles:type_name -> grpc.api.v1.Role
	0,  // 1: grpc.api.v1.CreateRoleResponse.role:type_name -> grpc.api.v1.Role
	9,  // 2: grpc.api.v1.ListAppUsersResponse.users:type_name -> grpc.api.v1.AppUser
	18, // 3: grpc.api.v1.ListAuditLogsResponse.data:type_name -> grpc.api.v1.AuditLog
	23, // 4: grpc.api.v1.GetStorageMetricsResponse.volumes:type_name -> grpc.api.v1.VolumeMetric
	26, // 5: grpc.api.v1.GetStorageMetricsResponse.backend:type_name -> grpc.api.v1.StorageBackendInfo
	27, // 6: grpc.api.v1.GetRecentErrorsResponse.errors:type_name -> grpc.api.v1.ErrorEntry
	34, // 7: grpc.api.v1.ListQuarantineResponse.data:type_name -> grpc.api.v1.QuarantineEntry
	21, // 8: grpc.api.v1.AdminService.GetStats:input_type -> grpc.api.v1.GetStatsRequest
	24, // 9: grpc.api.v1.AdminService.GetStorageMetrics:input_type -> grpc.api.v1.GetStorageMetricsRequest
	28, // 10: grpc.api.v1.AdminService.GetRecentErrors:input_type -> grpc.api.v1.GetRecentErrorsRequest
	19, // 11: grpc.api.v1.AdminService.ListAuditLogs:input_type -> grpc.api.v1.ListAuditLogsRequest
	30, // 12: grpc.api.v1.AdminService.GetUserDefaults:input_type -> grpc.api.v1.GetUserDefaultsRequest
	32, // 13: grpc.api.v1.AdminService.SetUserDefaults:input_type -> grpc.api.v1.SetUserDefaultsRequest
	1,  // 14: grpc.api.v1.AdminService.ListRoles:input_type -> grpc.api.v1.ListRolesRequest
	3,  // 15: grpc.api.v1.AdminService.CreateRole:input_type -> grpc.api.v1.CreateRoleRequest
	5,  // 16: grpc.api.v1.AdminService.UpdateRole:input_type -> grpc.api.v1.UpdateRoleRequest
	7,  // 17: grpc.api.v1.AdminService.DeleteRole:input_type -> grpc.api.v1.DeleteRoleRequest
	10, // 18: grpc.api.v1.AdminService.ListAppUsers:input_type -> grpc.api.v1.ListAppUsersRequest
	12, // 19: grpc.api.v1.AdminService.SetAppUserRole:input_type -> grpc.api.v1.SetAppUserRoleRequest
	14, // 20: grpc.api.v1.AdminService.DeleteAppUser:input_type -> grpc.api.v1.DeleteAppUserRequest
	16, // 21: grpc.api.v1.AdminService.CreateLocalUser:input_type -> grpc.api.v1.CreateLocalUserRequest
	35, // 22: grpc.api.v1.AdminService.ListQuarantine:input_type -> grpc.api.v1.ListQuarantineRequest
	37, // 23: grpc.api.v1.AdminService.DeleteQuarantine:input_type -> grpc.api.v1.DeleteQuarantineRequest
	39, // 24: grpc.api.v1.AdminService.AssignQuarantine:input_type -> grpc.api.v1.AssignQuarantineRequest
	22, // 25: grpc.api.v1.AdminService.GetStats:output_type -> grpc.api.v1.GetStatsResponse
	25, // 26: grpc.api.v1.AdminService.GetStorageMetrics:output_type -> grpc.api.v1.GetStorageMetricsResponse
	29, // 27: grpc.api.v1.AdminService.GetRecentErrors:output_type -> grpc.api.v1.GetRecentErrorsResponse
	20, // 28: grpc.api.v1.AdminService.ListAuditLogs:output_type -> grpc.api.v1.ListAuditLogsResponse
	31, // 29: grpc.api.v1.AdminService.GetUserDefaults:output_type -> grpc.api.v1.GetUserDefaultsResponse
	33, // 30: grpc.api.v1.AdminService.SetUserDefaults:output_type -> grpc.api.v1.SetUserDefaultsResponse
	2,  // 31: grpc.api.v1.AdminService.ListRoles:output_type -> grpc.api.v1.ListRolesResponse
	4,  // 32: grpc.api.v1.AdminService.CreateRole:output_type -> grpc.api.v1.CreateRoleResponse
	6,  // 33: grpc.api.v1.AdminService.UpdateRole:output_type -> grpc.api.v1.UpdateRoleResponse
	8,  // 34: grpc.api.v1.AdminService.DeleteRole:output_type -> grpc.api.v1.DeleteRoleResponse
	11, // 35: grpc.api.v1.AdminService.ListAppUsers:output_type -> grpc.api.v1.ListAppUsersResponse
	13, // 36: grpc.api.v1.AdminService.SetAppUserRole:output_type -> grpc.api.v1.SetAppUserRoleResponse
	15, // 37: grpc.api.v1.AdminService.DeleteAppUser:output_type -> grpc.api.v1.DeleteAppUserResponse
	17, // 38: grpc.api.v1.AdminService.CreateLocalUser:output_type -> grpc.api.v1.CreateLocalUserResponse
	36, // 39: grpc.api.v1.AdminService.ListQuarantine:output_type -> grpc.api.v1.ListQuarantineResponse
	38, // 40: grpc.api.v1.AdminService.DeleteQuarantine:output_type -> grpc.api.v1.DeleteQuarantineResponse
	40, // 41: grpc.api.v1.AdminService.AssignQuarantine:output_type -> grpc.api.v1.AssignQuarantineResponse
	25, // [25:42] is the sub-list for method output_type
	8,  // [8:25] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_admin_proto_init() }
func file_v1_admin_proto_init() {
	if File_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_proto_rawDesc), len(file_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_proto_goTypes,
		DependencyIndexes: file_v1_admin_proto_depIdxs,
		MessageInfos:      file_v1_admin_proto_msgTypes,
	}.Build()
	File_v1_admin_proto = out.File
	file_v1_admin_proto_goTypes = nil
	file_v1_admin_proto_depIdxs = nil
}
