// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/authadmin.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderType  string                 `protobuf:"bytes,2,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"` // "oidc" | "ldap"
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // decrypted config with secrets masked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthProvider) Reset() {
	*x = AuthProvider{}
	mi := &file_v1_authadmin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProvider) ProtoMessage() {}

func (x *AuthProvider) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProvider.ProtoReflect.Descriptor instead.
func (*AuthProvider) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{0}
}

func (x *AuthProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthProvider) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

func (x *AuthProvider) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *AuthProvider) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type ListAuthProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthProvidersRequest) Reset() {
	*x = ListAuthProvidersRequest{}
	mi := &file_v1_authadmin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthProvidersRequest) ProtoMessage() {}

func (x *ListAuthProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListAuthProvidersRequest) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{1}
}

type ListAuthProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*AuthProvider        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthProvidersResponse) Reset() {
	*x = ListAuthProvidersResponse{}
	mi := &file_v1_authadmin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthProvidersResponse) ProtoMessage() {}

func (x *ListAuthProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListAuthProvidersResponse) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuthProvidersResponse) GetProviders() []*AuthProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type SaveOIDCConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // SaveOIDCRequest JSON (issuer_url, client_id, …, active)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveOIDCConfigRequest) Reset() {
	*x = SaveOIDCConfigRequest{}
	mi := &file_v1_authadmin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveOIDCConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOIDCConfigRequest) ProtoMessage() {}

func (x *SaveOIDCConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOIDCConfigRequest.ProtoReflect.Descriptor instead.
func (*SaveOIDCConfigRequest) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{3}
}

func (x *SaveOIDCConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type SaveLDAPConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // SaveLDAPRequest JSON (host, port, …, active)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLDAPConfigRequest) Reset() {
	*x = SaveLDAPConfigRequest{}
	mi := &file_v1_authadmin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLDAPConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLDAPConfigRequest) ProtoMessage() {}

func (x *SaveLDAPConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLDAPConfigRequest.ProtoReflect.Descriptor instead.
func (*SaveLDAPConfigRequest) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{4}
}

func (x *SaveLDAPConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// Shared reply for provider saves/deletes that require a restart to apply.
type SaveAuthConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RestartRequired bool                   `protobuf:"varint,2,opt,name=restart_required,json=restartRequired,proto3" json:"restart_required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveAuthConfigResponse) Reset() {
	*x = SaveAuthConfigResponse{}
	mi := &file_v1_authadmin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAuthConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAuthConfigResponse) ProtoMessage() {}

func (x *SaveAuthConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAuthConfigResponse.ProtoReflect.Descriptor instead.
func (*SaveAuthConfigResponse) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{5}
}

func (x *SaveAuthConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveAuthConfigResponse) GetRestartRequired() bool {
	if x != nil {
		return x.RestartRequired
	}
	return false
}

type DeleteAuthProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAuthProviderRequest) Reset() {
	*x = DeleteAuthProviderRequest{}
	mi := &file_v1_authadmin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuthProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthProviderRequest) ProtoMessage() {}

func (x *DeleteAuthProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteAuthProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAuthProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAuthProviderResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RestartRequired bool                   `protobuf:"varint,2,opt,name=restart_required,json=restartRequired,proto3" json:"restart_required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteAuthProviderResponse) Reset() {
	*x = DeleteAuthProviderResponse{}
	mi := &file_v1_authadmin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAuthProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAuthProviderResponse) ProtoMessage() {}

func (x *DeleteAuthProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAuthProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteAuthProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAuthProviderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteAuthProviderResponse) GetRestartRequired() bool {
	if x != nil {
		return x.RestartRequired
	}
	return false
}

type TestOIDCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestOIDCRequest) Reset() {
	*x = TestOIDCRequest{}
	mi := &file_v1_authadmin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestOIDCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOIDCRequest) ProtoMessage() {}

func (x *TestOIDCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOIDCRequest.ProtoReflect.Descriptor instead.
func (*TestOIDCRequest) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{8}
}

func (x *TestOIDCRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type TestLDAPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestLDAPRequest) Reset() {
	*x = TestLDAPRequest{}
	mi := &file_v1_authadmin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestLDAPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestLDAPRequest) ProtoMessage() {}

func (x *TestLDAPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestLDAPRequest.ProtoReflect.Descriptor instead.
func (*TestLDAPRequest) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{9}
}

func (x *TestLDAPRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// Shared reply for the connectivity tests. host/latency are only populated by
// the LDAP TCP dial; OIDC leaves them empty.
type TestAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Latency       string                 `protobuf:"bytes,4,opt,name=latency,proto3" json:"latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAuthResponse) Reset() {
	*x = TestAuthResponse{}
	mi := &file_v1_authadmin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAuthResponse) ProtoMessage() {}

func (x *TestAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_authadmin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAuthResponse.ProtoReflect.Descriptor instead.
func (*TestAuthResponse) Descriptor() ([]byte, []int) {
	return file_v1_authadmin_proto_rawDescGZIP(), []int{10}
}

func (x *TestAuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestAuthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TestAuthResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TestAuthResponse) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

var File_v1_authadmin_proto protoreflect.FileDescriptor

const file_v1_authadmin_proto_rawDesc = "" +
	"\n" +
	"\x12v1/authadmin.proto\x12\vgrpc.api.v1\"|\n" +
	"\fAuthProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rprovider_type\x18\x02 \x01(\tR\fproviderType\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\tR\n" +
	"configJson\"\x1a\n" +
	"\x18ListAuthProvidersRequest\"T\n" +
	"\x19ListAuthProvidersResponse\x127\n" +
	"\tproviders\x18\x01 \x03(\v2\x19.grpc.api.v1.AuthProviderR\tproviders\"8\n" +
	"\x15SaveOIDCConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"8\n" +
	"\x15SaveLDAPConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"]\n" +
	"\x16SaveAuthConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12)\n" +
	"\x10restart_required\x18\x02 \x01(\bR\x0frestartRequired\"+\n" +
	"\x19DeleteAuthProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"a\n" +
	"\x1aDeleteAuthProviderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12)\n" +
	"\x10restart_required\x18\x02 \x01(\bR\x0frestartRequired\"2\n" +
	"\x0fTestOIDCRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"2\n" +
	"\x0fTestLDAPRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"p\n" +
	"\x10TestAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x18\n" +
	"\alatency\x18\x04 \x01(\tR\alatency2\x9d\x04\n" +
	"\x10AuthAdminService\x12`\n" +
	"\rListProviders\x12%.grpc.api.v1.ListAuthProvidersRequest\x1a&.grpc.api.v1.ListAuthProvidersResponse\"\x00\x12U\n" +
	"\bSaveOIDC\x12\".grpc.api.v1.SaveOIDCConfigRequest\x1a#.grpc.api.v1.SaveAuthConfigResponse\"\x00\x12U\n" +
	"\bSaveLDAP\x12\".grpc.api.v1.SaveLDAPConfigRequest\x1a#.grpc.api.v1.SaveAuthConfigResponse\"\x00\x12c\n" +
	"\x0eDeleteProvider\x12&.grpc.api.v1.DeleteAuthProviderRequest\x1a'.grpc.api.v1.DeleteAuthProviderResponse\"\x00\x12I\n" +
	"\bTestOIDC\x12\x1c.grpc.api.v1.TestOIDCRequest\x1a\x1d.grpc.api.v1.TestAuthResponse\"\x00\x12I\n" +
	"\bTestLDAP\x12\x1c.grpc.api.v1.TestLDAPRequest\x1a\x1d.grpc.api.v1.TestAuthResponse\"\x00B\xa3\x01\n" +
	"\x0fcom.grpc.api.v1B\x0eAuthadminProtoP\x01Z2github.com/LIRYC-IHU/ecg-hub/internal/api/v1;apiv1\xa2\x02\x03GAX\xaa\x02\vGrpc.Api.V1\xca\x02\vGrpc\\Api\\V1\xe2\x02\x17Grpc\\Api\\V1\\GPBMetadata\xea\x02\rGrpc::Api::V1b\x06proto3"

var (
	file_v1_authadmin_proto_rawDescOnce sync.Once
	file_v1_authadmin_proto_rawDescData []byte
)

func file_v1_authadmin_proto_rawDescGZIP() []byte {
	file_v1_authadmin_proto_rawDescOnce.Do(func() {
		file_v1_authadmin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_authadmin_proto_rawDesc), len(file_v1_authadmin_proto_rawDesc)))
	})
	return file_v1_authadmin_proto_rawDescData
}

var file_v1_authadmin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_authadmin_proto_goTypes = []any{
	(*AuthProvider)(nil),               // 0: grpc.api.v1.AuthProvider
	(*ListAuthProvidersRequest)(nil),   // 1: grpc.api.v1.ListAuthProvidersRequest
	(*ListAuthProvidersResponse)(nil),  // 2: grpc.api.v1.ListAuthProvidersResponse
	(*SaveOIDCConfigRequest)(nil),      // 3: grpc.api.v1.SaveOIDCConfigRequest
	(*SaveLDAPConfigRequest)(nil),      // 4: grpc.api.v1.SaveLDAPConfigRequest
	(*SaveAuthConfigResponse)(nil),     // 5: grpc.api.v1.SaveAuthConfigResponse
	(*DeleteAuthProviderRequest)(nil),  // 6: grpc.api.v1.DeleteAuthProviderRequest
	(*DeleteAuthProviderResponse)(nil), // 7: grpc.api.v1.DeleteAuthProviderResponse
	(*TestOIDCRequest)(nil),            // 8: grpc.api.v1.TestOIDCRequest
	(*TestLDAPRequest)(nil),            // 9: grpc.api.v1.TestLDAPRequest
	(*TestAuthResponse)(nil),           // 10: grpc.api.v1.TestAuthResponse
}
var file_v1_authadmin_proto_depIdxs = []int32{
	0,  // 0: grpc.api.v1.ListAuthProvidersResponse.providers:type_name -> grpc.api.v1.AuthProvider
	1,  // 1: grpc.api.v1.AuthAdminService.ListProviders:input_type -> grpc.api.v1.ListAuthProvidersRequest
	3,  // 2: grpc.api.v1.AuthAdminService.SaveOIDC:input_type -> grpc.api.v1.SaveOIDCConfigRequest
	4,  // 3: grpc.api.v1.AuthAdminService.SaveLDAP:input_type -> grpc.api.v1.SaveLDAPConfigRequest
	6,  // 4: grpc.api.v1.AuthAdminService.DeleteProvider:input_type -> grpc.api.v1.DeleteAuthProviderRequest
	8,  // 5: grpc.api.v1.AuthAdminService.TestOIDC:input_type -> grpc.api.v1.TestOIDCRequest
	9,  // 6: grpc.api.v1.AuthAdminService.TestLDAP:input_type -> grpc.api.v1.TestLDAPRequest
	2,  // 7: grpc.api.v1.AuthAdminService.ListProviders:output_type -> grpc.api.v1.ListAuthProvidersResponse
	5,  // 8: grpc.api.v1.AuthAdminService.SaveOIDC:output_type -> grpc.api.v1.SaveAuthConfigResponse
	5,  // 9: grpc.api.v1.AuthAdminService.SaveLDAP:output_type -> grpc.api.v1.SaveAuthConfigResponse
	7,  // 10: grpc.api.v1.AuthAdminService.DeleteProvider:output_type -> grpc.api.v1.DeleteAuthProviderResponse
	10, // 11: grpc.api.v1.AuthAdminService.TestOIDC:output_type -> grpc.api.v1.TestAuthResponse
	10, // 12: grpc.api.v1.AuthAdminService.TestLDAP:output_type -> grpc.api.v1.TestAuthResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_v1_authadmin_proto_init() }
func file_v1_authadmin_proto_init() {
	if File_v1_authadmin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_authadmin_proto_rawDesc), len(file_v1_authadmin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_authadmin_proto_goTypes,
		DependencyIndexes: file_v1_authadmin_proto_depIdxs,
		MessageInfos:      file_v1_authadmin_proto_msgTypes,
	}.Build()
	File_v1_authadmin_proto = out.File
	file_v1_authadmin_proto_goTypes = nil
	file_v1_authadmin_proto_depIdxs = nil
}
