// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/ecg.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ecg mirrors dto.EcgDTO (the API representation, not the DB model). file_path is
// intentionally excluded (internal). Timestamps are ISO 8601 UTC strings, empty
// when null. extra_json is the JSONB metadata serialized as a JSON object string
// (a plain google.protobuf.Struct would need fiddly Go/TS conversion for a
// free-form passthrough blob).
type Ecg struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId        string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Vendor           string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,4,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	RecordedAt       string                 `protobuf:"bytes,5,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"` // ISO 8601 UTC; empty for legacy records
	IngestedAt       string                 `protobuf:"bytes,6,opt,name=ingested_at,json=ingestedAt,proto3" json:"ingested_at,omitempty"` // ISO 8601 UTC
	Hl7Status        string                 `protobuf:"bytes,7,opt,name=hl7_status,json=hl7Status,proto3" json:"hl7_status,omitempty"`    // "pending"|"success"|"hl7_exhausted"|"hl7_rejected"
	Viewed           bool                   `protobuf:"varint,8,opt,name=viewed,proto3" json:"viewed,omitempty"`
	ExtraJson        string                 `protobuf:"bytes,9,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"` // editable vendor metadata (JSON object)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ecg) Reset() {
	*x = Ecg{}
	mi := &file_v1_ecg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ecg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ecg) ProtoMessage() {}

func (x *Ecg) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ecg.ProtoReflect.Descriptor instead.
func (*Ecg) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{0}
}

func (x *Ecg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ecg) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Ecg) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Ecg) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

func (x *Ecg) GetRecordedAt() string {
	if x != nil {
		return x.RecordedAt
	}
	return ""
}

func (x *Ecg) GetIngestedAt() string {
	if x != nil {
		return x.IngestedAt
	}
	return ""
}

func (x *Ecg) GetHl7Status() string {
	if x != nil {
		return x.Hl7Status
	}
	return ""
}

func (x *Ecg) GetViewed() bool {
	if x != nil {
		return x.Viewed
	}
	return false
}

func (x *Ecg) GetExtraJson() string {
	if x != nil {
		return x.ExtraJson
	}
	return ""
}

// EcgWithPatient is one row of the cross-patient timeline (GET /ecgs): an Ecg
// plus the joined patient demographics. Mirrors dto.EcgWithPatientDTO (which
// flattens EcgDTO + patient fields); the frontend flattens the nested ecg.
type EcgWithPatient struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ecg              *Ecg                   `protobuf:"bytes,1,opt,name=ecg,proto3" json:"ecg,omitempty"`
	PatientFirstName string                 `protobuf:"bytes,2,opt,name=patient_first_name,json=patientFirstName,proto3" json:"patient_first_name,omitempty"`
	PatientLastName  string                 `protobuf:"bytes,3,opt,name=patient_last_name,json=patientLastName,proto3" json:"patient_last_name,omitempty"`
	PatientGender    string                 `protobuf:"bytes,4,opt,name=patient_gender,json=patientGender,proto3" json:"patient_gender,omitempty"`
	PatientDob       string                 `protobuf:"bytes,5,opt,name=patient_dob,json=patientDob,proto3" json:"patient_dob,omitempty"` // ISO 8601 UTC; empty when null
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EcgWithPatient) Reset() {
	*x = EcgWithPatient{}
	mi := &file_v1_ecg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcgWithPatient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcgWithPatient) ProtoMessage() {}

func (x *EcgWithPatient) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcgWithPatient.ProtoReflect.Descriptor instead.
func (*EcgWithPatient) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{1}
}

func (x *EcgWithPatient) GetEcg() *Ecg {
	if x != nil {
		return x.Ecg
	}
	return nil
}

func (x *EcgWithPatient) GetPatientFirstName() string {
	if x != nil {
		return x.PatientFirstName
	}
	return ""
}

func (x *EcgWithPatient) GetPatientLastName() string {
	if x != nil {
		return x.PatientLastName
	}
	return ""
}

func (x *EcgWithPatient) GetPatientGender() string {
	if x != nil {
		return x.PatientGender
	}
	return ""
}

func (x *EcgWithPatient) GetPatientDob() string {
	if x != nil {
		return x.PatientDob
	}
	return ""
}

type GetFiltersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFiltersRequest) Reset() {
	*x = GetFiltersRequest{}
	mi := &file_v1_ecg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFiltersRequest) ProtoMessage() {}

func (x *GetFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFiltersRequest.ProtoReflect.Descriptor instead.
func (*GetFiltersRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{2}
}

type GetFiltersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendors       []string               `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
	DeviceModels  []string               `protobuf:"bytes,2,rep,name=device_models,json=deviceModels,proto3" json:"device_models,omitempty"`
	FileFormats   []string               `protobuf:"bytes,3,rep,name=file_formats,json=fileFormats,proto3" json:"file_formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFiltersResponse) Reset() {
	*x = GetFiltersResponse{}
	mi := &file_v1_ecg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFiltersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFiltersResponse) ProtoMessage() {}

func (x *GetFiltersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFiltersResponse.ProtoReflect.Descriptor instead.
func (*GetFiltersResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{3}
}

func (x *GetFiltersResponse) GetVendors() []string {
	if x != nil {
		return x.Vendors
	}
	return nil
}

func (x *GetFiltersResponse) GetDeviceModels() []string {
	if x != nil {
		return x.DeviceModels
	}
	return nil
}

func (x *GetFiltersResponse) GetFileFormats() []string {
	if x != nil {
		return x.FileFormats
	}
	return nil
}

// ListAllRequest is the cross-patient ECG timeline filter set (GET /ecgs).
type ListAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"` // search patient name, patient_id, filename
	Hl7Status     string                 `protobuf:"bytes,2,opt,name=hl7_status,json=hl7Status,proto3" json:"hl7_status,omitempty"`
	Vendor        string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	DeviceModel   string                 `protobuf:"bytes,4,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	FileFormat    string                 `protobuf:"bytes,5,opt,name=file_format,json=fileFormat,proto3" json:"file_format,omitempty"`
	From          string                 `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"` // YYYY-MM-DD (inclusive)
	To            string                 `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`     // YYYY-MM-DD (inclusive)
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,9,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllRequest) Reset() {
	*x = ListAllRequest{}
	mi := &file_v1_ecg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllRequest) ProtoMessage() {}

func (x *ListAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllRequest.ProtoReflect.Descriptor instead.
func (*ListAllRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{4}
}

func (x *ListAllRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListAllRequest) GetHl7Status() string {
	if x != nil {
		return x.Hl7Status
	}
	return ""
}

func (x *ListAllRequest) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ListAllRequest) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *ListAllRequest) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

func (x *ListAllRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ListAllRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ListAllRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAllRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*EcgWithPatient      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllResponse) Reset() {
	*x = ListAllResponse{}
	mi := &file_v1_ecg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllResponse) ProtoMessage() {}

func (x *ListAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllResponse.ProtoReflect.Descriptor instead.
func (*ListAllResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{5}
}

func (x *ListAllResponse) GetData() []*EcgWithPatient {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListAllResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAllResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAllResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// EcgField is one editable metadata field definition (mirrors ecgmeta.FieldDef),
// driving the frontend's dynamic metadata form.
type EcgField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`       // "text"|"number"|"datetime"|"select"
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"` // non-empty only for type "select"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcgField) Reset() {
	*x = EcgField{}
	mi := &file_v1_ecg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcgField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcgField) ProtoMessage() {}

func (x *EcgField) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcgField.ProtoReflect.Descriptor instead.
func (*EcgField) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{6}
}

func (x *EcgField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EcgField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EcgField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EcgField) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // ECG id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_v1_ecg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*EcgField            `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	ValuesJson    string                 `protobuf:"bytes,2,opt,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"` // current metadata values as a JSON object string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_v1_ecg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{8}
}

func (x *GetMetadataResponse) GetFields() []*EcgField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *GetMetadataResponse) GetValuesJson() string {
	if x != nil {
		return x.ValuesJson
	}
	return ""
}

// UpdateMetadataRequest patches an ECG's editable metadata. values_json is a JSON
// object; only keys in ecgmeta.EditableFields are applied (unknown keys ignored).
type UpdateMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ValuesJson    string                 `protobuf:"bytes,2,opt,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataRequest) Reset() {
	*x = UpdateMetadataRequest{}
	mi := &file_v1_ecg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataRequest) ProtoMessage() {}

func (x *UpdateMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMetadataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMetadataRequest) GetValuesJson() string {
	if x != nil {
		return x.ValuesJson
	}
	return ""
}

type UpdateMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValuesJson    string                 `protobuf:"bytes,1,opt,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"` // metadata values after the update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataResponse) Reset() {
	*x = UpdateMetadataResponse{}
	mi := &file_v1_ecg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataResponse) ProtoMessage() {}

func (x *UpdateMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ecg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return file_v1_ecg_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMetadataResponse) GetValuesJson() string {
	if x != nil {
		return x.ValuesJson
	}
	return ""
}

var File_v1_ecg_proto protoreflect.FileDescriptor

const file_v1_ecg_proto_rawDesc = "" +
	"\n" +
	"\fv1/ecg.proto\x12\vgrpc.api.v1\"\x91\x02\n" +
	"\x03Ecg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12+\n" +
	"\x11original_filename\x18\x04 \x01(\tR\x10originalFilename\x12\x1f\n" +
	"\vrecorded_at\x18\x05 \x01(\tR\n" +
	"recordedAt\x12\x1f\n" +
	"\vingested_at\x18\x06 \x01(\tR\n" +
	"ingestedAt\x12\x1d\n" +
	"\n" +
	"hl7_status\x18\a \x01(\tR\thl7Status\x12\x16\n" +
	"\x06viewed\x18\b \x01(\bR\x06viewed\x12\x1d\n" +
	"\n" +
	"extra_json\x18\t \x01(\tR\textraJson\"\xd6\x01\n" +
	"\x0eEcgWithPatient\x12\"\n" +
	"\x03ecg\x18\x01 \x01(\v2\x10.grpc.api.v1.EcgR\x03ecg\x12,\n" +
	"\x12patient_first_name\x18\x02 \x01(\tR\x10patientFirstName\x12*\n" +
	"\x11patient_last_name\x18\x03 \x01(\tR\x0fpatientLastName\x12%\n" +
	"\x0epatient_gender\x18\x04 \x01(\tR\rpatientGender\x12\x1f\n" +
	"\vpatient_dob\x18\x05 \x01(\tR\n" +
	"patientDob\"\x13\n" +
	"\x11GetFiltersRequest\"v\n" +
	"\x12GetFiltersResponse\x12\x18\n" +
	"\avendors\x18\x01 \x03(\tR\avendors\x12#\n" +
	"\rdevice_models\x18\x02 \x03(\tR\fdeviceModels\x12!\n" +
	"\ffile_formats\x18\x03 \x03(\tR\vfileFormats\"\xec\x01\n" +
	"\x0eListAllRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x1d\n" +
	"\n" +
	"hl7_status\x18\x02 \x01(\tR\thl7Status\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12!\n" +
	"\fdevice_model\x18\x04 \x01(\tR\vdeviceModel\x12\x1f\n" +
	"\vfile_format\x18\x05 \x01(\tR\n" +
	"fileFormat\x12\x12\n" +
	"\x04from\x18\x06 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\a \x01(\tR\x02to\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\t \x01(\x05R\aperPage\"\x87\x01\n" +
	"\x0fListAllResponse\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.grpc.api.v1.EcgWithPatientR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"`\n" +
	"\bEcgField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"$\n" +
	"\x12GetMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"e\n" +
	"\x13GetMetadataResponse\x12-\n" +
	"\x06fields\x18\x01 \x03(\v2\x15.grpc.api.v1.EcgFieldR\x06fields\x12\x1f\n" +
	"\vvalues_json\x18\x02 \x01(\tR\n" +
	"valuesJson\"H\n" +
	"\x15UpdateMetadataRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vvalues_json\x18\x02 \x01(\tR\n" +
	"valuesJson\"9\n" +
	"\x16UpdateMetadataResponse\x12\x1f\n" +
	"\vvalues_json\x18\x01 \x01(\tR\n" +
	"valuesJson2\xd6\x02\n" +
	"\n" +
	"ECGService\x12O\n" +
	"\n" +
	"GetFilters\x12\x1e.grpc.api.v1.GetFiltersRequest\x1a\x1f.grpc.api.v1.GetFiltersResponse\"\x00\x12F\n" +
	"\aListAll\x12\x1b.grpc.api.v1.ListAllRequest\x1a\x1c.grpc.api.v1.ListAllResponse\"\x00\x12R\n" +
	"\vGetMetadata\x12\x1f.grpc.api.v1.GetMetadataRequest\x1a .grpc.api.v1.GetMetadataResponse\"\x00\x12[\n" +
	"\x0eUpdateMetadata\x12\".grpc.api.v1.UpdateMetadataRequest\x1a#.grpc.api.v1.UpdateMetadataResponse\"\x00B\x9d\x01\n" +
	"\x0fcom.grpc.api.v1B\bEcgProtoP\x01Z2github.com/LIRYC-IHU/ecg-hub/internal/api/v1;apiv1\xa2\x02\x03GAX\xaa\x02\vGrpc.Api.V1\xca\x02\vGrpc\\Api\\V1\xe2\x02\x17Grpc\\Api\\V1\\GPBMetadata\xea\x02\rGrpc::Api::V1b\x06proto3"

var (
	file_v1_ecg_proto_rawDescOnce sync.Once
	file_v1_ecg_proto_rawDescData []byte
)

func file_v1_ecg_proto_rawDescGZIP() []byte {
	file_v1_ecg_proto_rawDescOnce.Do(func() {
		file_v1_ecg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_ecg_proto_rawDesc), len(file_v1_ecg_proto_rawDesc)))
	})
	return file_v1_ecg_proto_rawDescData
}

var file_v1_ecg_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_ecg_proto_goTypes = []any{
	(*Ecg)(nil),                    // 0: grpc.api.v1.Ecg
	(*EcgWithPatient)(nil),         // 1: grpc.api.v1.EcgWithPatient
	(*GetFiltersRequest)(nil),      // 2: grpc.api.v1.GetFiltersRequest
	(*GetFiltersResponse)(nil),     // 3: grpc.api.v1.GetFiltersResponse
	(*ListAllRequest)(nil),         // 4: grpc.api.v1.ListAllRequest
	(*ListAllResponse)(nil),        // 5: grpc.api.v1.ListAllResponse
	(*EcgField)(nil),               // 6: grpc.api.v1.EcgField
	(*GetMetadataRequest)(nil),     // 7: grpc.api.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil),    // 8: grpc.api.v1.GetMetadataResponse
	(*UpdateMetadataRequest)(nil),  // 9: grpc.api.v1.UpdateMetadataRequest
	(*UpdateMetadataResponse)(nil), // 10: grpc.api.v1.UpdateMetadataResponse
}
var file_v1_ecg_proto_depIdxs = []int32{
	0,  // 0: grpc.api.v1.EcgWithPatient.ecg:type_name -> grpc.api.v1.Ecg
	1,  // 1: grpc.api.v1.ListAllResponse.data:type_name -> grpc.api.v1.EcgWithPatient
	6,  // 2: grpc.api.v1.GetMetadataResponse.fields:type_name -> grpc.api.v1.EcgField
	2,  // 3: grpc.api.v1.ECGService.GetFilters:input_type -> grpc.api.v1.GetFiltersRequest
	4,  // 4: grpc.api.v1.ECGService.ListAll:input_type -> grpc.api.v1.ListAllRequest
	7,  // 5: grpc.api.v1.ECGService.GetMetadata:input_type -> grpc.api.v1.GetMetadataRequest
	9,  // 6: grpc.api.v1.ECGService.UpdateMetadata:input_type -> grpc.api.v1.UpdateMetadataRequest
	3,  // 7: grpc.api.v1.ECGService.GetFilters:output_type -> grpc.api.v1.GetFiltersResponse
	5,  // 8: grpc.api.v1.ECGService.ListAll:output_type -> grpc.api.v1.ListAllResponse
	8,  // 9: grpc.api.v1.ECGService.GetMetadata:output_type -> grpc.api.v1.GetMetadataResponse
	10, // 10: grpc.api.v1.ECGService.UpdateMetadata:output_type -> grpc.api.v1.UpdateMetadataResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_v1_ecg_proto_init() }
func file_v1_ecg_proto_init() {
	if File_v1_ecg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_ecg_proto_rawDesc), len(file_v1_ecg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_ecg_proto_goTypes,
		DependencyIndexes: file_v1_ecg_proto_depIdxs,
		MessageInfos:      file_v1_ecg_proto_msgTypes,
	}.Build()
	File_v1_ecg_proto = out.File
	file_v1_ecg_proto_goTypes = nil
	file_v1_ecg_proto_depIdxs = nil
}
