// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/healthz.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckHealthRequest carries no input — health is a server-side snapshot.
type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_v1_healthz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_healthz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_v1_healthz_proto_rawDescGZIP(), []int{0}
}

// ConnectorHealthEntry mirrors handlers.ConnectorHealthEntry: one outbound
// PACS connector's health state. Empty host/ae_title/protocol are omitted by
// the JSON codec via proto3 default-value semantics.
type ConnectorHealthEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "ok" or the error message
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	AeTitle       string                 `protobuf:"bytes,6,opt,name=ae_title,json=aeTitle,proto3" json:"ae_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectorHealthEntry) Reset() {
	*x = ConnectorHealthEntry{}
	mi := &file_v1_healthz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorHealthEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorHealthEntry) ProtoMessage() {}

func (x *ConnectorHealthEntry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_healthz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorHealthEntry.ProtoReflect.Descriptor instead.
func (*ConnectorHealthEntry) Descriptor() ([]byte, []int) {
	return file_v1_healthz_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectorHealthEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectorHealthEntry) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ConnectorHealthEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConnectorHealthEntry) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectorHealthEntry) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectorHealthEntry) GetAeTitle() string {
	if x != nil {
		return x.AeTitle
	}
	return ""
}

// CheckHealthResponse is the full health snapshot. Unauthenticated callers get
// only status/database populated (the rest stays zero-valued); authenticated
// callers get the runtime module + connector details.
type CheckHealthResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`     // "ok" or "degraded"
	Database      string                  `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"` // "ok" or "error"
	DicomEnabled  bool                    `protobuf:"varint,3,opt,name=dicom_enabled,json=dicomEnabled,proto3" json:"dicom_enabled,omitempty"`
	DicomPort     int32                   `protobuf:"varint,4,opt,name=dicom_port,json=dicomPort,proto3" json:"dicom_port,omitempty"`
	FtpEnabled    bool                    `protobuf:"varint,5,opt,name=ftp_enabled,json=ftpEnabled,proto3" json:"ftp_enabled,omitempty"`
	FtpPort       int32                   `protobuf:"varint,6,opt,name=ftp_port,json=ftpPort,proto3" json:"ftp_port,omitempty"`
	EctpEnabled   bool                    `protobuf:"varint,7,opt,name=ectp_enabled,json=ectpEnabled,proto3" json:"ectp_enabled,omitempty"`
	EctpPort      int32                   `protobuf:"varint,8,opt,name=ectp_port,json=ectpPort,proto3" json:"ectp_port,omitempty"`
	Connectors    []*ConnectorHealthEntry `protobuf:"bytes,9,rep,name=connectors,proto3" json:"connectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthResponse) Reset() {
	*x = CheckHealthResponse{}
	mi := &file_v1_healthz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthResponse) ProtoMessage() {}

func (x *CheckHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_healthz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthResponse) Descriptor() ([]byte, []int) {
	return file_v1_healthz_proto_rawDescGZIP(), []int{2}
}

func (x *CheckHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckHealthResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *CheckHealthResponse) GetDicomEnabled() bool {
	if x != nil {
		return x.DicomEnabled
	}
	return false
}

func (x *CheckHealthResponse) GetDicomPort() int32 {
	if x != nil {
		return x.DicomPort
	}
	return 0
}

func (x *CheckHealthResponse) GetFtpEnabled() bool {
	if x != nil {
		return x.FtpEnabled
	}
	return false
}

func (x *CheckHealthResponse) GetFtpPort() int32 {
	if x != nil {
		return x.FtpPort
	}
	return 0
}

func (x *CheckHealthResponse) GetEctpEnabled() bool {
	if x != nil {
		return x.EctpEnabled
	}
	return false
}

func (x *CheckHealthResponse) GetEctpPort() int32 {
	if x != nil {
		return x.EctpPort
	}
	return 0
}

func (x *CheckHealthResponse) GetConnectors() []*ConnectorHealthEntry {
	if x != nil {
		return x.Connectors
	}
	return nil
}

var File_v1_healthz_proto protoreflect.FileDescriptor

const file_v1_healthz_proto_rawDesc = "" +
	"\n" +
	"\x10v1/healthz.proto\x12\vgrpc.api.v1\"\x14\n" +
	"\x12CheckHealthRequest\"\xa1\x01\n" +
	"\x14ConnectorHealthEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x19\n" +
	"\bae_title\x18\x06 \x01(\tR\aaeTitle\"\xcc\x02\n" +
	"\x13CheckHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12#\n" +
	"\rdicom_enabled\x18\x03 \x01(\bR\fdicomEnabled\x12\x1d\n" +
	"\n" +
	"dicom_port\x18\x04 \x01(\x05R\tdicomPort\x12\x1f\n" +
	"\vftp_enabled\x18\x05 \x01(\bR\n" +
	"ftpEnabled\x12\x19\n" +
	"\bftp_port\x18\x06 \x01(\x05R\aftpPort\x12!\n" +
	"\fectp_enabled\x18\a \x01(\bR\vectpEnabled\x12\x1b\n" +
	"\tectp_port\x18\b \x01(\x05R\bectpPort\x12A\n" +
	"\n" +
	"connectors\x18\t \x03(\v2!.grpc.api.v1.ConnectorHealthEntryR\n" +
	"connectors2d\n" +
	"\x0eHealthzService\x12R\n" +
	"\vCheckHealth\x12\x1f.grpc.api.v1.CheckHealthRequest\x1a .grpc.api.v1.CheckHealthResponse\"\x00B\xa1\x01\n" +
	"\x0fcom.grpc.api.v1B\fHealthzProtoP\x01Z2github.com/LIRYC-IHU/ecg-hub/internal/api/v1;apiv1\xa2\x02\x03GAX\xaa\x02\vGrpc.Api.V1\xca\x02\vGrpc\\Api\\V1\xe2\x02\x17Grpc\\Api\\V1\\GPBMetadata\xea\x02\rGrpc::Api::V1b\x06proto3"

var (
	file_v1_healthz_proto_rawDescOnce sync.Once
	file_v1_healthz_proto_rawDescData []byte
)

func file_v1_healthz_proto_rawDescGZIP() []byte {
	file_v1_healthz_proto_rawDescOnce.Do(func() {
		file_v1_healthz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_healthz_proto_rawDesc), len(file_v1_healthz_proto_rawDesc)))
	})
	return file_v1_healthz_proto_rawDescData
}

var file_v1_healthz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_healthz_proto_goTypes = []any{
	(*CheckHealthRequest)(nil),   // 0: grpc.api.v1.CheckHealthRequest
	(*ConnectorHealthEntry)(nil), // 1: grpc.api.v1.ConnectorHealthEntry
	(*CheckHealthResponse)(nil),  // 2: grpc.api.v1.CheckHealthResponse
}
var file_v1_healthz_proto_depIdxs = []int32{
	1, // 0: grpc.api.v1.CheckHealthResponse.connectors:type_name -> grpc.api.v1.ConnectorHealthEntry
	0, // 1: grpc.api.v1.HealthzService.CheckHealth:input_type -> grpc.api.v1.CheckHealthRequest
	2, // 2: grpc.api.v1.HealthzService.CheckHealth:output_type -> grpc.api.v1.CheckHealthResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_healthz_proto_init() }
func file_v1_healthz_proto_init() {
	if File_v1_healthz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_healthz_proto_rawDesc), len(file_v1_healthz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_healthz_proto_goTypes,
		DependencyIndexes: file_v1_healthz_proto_depIdxs,
		MessageInfos:      file_v1_healthz_proto_msgTypes,
	}.Build()
	File_v1_healthz_proto = out.File
	file_v1_healthz_proto_goTypes = nil
	file_v1_healthz_proto_depIdxs = nil
}
