// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/hl7.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OruAttempt mirrors models.HL7ORUAttempt — the outcome of an outbound HL7 ORU
// result-send (ECG result pushed to the HIS/DPI).
type OruAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EcgId         string                 `protobuf:"bytes,2,opt,name=ecg_id,json=ecgId,proto3" json:"ecg_id,omitempty"`
	PatientId     string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                  // "success"|"rejected"|"failed"
	MsaCode       string                 `protobuf:"bytes,5,opt,name=msa_code,json=msaCode,proto3" json:"msa_code,omitempty"` // AA, AE, AR, CA, CE, CR
	MsaMessage    string                 `protobuf:"bytes,6,opt,name=msa_message,json=msaMessage,proto3" json:"msa_message,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	IncludedPdf   bool                   `protobuf:"varint,8,opt,name=included_pdf,json=includedPdf,proto3" json:"included_pdf,omitempty"`
	TriggeredBy   string                 `protobuf:"bytes,9,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"` // "auto" or a user id for manual sends
	ResponseMs    int32                  `protobuf:"varint,10,opt,name=response_ms,json=responseMs,proto3" json:"response_ms,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601 UTC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OruAttempt) Reset() {
	*x = OruAttempt{}
	mi := &file_v1_hl7_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OruAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OruAttempt) ProtoMessage() {}

func (x *OruAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OruAttempt.ProtoReflect.Descriptor instead.
func (*OruAttempt) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{0}
}

func (x *OruAttempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OruAttempt) GetEcgId() string {
	if x != nil {
		return x.EcgId
	}
	return ""
}

func (x *OruAttempt) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *OruAttempt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OruAttempt) GetMsaCode() string {
	if x != nil {
		return x.MsaCode
	}
	return ""
}

func (x *OruAttempt) GetMsaMessage() string {
	if x != nil {
		return x.MsaMessage
	}
	return ""
}

func (x *OruAttempt) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OruAttempt) GetIncludedPdf() bool {
	if x != nil {
		return x.IncludedPdf
	}
	return false
}

func (x *OruAttempt) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

func (x *OruAttempt) GetResponseMs() int32 {
	if x != nil {
		return x.ResponseMs
	}
	return 0
}

func (x *OruAttempt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Hl7Attempt mirrors models.HL7Attempt — one inbound HL7 enrichment attempt.
type Hl7Attempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EcgId         string                 `protobuf:"bytes,2,opt,name=ecg_id,json=ecgId,proto3" json:"ecg_id,omitempty"`
	PatientId     string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                  // "success"|"failed"|"exhausted"|"rejected"
	MsaCode       string                 `protobuf:"bytes,5,opt,name=msa_code,json=msaCode,proto3" json:"msa_code,omitempty"` // AA, AE, AR
	MsaMessage    string                 `protobuf:"bytes,6,opt,name=msa_message,json=msaMessage,proto3" json:"msa_message,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	ResponseMs    int32                  `protobuf:"varint,8,opt,name=response_ms,json=responseMs,proto3" json:"response_ms,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601 UTC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hl7Attempt) Reset() {
	*x = Hl7Attempt{}
	mi := &file_v1_hl7_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hl7Attempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hl7Attempt) ProtoMessage() {}

func (x *Hl7Attempt) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hl7Attempt.ProtoReflect.Descriptor instead.
func (*Hl7Attempt) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{1}
}

func (x *Hl7Attempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hl7Attempt) GetEcgId() string {
	if x != nil {
		return x.EcgId
	}
	return ""
}

func (x *Hl7Attempt) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Hl7Attempt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Hl7Attempt) GetMsaCode() string {
	if x != nil {
		return x.MsaCode
	}
	return ""
}

func (x *Hl7Attempt) GetMsaMessage() string {
	if x != nil {
		return x.MsaMessage
	}
	return ""
}

func (x *Hl7Attempt) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Hl7Attempt) GetResponseMs() int32 {
	if x != nil {
		return x.ResponseMs
	}
	return 0
}

func (x *Hl7Attempt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ForceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EcgId         string                 `protobuf:"bytes,1,opt,name=ecg_id,json=ecgId,proto3" json:"ecg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceRequest) Reset() {
	*x = ForceRequest{}
	mi := &file_v1_hl7_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceRequest) ProtoMessage() {}

func (x *ForceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceRequest.ProtoReflect.Descriptor instead.
func (*ForceRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{2}
}

func (x *ForceRequest) GetEcgId() string {
	if x != nil {
		return x.EcgId
	}
	return ""
}

type ForceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hl7Status     string                 `protobuf:"bytes,1,opt,name=hl7_status,json=hl7Status,proto3" json:"hl7_status,omitempty"` // always "pending" after a forced retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceResponse) Reset() {
	*x = ForceResponse{}
	mi := &file_v1_hl7_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceResponse) ProtoMessage() {}

func (x *ForceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceResponse.ProtoReflect.Descriptor instead.
func (*ForceResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{3}
}

func (x *ForceResponse) GetHl7Status() string {
	if x != nil {
		return x.Hl7Status
	}
	return ""
}

type GetOruStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EcgId         string                 `protobuf:"bytes,1,opt,name=ecg_id,json=ecgId,proto3" json:"ecg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOruStatusRequest) Reset() {
	*x = GetOruStatusRequest{}
	mi := &file_v1_hl7_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOruStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOruStatusRequest) ProtoMessage() {}

func (x *GetOruStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOruStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOruStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{4}
}

func (x *GetOruStatusRequest) GetEcgId() string {
	if x != nil {
		return x.EcgId
	}
	return ""
}

type GetOruStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *OruAttempt            `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"` // unset when the ECG has no ORU attempt yet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOruStatusResponse) Reset() {
	*x = GetOruStatusResponse{}
	mi := &file_v1_hl7_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOruStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOruStatusResponse) ProtoMessage() {}

func (x *GetOruStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOruStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOruStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{5}
}

func (x *GetOruStatusResponse) GetAttempt() *OruAttempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

type SendResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EcgId         string                 `protobuf:"bytes,1,opt,name=ecg_id,json=ecgId,proto3" json:"ecg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResultRequest) Reset() {
	*x = SendResultRequest{}
	mi := &file_v1_hl7_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResultRequest) ProtoMessage() {}

func (x *SendResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResultRequest.ProtoReflect.Descriptor instead.
func (*SendResultRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{6}
}

func (x *SendResultRequest) GetEcgId() string {
	if x != nil {
		return x.EcgId
	}
	return ""
}

type SendResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *OruAttempt            `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"` // the recorded attempt on a successful send
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResultResponse) Reset() {
	*x = SendResultResponse{}
	mi := &file_v1_hl7_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResultResponse) ProtoMessage() {}

func (x *SendResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResultResponse.ProtoReflect.Descriptor instead.
func (*SendResultResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{7}
}

func (x *SendResultResponse) GetAttempt() *OruAttempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

type ListAttemptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 1..100, defaults to 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttemptsRequest) Reset() {
	*x = ListAttemptsRequest{}
	mi := &file_v1_hl7_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttemptsRequest) ProtoMessage() {}

func (x *ListAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttemptsRequest.ProtoReflect.Descriptor instead.
func (*ListAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{8}
}

func (x *ListAttemptsRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ListAttemptsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAttemptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Hl7Attempt          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttemptsResponse) Reset() {
	*x = ListAttemptsResponse{}
	mi := &file_v1_hl7_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttemptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttemptsResponse) ProtoMessage() {}

func (x *ListAttemptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttemptsResponse.ProtoReflect.Descriptor instead.
func (*ListAttemptsResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7_proto_rawDescGZIP(), []int{9}
}

func (x *ListAttemptsResponse) GetData() []*Hl7Attempt {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_hl7_proto protoreflect.FileDescriptor

const file_v1_hl7_proto_rawDesc = "" +
	"\n" +
	"\fv1/hl7.proto\x12\vgrpc.api.v1\"\xc2\x02\n" +
	"\n" +
	"OruAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06ecg_id\x18\x02 \x01(\tR\x05ecgId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x19\n" +
	"\bmsa_code\x18\x05 \x01(\tR\amsaCode\x12\x1f\n" +
	"\vmsa_message\x18\x06 \x01(\tR\n" +
	"msaMessage\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12!\n" +
	"\fincluded_pdf\x18\b \x01(\bR\vincludedPdf\x12!\n" +
	"\ftriggered_by\x18\t \x01(\tR\vtriggeredBy\x12\x1f\n" +
	"\vresponse_ms\x18\n" +
	" \x01(\x05R\n" +
	"responseMs\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"\xfc\x01\n" +
	"\n" +
	"Hl7Attempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06ecg_id\x18\x02 \x01(\tR\x05ecgId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x19\n" +
	"\bmsa_code\x18\x05 \x01(\tR\amsaCode\x12\x1f\n" +
	"\vmsa_message\x18\x06 \x01(\tR\n" +
	"msaMessage\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1f\n" +
	"\vresponse_ms\x18\b \x01(\x05R\n" +
	"responseMs\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"%\n" +
	"\fForceRequest\x12\x15\n" +
	"\x06ecg_id\x18\x01 \x01(\tR\x05ecgId\".\n" +
	"\rForceResponse\x12\x1d\n" +
	"\n" +
	"hl7_status\x18\x01 \x01(\tR\thl7Status\",\n" +
	"\x13GetOruStatusRequest\x12\x15\n" +
	"\x06ecg_id\x18\x01 \x01(\tR\x05ecgId\"I\n" +
	"\x14GetOruStatusResponse\x121\n" +
	"\aattempt\x18\x01 \x01(\v2\x17.grpc.api.v1.OruAttemptR\aattempt\"*\n" +
	"\x11SendResultRequest\x12\x15\n" +
	"\x06ecg_id\x18\x01 \x01(\tR\x05ecgId\"G\n" +
	"\x12SendResultResponse\x121\n" +
	"\aattempt\x18\x01 \x01(\v2\x17.grpc.api.v1.OruAttemptR\aattempt\"J\n" +
	"\x13ListAttemptsRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"C\n" +
	"\x14ListAttemptsResponse\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.grpc.api.v1.Hl7AttemptR\x04data2\xcd\x02\n" +
	"\n" +
	"HL7Service\x12@\n" +
	"\x05Force\x12\x19.grpc.api.v1.ForceRequest\x1a\x1a.grpc.api.v1.ForceResponse\"\x00\x12U\n" +
	"\fGetOruStatus\x12 .grpc.api.v1.GetOruStatusRequest\x1a!.grpc.api.v1.GetOruStatusResponse\"\x00\x12O\n" +
	"\n" +
	"SendResult\x12\x1e.grpc.api.v1.SendResultRequest\x1a\x1f.grpc.api.v1.SendResultResponse\"\x00\x12U\n" +
	"\fListAttempts\x12 .grpc.api.v1.ListAttemptsRequest\x1a!.grpc.api.v1.ListAttemptsResponse\"\x00B\x9d\x01\n" +
	"\x0fcom.grpc.api.v1B\bHl7ProtoP\x01Z2github.com/LIRYC-IHU/ecg-hub/internal/api/v1;apiv1\xa2\x02\x03GAX\xaa\x02\vGrpc.Api.V1\xca\x02\vGrpc\\Api\\V1\xe2\x02\x17Grpc\\Api\\V1\\GPBMetadata\xea\x02\rGrpc::Api::V1b\x06proto3"

var (
	file_v1_hl7_proto_rawDescOnce sync.Once
	file_v1_hl7_proto_rawDescData []byte
)

func file_v1_hl7_proto_rawDescGZIP() []byte {
	file_v1_hl7_proto_rawDescOnce.Do(func() {
		file_v1_hl7_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_hl7_proto_rawDesc), len(file_v1_hl7_proto_rawDesc)))
	})
	return file_v1_hl7_proto_rawDescData
}

var file_v1_hl7_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_hl7_proto_goTypes = []any{
	(*OruAttempt)(nil),           // 0: grpc.api.v1.OruAttempt
	(*Hl7Attempt)(nil),           // 1: grpc.api.v1.Hl7Attempt
	(*ForceRequest)(nil),         // 2: grpc.api.v1.ForceRequest
	(*ForceResponse)(nil),        // 3: grpc.api.v1.ForceResponse
	(*GetOruStatusRequest)(nil),  // 4: grpc.api.v1.GetOruStatusRequest
	(*GetOruStatusResponse)(nil), // 5: grpc.api.v1.GetOruStatusResponse
	(*SendResultRequest)(nil),    // 6: grpc.api.v1.SendResultRequest
	(*SendResultResponse)(nil),   // 7: grpc.api.v1.SendResultResponse
	(*ListAttemptsRequest)(nil),  // 8: grpc.api.v1.ListAttemptsRequest
	(*ListAttemptsResponse)(nil), // 9: grpc.api.v1.ListAttemptsResponse
}
var file_v1_hl7_proto_depIdxs = []int32{
	0, // 0: grpc.api.v1.GetOruStatusResponse.attempt:type_name -> grpc.api.v1.OruAttempt
	0, // 1: grpc.api.v1.SendResultResponse.attempt:type_name -> grpc.api.v1.OruAttempt
	1, // 2: grpc.api.v1.ListAttemptsResponse.data:type_name -> grpc.api.v1.Hl7Attempt
	2, // 3: grpc.api.v1.HL7Service.Force:input_type -> grpc.api.v1.ForceRequest
	4, // 4: grpc.api.v1.HL7Service.GetOruStatus:input_type -> grpc.api.v1.GetOruStatusRequest
	6, // 5: grpc.api.v1.HL7Service.SendResult:input_type -> grpc.api.v1.SendResultRequest
	8, // 6: grpc.api.v1.HL7Service.ListAttempts:input_type -> grpc.api.v1.ListAttemptsRequest
	3, // 7: grpc.api.v1.HL7Service.Force:output_type -> grpc.api.v1.ForceResponse
	5, // 8: grpc.api.v1.HL7Service.GetOruStatus:output_type -> grpc.api.v1.GetOruStatusResponse
	7, // 9: grpc.api.v1.HL7Service.SendResult:output_type -> grpc.api.v1.SendResultResponse
	9, // 10: grpc.api.v1.HL7Service.ListAttempts:output_type -> grpc.api.v1.ListAttemptsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_hl7_proto_init() }
func file_v1_hl7_proto_init() {
	if File_v1_hl7_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_hl7_proto_rawDesc), len(file_v1_hl7_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_hl7_proto_goTypes,
		DependencyIndexes: file_v1_hl7_proto_depIdxs,
		MessageInfos:      file_v1_hl7_proto_msgTypes,
	}.Build()
	File_v1_hl7_proto = out.File
	file_v1_hl7_proto_goTypes = nil
	file_v1_hl7_proto_depIdxs = nil
}
