// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/hl7admin.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HL7Mapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PresetId      string                 `protobuf:"bytes,2,opt,name=preset_id,json=presetId,proto3" json:"preset_id,omitempty"`
	SourcePath    string                 `protobuf:"bytes,3,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	TargetField   string                 `protobuf:"bytes,4,opt,name=target_field,json=targetField,proto3" json:"target_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HL7Mapping) Reset() {
	*x = HL7Mapping{}
	mi := &file_v1_hl7admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HL7Mapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HL7Mapping) ProtoMessage() {}

func (x *HL7Mapping) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HL7Mapping.ProtoReflect.Descriptor instead.
func (*HL7Mapping) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{0}
}

func (x *HL7Mapping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HL7Mapping) GetPresetId() string {
	if x != nil {
		return x.PresetId
	}
	return ""
}

func (x *HL7Mapping) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *HL7Mapping) GetTargetField() string {
	if x != nil {
		return x.TargetField
	}
	return ""
}

// HL7MappingInput is a mapping supplied by the client on create/save (no ids).
type HL7MappingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	TargetField   string                 `protobuf:"bytes,2,opt,name=target_field,json=targetField,proto3" json:"target_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HL7MappingInput) Reset() {
	*x = HL7MappingInput{}
	mi := &file_v1_hl7admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HL7MappingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HL7MappingInput) ProtoMessage() {}

func (x *HL7MappingInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HL7MappingInput.ProtoReflect.Descriptor instead.
func (*HL7MappingInput) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{1}
}

func (x *HL7MappingInput) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *HL7MappingInput) GetTargetField() string {
	if x != nil {
		return x.TargetField
	}
	return ""
}

type HL7Preset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	Mappings      []*HL7Mapping          `protobuf:"bytes,5,rep,name=mappings,proto3" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HL7Preset) Reset() {
	*x = HL7Preset{}
	mi := &file_v1_hl7admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HL7Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HL7Preset) ProtoMessage() {}

func (x *HL7Preset) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HL7Preset.ProtoReflect.Descriptor instead.
func (*HL7Preset) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{2}
}

func (x *HL7Preset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HL7Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HL7Preset) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *HL7Preset) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *HL7Preset) GetMappings() []*HL7Mapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type ListHL7PresetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHL7PresetsRequest) Reset() {
	*x = ListHL7PresetsRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHL7PresetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHL7PresetsRequest) ProtoMessage() {}

func (x *ListHL7PresetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHL7PresetsRequest.ProtoReflect.Descriptor instead.
func (*ListHL7PresetsRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{3}
}

type ListHL7PresetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presets       []*HL7Preset           `protobuf:"bytes,1,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHL7PresetsResponse) Reset() {
	*x = ListHL7PresetsResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHL7PresetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHL7PresetsResponse) ProtoMessage() {}

func (x *ListHL7PresetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHL7PresetsResponse.ProtoReflect.Descriptor instead.
func (*ListHL7PresetsResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListHL7PresetsResponse) GetPresets() []*HL7Preset {
	if x != nil {
		return x.Presets
	}
	return nil
}

type CreateHL7PresetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mappings      []*HL7MappingInput     `protobuf:"bytes,2,rep,name=mappings,proto3" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHL7PresetRequest) Reset() {
	*x = CreateHL7PresetRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHL7PresetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHL7PresetRequest) ProtoMessage() {}

func (x *CreateHL7PresetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHL7PresetRequest.ProtoReflect.Descriptor instead.
func (*CreateHL7PresetRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateHL7PresetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateHL7PresetRequest) GetMappings() []*HL7MappingInput {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type CreateHL7PresetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preset        *HL7Preset             `protobuf:"bytes,1,opt,name=preset,proto3" json:"preset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHL7PresetResponse) Reset() {
	*x = CreateHL7PresetResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHL7PresetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHL7PresetResponse) ProtoMessage() {}

func (x *CreateHL7PresetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHL7PresetResponse.ProtoReflect.Descriptor instead.
func (*CreateHL7PresetResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{6}
}

func (x *CreateHL7PresetResponse) GetPreset() *HL7Preset {
	if x != nil {
		return x.Preset
	}
	return nil
}

type ActivateHL7PresetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateHL7PresetRequest) Reset() {
	*x = ActivateHL7PresetRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateHL7PresetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateHL7PresetRequest) ProtoMessage() {}

func (x *ActivateHL7PresetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateHL7PresetRequest.ProtoReflect.Descriptor instead.
func (*ActivateHL7PresetRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{7}
}

func (x *ActivateHL7PresetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActivateHL7PresetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateHL7PresetResponse) Reset() {
	*x = ActivateHL7PresetResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateHL7PresetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateHL7PresetResponse) ProtoMessage() {}

func (x *ActivateHL7PresetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateHL7PresetResponse.ProtoReflect.Descriptor instead.
func (*ActivateHL7PresetResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{8}
}

type DeleteHL7PresetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHL7PresetRequest) Reset() {
	*x = DeleteHL7PresetRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHL7PresetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHL7PresetRequest) ProtoMessage() {}

func (x *DeleteHL7PresetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHL7PresetRequest.ProtoReflect.Descriptor instead.
func (*DeleteHL7PresetRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteHL7PresetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteHL7PresetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHL7PresetResponse) Reset() {
	*x = DeleteHL7PresetResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHL7PresetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHL7PresetResponse) ProtoMessage() {}

func (x *DeleteHL7PresetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHL7PresetResponse.ProtoReflect.Descriptor instead.
func (*DeleteHL7PresetResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{10}
}

type SaveHL7PresetMappingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mappings      []*HL7MappingInput     `protobuf:"bytes,2,rep,name=mappings,proto3" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveHL7PresetMappingsRequest) Reset() {
	*x = SaveHL7PresetMappingsRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHL7PresetMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHL7PresetMappingsRequest) ProtoMessage() {}

func (x *SaveHL7PresetMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHL7PresetMappingsRequest.ProtoReflect.Descriptor instead.
func (*SaveHL7PresetMappingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{11}
}

func (x *SaveHL7PresetMappingsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveHL7PresetMappingsRequest) GetMappings() []*HL7MappingInput {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type SaveHL7PresetMappingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mappings      []*HL7Mapping          `protobuf:"bytes,1,rep,name=mappings,proto3" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveHL7PresetMappingsResponse) Reset() {
	*x = SaveHL7PresetMappingsResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveHL7PresetMappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveHL7PresetMappingsResponse) ProtoMessage() {}

func (x *SaveHL7PresetMappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveHL7PresetMappingsResponse.ProtoReflect.Descriptor instead.
func (*SaveHL7PresetMappingsResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{12}
}

func (x *SaveHL7PresetMappingsResponse) GetMappings() []*HL7Mapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type GetActiveHL7MappingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveHL7MappingsRequest) Reset() {
	*x = GetActiveHL7MappingsRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveHL7MappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveHL7MappingsRequest) ProtoMessage() {}

func (x *GetActiveHL7MappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveHL7MappingsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveHL7MappingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{13}
}

type GetActiveHL7MappingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*HL7Mapping          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveHL7MappingsResponse) Reset() {
	*x = GetActiveHL7MappingsResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveHL7MappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveHL7MappingsResponse) ProtoMessage() {}

func (x *GetActiveHL7MappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveHL7MappingsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveHL7MappingsResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{14}
}

func (x *GetActiveHL7MappingsResponse) GetData() []*HL7Mapping {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetActiveHL7MappingsResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type HL7Demographics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastName      string                 `protobuf:"bytes,1,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HL7Demographics) Reset() {
	*x = HL7Demographics{}
	mi := &file_v1_hl7admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HL7Demographics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HL7Demographics) ProtoMessage() {}

func (x *HL7Demographics) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HL7Demographics.ProtoReflect.Descriptor instead.
func (*HL7Demographics) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{15}
}

func (x *HL7Demographics) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *HL7Demographics) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *HL7Demographics) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *HL7Demographics) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *HL7Demographics) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type HL7TestQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HL7TestQueryRequest) Reset() {
	*x = HL7TestQueryRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HL7TestQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HL7TestQueryRequest) ProtoMessage() {}

func (x *HL7TestQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HL7TestQueryRequest.ProtoReflect.Descriptor instead.
func (*HL7TestQueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{16}
}

func (x *HL7TestQueryRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type HL7TestQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Raw           string                 `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`
	TreeJson      string                 `protobuf:"bytes,6,opt,name=tree_json,json=treeJson,proto3" json:"tree_json,omitempty"` // JSON-encoded []SegmentNode (recursive; parsed client-side)
	MsaCode       string                 `protobuf:"bytes,7,opt,name=msa_code,json=msaCode,proto3" json:"msa_code,omitempty"`
	MsaMessage    string                 `protobuf:"bytes,8,opt,name=msa_message,json=msaMessage,proto3" json:"msa_message,omitempty"`
	Demographics  *HL7Demographics       `protobuf:"bytes,9,opt,name=demographics,proto3" json:"demographics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HL7TestQueryResponse) Reset() {
	*x = HL7TestQueryResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HL7TestQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HL7TestQueryResponse) ProtoMessage() {}

func (x *HL7TestQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HL7TestQueryResponse.ProtoReflect.Descriptor instead.
func (*HL7TestQueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{17}
}

func (x *HL7TestQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HL7TestQueryResponse) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *HL7TestQueryResponse) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *HL7TestQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HL7TestQueryResponse) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *HL7TestQueryResponse) GetTreeJson() string {
	if x != nil {
		return x.TreeJson
	}
	return ""
}

func (x *HL7TestQueryResponse) GetMsaCode() string {
	if x != nil {
		return x.MsaCode
	}
	return ""
}

func (x *HL7TestQueryResponse) GetMsaMessage() string {
	if x != nil {
		return x.MsaMessage
	}
	return ""
}

func (x *HL7TestQueryResponse) GetDemographics() *HL7Demographics {
	if x != nil {
		return x.Demographics
	}
	return nil
}

type HL7PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HL7PingRequest) Reset() {
	*x = HL7PingRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HL7PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HL7PingRequest) ProtoMessage() {}

func (x *HL7PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HL7PingRequest.ProtoReflect.Descriptor instead.
func (*HL7PingRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{18}
}

type HL7PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Latency       string                 `protobuf:"bytes,3,opt,name=latency,proto3" json:"latency,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HL7PingResponse) Reset() {
	*x = HL7PingResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HL7PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HL7PingResponse) ProtoMessage() {}

func (x *HL7PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HL7PingResponse.ProtoReflect.Descriptor instead.
func (*HL7PingResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{19}
}

func (x *HL7PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HL7PingResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HL7PingResponse) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

func (x *HL7PingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HL7Settings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TriggerMode    string                 `protobuf:"bytes,2,opt,name=trigger_mode,json=triggerMode,proto3" json:"trigger_mode,omitempty"` // "immediate" | "scheduled"
	CronExpression string                 `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Timeout        string                 `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Enabled        bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Hl7Enabled     bool                   `protobuf:"varint,7,opt,name=hl7_enabled,json=hl7Enabled,proto3" json:"hl7_enabled,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastRun        string                 `protobuf:"bytes,9,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`  // empty when never run
	NextRun        string                 `protobuf:"bytes,10,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"` // empty when scheduler disabled
	// Connection
	Host                 string `protobuf:"bytes,11,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32  `protobuf:"varint,12,opt,name=port,proto3" json:"port,omitempty"`
	SendingApplication   string `protobuf:"bytes,13,opt,name=sending_application,json=sendingApplication,proto3" json:"sending_application,omitempty"`
	SendingFacility      string `protobuf:"bytes,14,opt,name=sending_facility,json=sendingFacility,proto3" json:"sending_facility,omitempty"`
	ReceivingApplication string `protobuf:"bytes,15,opt,name=receiving_application,json=receivingApplication,proto3" json:"receiving_application,omitempty"`
	ReceivingFacility    string `protobuf:"bytes,16,opt,name=receiving_facility,json=receivingFacility,proto3" json:"receiving_facility,omitempty"`
	Version              string `protobuf:"bytes,17,opt,name=version,proto3" json:"version,omitempty"`
	ProcessingId         string `protobuf:"bytes,18,opt,name=processing_id,json=processingId,proto3" json:"processing_id,omitempty"`
	// Outbound ORU
	OruEnabled     bool   `protobuf:"varint,19,opt,name=oru_enabled,json=oruEnabled,proto3" json:"oru_enabled,omitempty"`
	OruTriggerMode string `protobuf:"bytes,20,opt,name=oru_trigger_mode,json=oruTriggerMode,proto3" json:"oru_trigger_mode,omitempty"` // "auto" | "manual"
	OruHost        string `protobuf:"bytes,21,opt,name=oru_host,json=oruHost,proto3" json:"oru_host,omitempty"`
	OruPort        int32  `protobuf:"varint,22,opt,name=oru_port,json=oruPort,proto3" json:"oru_port,omitempty"`
	OruIncludePdf  bool   `protobuf:"varint,23,opt,name=oru_include_pdf,json=oruIncludePdf,proto3" json:"oru_include_pdf,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HL7Settings) Reset() {
	*x = HL7Settings{}
	mi := &file_v1_hl7admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HL7Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HL7Settings) ProtoMessage() {}

func (x *HL7Settings) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HL7Settings.ProtoReflect.Descriptor instead.
func (*HL7Settings) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{20}
}

func (x *HL7Settings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HL7Settings) GetTriggerMode() string {
	if x != nil {
		return x.TriggerMode
	}
	return ""
}

func (x *HL7Settings) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *HL7Settings) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *HL7Settings) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *HL7Settings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HL7Settings) GetHl7Enabled() bool {
	if x != nil {
		return x.Hl7Enabled
	}
	return false
}

func (x *HL7Settings) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *HL7Settings) GetLastRun() string {
	if x != nil {
		return x.LastRun
	}
	return ""
}

func (x *HL7Settings) GetNextRun() string {
	if x != nil {
		return x.NextRun
	}
	return ""
}

func (x *HL7Settings) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HL7Settings) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HL7Settings) GetSendingApplication() string {
	if x != nil {
		return x.SendingApplication
	}
	return ""
}

func (x *HL7Settings) GetSendingFacility() string {
	if x != nil {
		return x.SendingFacility
	}
	return ""
}

func (x *HL7Settings) GetReceivingApplication() string {
	if x != nil {
		return x.ReceivingApplication
	}
	return ""
}

func (x *HL7Settings) GetReceivingFacility() string {
	if x != nil {
		return x.ReceivingFacility
	}
	return ""
}

func (x *HL7Settings) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HL7Settings) GetProcessingId() string {
	if x != nil {
		return x.ProcessingId
	}
	return ""
}

func (x *HL7Settings) GetOruEnabled() bool {
	if x != nil {
		return x.OruEnabled
	}
	return false
}

func (x *HL7Settings) GetOruTriggerMode() string {
	if x != nil {
		return x.OruTriggerMode
	}
	return ""
}

func (x *HL7Settings) GetOruHost() string {
	if x != nil {
		return x.OruHost
	}
	return ""
}

func (x *HL7Settings) GetOruPort() int32 {
	if x != nil {
		return x.OruPort
	}
	return 0
}

func (x *HL7Settings) GetOruIncludePdf() bool {
	if x != nil {
		return x.OruIncludePdf
	}
	return false
}

type GetHL7SettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHL7SettingsRequest) Reset() {
	*x = GetHL7SettingsRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHL7SettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHL7SettingsRequest) ProtoMessage() {}

func (x *GetHL7SettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHL7SettingsRequest.ProtoReflect.Descriptor instead.
func (*GetHL7SettingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{21}
}

type GetHL7SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *HL7Settings           `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHL7SettingsResponse) Reset() {
	*x = GetHL7SettingsResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHL7SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHL7SettingsResponse) ProtoMessage() {}

func (x *GetHL7SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHL7SettingsResponse.ProtoReflect.Descriptor instead.
func (*GetHL7SettingsResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{22}
}

func (x *GetHL7SettingsResponse) GetSettings() *HL7Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// UpdateHL7SettingsRequest uses proto3 `optional` on every field so only the
// fields the client actually sets are applied (mirrors the pointer-based REST
// PATCH semantics).
type UpdateHL7SettingsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Hl7Enabled           *bool                  `protobuf:"varint,1,opt,name=hl7_enabled,json=hl7Enabled,proto3,oneof" json:"hl7_enabled,omitempty"`
	TriggerMode          *string                `protobuf:"bytes,2,opt,name=trigger_mode,json=triggerMode,proto3,oneof" json:"trigger_mode,omitempty"`
	CronExpression       *string                `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression,proto3,oneof" json:"cron_expression,omitempty"`
	MaxRetries           *int32                 `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3,oneof" json:"max_retries,omitempty"`
	Timeout              *string                `protobuf:"bytes,5,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	Enabled              *bool                  `protobuf:"varint,6,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Host                 *string                `protobuf:"bytes,7,opt,name=host,proto3,oneof" json:"host,omitempty"`
	Port                 *int32                 `protobuf:"varint,8,opt,name=port,proto3,oneof" json:"port,omitempty"`
	SendingApplication   *string                `protobuf:"bytes,9,opt,name=sending_application,json=sendingApplication,proto3,oneof" json:"sending_application,omitempty"`
	SendingFacility      *string                `protobuf:"bytes,10,opt,name=sending_facility,json=sendingFacility,proto3,oneof" json:"sending_facility,omitempty"`
	ReceivingApplication *string                `protobuf:"bytes,11,opt,name=receiving_application,json=receivingApplication,proto3,oneof" json:"receiving_application,omitempty"`
	ReceivingFacility    *string                `protobuf:"bytes,12,opt,name=receiving_facility,json=receivingFacility,proto3,oneof" json:"receiving_facility,omitempty"`
	Version              *string                `protobuf:"bytes,13,opt,name=version,proto3,oneof" json:"version,omitempty"`
	ProcessingId         *string                `protobuf:"bytes,14,opt,name=processing_id,json=processingId,proto3,oneof" json:"processing_id,omitempty"`
	OruEnabled           *bool                  `protobuf:"varint,15,opt,name=oru_enabled,json=oruEnabled,proto3,oneof" json:"oru_enabled,omitempty"`
	OruTriggerMode       *string                `protobuf:"bytes,16,opt,name=oru_trigger_mode,json=oruTriggerMode,proto3,oneof" json:"oru_trigger_mode,omitempty"`
	OruHost              *string                `protobuf:"bytes,17,opt,name=oru_host,json=oruHost,proto3,oneof" json:"oru_host,omitempty"`
	OruPort              *int32                 `protobuf:"varint,18,opt,name=oru_port,json=oruPort,proto3,oneof" json:"oru_port,omitempty"`
	OruIncludePdf        *bool                  `protobuf:"varint,19,opt,name=oru_include_pdf,json=oruIncludePdf,proto3,oneof" json:"oru_include_pdf,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateHL7SettingsRequest) Reset() {
	*x = UpdateHL7SettingsRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHL7SettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHL7SettingsRequest) ProtoMessage() {}

func (x *UpdateHL7SettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHL7SettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateHL7SettingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateHL7SettingsRequest) GetHl7Enabled() bool {
	if x != nil && x.Hl7Enabled != nil {
		return *x.Hl7Enabled
	}
	return false
}

func (x *UpdateHL7SettingsRequest) GetTriggerMode() string {
	if x != nil && x.TriggerMode != nil {
		return *x.TriggerMode
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetCronExpression() string {
	if x != nil && x.CronExpression != nil {
		return *x.CronExpression
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetMaxRetries() int32 {
	if x != nil && x.MaxRetries != nil {
		return *x.MaxRetries
	}
	return 0
}

func (x *UpdateHL7SettingsRequest) GetTimeout() string {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *UpdateHL7SettingsRequest) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *UpdateHL7SettingsRequest) GetSendingApplication() string {
	if x != nil && x.SendingApplication != nil {
		return *x.SendingApplication
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetSendingFacility() string {
	if x != nil && x.SendingFacility != nil {
		return *x.SendingFacility
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetReceivingApplication() string {
	if x != nil && x.ReceivingApplication != nil {
		return *x.ReceivingApplication
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetReceivingFacility() string {
	if x != nil && x.ReceivingFacility != nil {
		return *x.ReceivingFacility
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetProcessingId() string {
	if x != nil && x.ProcessingId != nil {
		return *x.ProcessingId
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetOruEnabled() bool {
	if x != nil && x.OruEnabled != nil {
		return *x.OruEnabled
	}
	return false
}

func (x *UpdateHL7SettingsRequest) GetOruTriggerMode() string {
	if x != nil && x.OruTriggerMode != nil {
		return *x.OruTriggerMode
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetOruHost() string {
	if x != nil && x.OruHost != nil {
		return *x.OruHost
	}
	return ""
}

func (x *UpdateHL7SettingsRequest) GetOruPort() int32 {
	if x != nil && x.OruPort != nil {
		return *x.OruPort
	}
	return 0
}

func (x *UpdateHL7SettingsRequest) GetOruIncludePdf() bool {
	if x != nil && x.OruIncludePdf != nil {
		return *x.OruIncludePdf
	}
	return false
}

type UpdateHL7SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *HL7Settings           `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHL7SettingsResponse) Reset() {
	*x = UpdateHL7SettingsResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHL7SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHL7SettingsResponse) ProtoMessage() {}

func (x *UpdateHL7SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHL7SettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateHL7SettingsResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateHL7SettingsResponse) GetSettings() *HL7Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ForceHL7RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceHL7RunRequest) Reset() {
	*x = ForceHL7RunRequest{}
	mi := &file_v1_hl7admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceHL7RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceHL7RunRequest) ProtoMessage() {}

func (x *ForceHL7RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceHL7RunRequest.ProtoReflect.Descriptor instead.
func (*ForceHL7RunRequest) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{25}
}

type ForceHL7RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceHL7RunResponse) Reset() {
	*x = ForceHL7RunResponse{}
	mi := &file_v1_hl7admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceHL7RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceHL7RunResponse) ProtoMessage() {}

func (x *ForceHL7RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceHL7RunResponse.ProtoReflect.Descriptor instead.
func (*ForceHL7RunResponse) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{26}
}

func (x *ForceHL7RunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BulkRetryHL7Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRetryHL7Request) Reset() {
	*x = BulkRetryHL7Request{}
	mi := &file_v1_hl7admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRetryHL7Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRetryHL7Request) ProtoMessage() {}

func (x *BulkRetryHL7Request) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRetryHL7Request.ProtoReflect.Descriptor instead.
func (*BulkRetryHL7Request) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{27}
}

type BulkRetryHL7Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRetryHL7Response) Reset() {
	*x = BulkRetryHL7Response{}
	mi := &file_v1_hl7admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRetryHL7Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRetryHL7Response) ProtoMessage() {}

func (x *BulkRetryHL7Response) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hl7admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRetryHL7Response.ProtoReflect.Descriptor instead.
func (*BulkRetryHL7Response) Descriptor() ([]byte, []int) {
	return file_v1_hl7admin_proto_rawDescGZIP(), []int{28}
}

func (x *BulkRetryHL7Response) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BulkRetryHL7Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_hl7admin_proto protoreflect.FileDescriptor

const file_v1_hl7admin_proto_rawDesc = "" +
	"\n" +
	"\x11v1/hl7admin.proto\x12\vgrpc.api.v1\"}\n" +
	"\n" +
	"HL7Mapping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tpreset_id\x18\x02 \x01(\tR\bpresetId\x12\x1f\n" +
	"\vsource_path\x18\x03 \x01(\tR\n" +
	"sourcePath\x12!\n" +
	"\ftarget_field\x18\x04 \x01(\tR\vtargetField\"U\n" +
	"\x0fHL7MappingInput\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12!\n" +
	"\ftarget_field\x18\x02 \x01(\tR\vtargetField\"\x9b\x01\n" +
	"\tHL7Preset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x123\n" +
	"\bmappings\x18\x05 \x03(\v2\x17.grpc.api.v1.HL7MappingR\bmappings\"\x17\n" +
	"\x15ListHL7PresetsRequest\"J\n" +
	"\x16ListHL7PresetsResponse\x120\n" +
	"\apresets\x18\x01 \x03(\v2\x16.grpc.api.v1.HL7PresetR\apresets\"f\n" +
	"\x16CreateHL7PresetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\bmappings\x18\x02 \x03(\v2\x1c.grpc.api.v1.HL7MappingInputR\bmappings\"I\n" +
	"\x17CreateHL7PresetResponse\x12.\n" +
	"\x06preset\x18\x01 \x01(\v2\x16.grpc.api.v1.HL7PresetR\x06preset\"*\n" +
	"\x18ActivateHL7PresetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19ActivateHL7PresetResponse\"(\n" +
	"\x16DeleteHL7PresetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17DeleteHL7PresetResponse\"h\n" +
	"\x1cSaveHL7PresetMappingsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\bmappings\x18\x02 \x03(\v2\x1c.grpc.api.v1.HL7MappingInputR\bmappings\"T\n" +
	"\x1dSaveHL7PresetMappingsResponse\x123\n" +
	"\bmappings\x18\x01 \x03(\v2\x17.grpc.api.v1.HL7MappingR\bmappings\"\x1d\n" +
	"\x1bGetActiveHL7MappingsRequest\"c\n" +
	"\x1cGetActiveHL7MappingsResponse\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.grpc.api.v1.HL7MappingR\x04data\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\"\xa1\x01\n" +
	"\x0fHL7Demographics\x12\x1b\n" +
	"\tlast_name\x18\x01 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"4\n" +
	"\x13HL7TestQueryRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"\xae\x02\n" +
	"\x14HL7TestQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x10\n" +
	"\x03raw\x18\x05 \x01(\tR\x03raw\x12\x1b\n" +
	"\ttree_json\x18\x06 \x01(\tR\btreeJson\x12\x19\n" +
	"\bmsa_code\x18\a \x01(\tR\amsaCode\x12\x1f\n" +
	"\vmsa_message\x18\b \x01(\tR\n" +
	"msaMessage\x12@\n" +
	"\fdemographics\x18\t \x01(\v2\x1c.grpc.api.v1.HL7DemographicsR\fdemographics\"\x10\n" +
	"\x0eHL7PingRequest\"o\n" +
	"\x0fHL7PingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x18\n" +
	"\alatency\x18\x03 \x01(\tR\alatency\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x84\x06\n" +
	"\vHL7Settings\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\ftrigger_mode\x18\x02 \x01(\tR\vtriggerMode\x12'\n" +
	"\x0fcron_expression\x18\x03 \x01(\tR\x0ecronExpression\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\tR\atimeout\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1f\n" +
	"\vhl7_enabled\x18\a \x01(\bR\n" +
	"hl7Enabled\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x19\n" +
	"\blast_run\x18\t \x01(\tR\alastRun\x12\x19\n" +
	"\bnext_run\x18\n" +
	" \x01(\tR\anextRun\x12\x12\n" +
	"\x04host\x18\v \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\f \x01(\x05R\x04port\x12/\n" +
	"\x13sending_application\x18\r \x01(\tR\x12sendingApplication\x12)\n" +
	"\x10sending_facility\x18\x0e \x01(\tR\x0fsendingFacility\x123\n" +
	"\x15receiving_application\x18\x0f \x01(\tR\x14receivingApplication\x12-\n" +
	"\x12receiving_facility\x18\x10 \x01(\tR\x11receivingFacility\x12\x18\n" +
	"\aversion\x18\x11 \x01(\tR\aversion\x12#\n" +
	"\rprocessing_id\x18\x12 \x01(\tR\fprocessingId\x12\x1f\n" +
	"\voru_enabled\x18\x13 \x01(\bR\n" +
	"oruEnabled\x12(\n" +
	"\x10oru_trigger_mode\x18\x14 \x01(\tR\x0eoruTriggerMode\x12\x19\n" +
	"\boru_host\x18\x15 \x01(\tR\aoruHost\x12\x19\n" +
	"\boru_port\x18\x16 \x01(\x05R\aoruPort\x12&\n" +
	"\x0foru_include_pdf\x18\x17 \x01(\bR\roruIncludePdf\"\x17\n" +
	"\x15GetHL7SettingsRequest\"N\n" +
	"\x16GetHL7SettingsResponse\x124\n" +
	"\bsettings\x18\x01 \x01(\v2\x18.grpc.api.v1.HL7SettingsR\bsettings\"\xc9\b\n" +
	"\x18UpdateHL7SettingsRequest\x12$\n" +
	"\vhl7_enabled\x18\x01 \x01(\bH\x00R\n" +
	"hl7Enabled\x88\x01\x01\x12&\n" +
	"\ftrigger_mode\x18\x02 \x01(\tH\x01R\vtriggerMode\x88\x01\x01\x12,\n" +
	"\x0fcron_expression\x18\x03 \x01(\tH\x02R\x0ecronExpression\x88\x01\x01\x12$\n" +
	"\vmax_retries\x18\x04 \x01(\x05H\x03R\n" +
	"maxRetries\x88\x01\x01\x12\x1d\n" +
	"\atimeout\x18\x05 \x01(\tH\x04R\atimeout\x88\x01\x01\x12\x1d\n" +
	"\aenabled\x18\x06 \x01(\bH\x05R\aenabled\x88\x01\x01\x12\x17\n" +
	"\x04host\x18\a \x01(\tH\x06R\x04host\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\b \x01(\x05H\aR\x04port\x88\x01\x01\x124\n" +
	"\x13sending_application\x18\t \x01(\tH\bR\x12sendingApplication\x88\x01\x01\x12.\n" +
	"\x10sending_facility\x18\n" +
	" \x01(\tH\tR\x0fsendingFacility\x88\x01\x01\x128\n" +
	"\x15receiving_application\x18\v \x01(\tH\n" +
	"R\x14receivingApplication\x88\x01\x01\x122\n" +
	"\x12receiving_facility\x18\f \x01(\tH\vR\x11receivingFacility\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\r \x01(\tH\fR\aversion\x88\x01\x01\x12(\n" +
	"\rprocessing_id\x18\x0e \x01(\tH\rR\fprocessingId\x88\x01\x01\x12$\n" +
	"\voru_enabled\x18\x0f \x01(\bH\x0eR\n" +
	"oruEnabled\x88\x01\x01\x12-\n" +
	"\x10oru_trigger_mode\x18\x10 \x01(\tH\x0fR\x0eoruTriggerMode\x88\x01\x01\x12\x1e\n" +
	"\boru_host\x18\x11 \x01(\tH\x10R\aoruHost\x88\x01\x01\x12\x1e\n" +
	"\boru_port\x18\x12 \x01(\x05H\x11R\aoruPort\x88\x01\x01\x12+\n" +
	"\x0foru_include_pdf\x18\x13 \x01(\bH\x12R\roruIncludePdf\x88\x01\x01B\x0e\n" +
	"\f_hl7_enabledB\x0f\n" +
	"\r_trigger_modeB\x12\n" +
	"\x10_cron_expressionB\x0e\n" +
	"\f_max_retriesB\n" +
	"\n" +
	"\b_timeoutB\n" +
	"\n" +
	"\b_enabledB\a\n" +
	"\x05_hostB\a\n" +
	"\x05_portB\x16\n" +
	"\x14_sending_applicationB\x13\n" +
	"\x11_sending_facilityB\x18\n" +
	"\x16_receiving_applicationB\x15\n" +
	"\x13_receiving_facilityB\n" +
	"\n" +
	"\b_versionB\x10\n" +
	"\x0e_processing_idB\x0e\n" +
	"\f_oru_enabledB\x13\n" +
	"\x11_oru_trigger_modeB\v\n" +
	"\t_oru_hostB\v\n" +
	"\t_oru_portB\x12\n" +
	"\x10_oru_include_pdf\"Q\n" +
	"\x19UpdateHL7SettingsResponse\x124\n" +
	"\bsettings\x18\x01 \x01(\v2\x18.grpc.api.v1.HL7SettingsR\bsettings\"\x14\n" +
	"\x12ForceHL7RunRequest\"/\n" +
	"\x13ForceHL7RunResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x15\n" +
	"\x13BulkRetryHL7Request\"F\n" +
	"\x14BulkRetryHL7Response\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xde\b\n" +
	"\x0fHL7AdminService\x12X\n" +
	"\vListPresets\x12\".grpc.api.v1.ListHL7PresetsRequest\x1a#.grpc.api.v1.ListHL7PresetsResponse\"\x00\x12[\n" +
	"\fCreatePreset\x12#.grpc.api.v1.CreateHL7PresetRequest\x1a$.grpc.api.v1.CreateHL7PresetResponse\"\x00\x12a\n" +
	"\x0eActivatePreset\x12%.grpc.api.v1.ActivateHL7PresetRequest\x1a&.grpc.api.v1.ActivateHL7PresetResponse\"\x00\x12[\n" +
	"\fDeletePreset\x12#.grpc.api.v1.DeleteHL7PresetRequest\x1a$.grpc.api.v1.DeleteHL7PresetResponse\"\x00\x12m\n" +
	"\x12SavePresetMappings\x12).grpc.api.v1.SaveHL7PresetMappingsRequest\x1a*.grpc.api.v1.SaveHL7PresetMappingsResponse\"\x00\x12j\n" +
	"\x11GetActiveMappings\x12(.grpc.api.v1.GetActiveHL7MappingsRequest\x1a).grpc.api.v1.GetActiveHL7MappingsResponse\"\x00\x12R\n" +
	"\tTestQuery\x12 .grpc.api.v1.HL7TestQueryRequest\x1a!.grpc.api.v1.HL7TestQueryResponse\"\x00\x12C\n" +
	"\x04Ping\x12\x1b.grpc.api.v1.HL7PingRequest\x1a\x1c.grpc.api.v1.HL7PingResponse\"\x00\x12X\n" +
	"\vGetSettings\x12\".grpc.api.v1.GetHL7SettingsRequest\x1a#.grpc.api.v1.GetHL7SettingsResponse\"\x00\x12a\n" +
	"\x0eUpdateSettings\x12%.grpc.api.v1.UpdateHL7SettingsRequest\x1a&.grpc.api.v1.UpdateHL7SettingsResponse\"\x00\x12O\n" +
	"\bForceRun\x12\x1f.grpc.api.v1.ForceHL7RunRequest\x1a .grpc.api.v1.ForceHL7RunResponse\"\x00\x12R\n" +
	"\tBulkRetry\x12 .grpc.api.v1.BulkRetryHL7Request\x1a!.grpc.api.v1.BulkRetryHL7Response\"\x00B\xa2\x01\n" +
	"\x0fcom.grpc.api.v1B\rHl7adminProtoP\x01Z2github.com/LIRYC-IHU/ecg-hub/internal/api/v1;apiv1\xa2\x02\x03GAX\xaa\x02\vGrpc.Api.V1\xca\x02\vGrpc\\Api\\V1\xe2\x02\x17Grpc\\Api\\V1\\GPBMetadata\xea\x02\rGrpc::Api::V1b\x06proto3"

var (
	file_v1_hl7admin_proto_rawDescOnce sync.Once
	file_v1_hl7admin_proto_rawDescData []byte
)

func file_v1_hl7admin_proto_rawDescGZIP() []byte {
	file_v1_hl7admin_proto_rawDescOnce.Do(func() {
		file_v1_hl7admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_hl7admin_proto_rawDesc), len(file_v1_hl7admin_proto_rawDesc)))
	})
	return file_v1_hl7admin_proto_rawDescData
}

var file_v1_hl7admin_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_v1_hl7admin_proto_goTypes = []any{
	(*HL7Mapping)(nil),                    // 0: grpc.api.v1.HL7Mapping
	(*HL7MappingInput)(nil),               // 1: grpc.api.v1.HL7MappingInput
	(*HL7Preset)(nil),                     // 2: grpc.api.v1.HL7Preset
	(*ListHL7PresetsRequest)(nil),         // 3: grpc.api.v1.ListHL7PresetsRequest
	(*ListHL7PresetsResponse)(nil),        // 4: grpc.api.v1.ListHL7PresetsResponse
	(*CreateHL7PresetRequest)(nil),        // 5: grpc.api.v1.CreateHL7PresetRequest
	(*CreateHL7PresetResponse)(nil),       // 6: grpc.api.v1.CreateHL7PresetResponse
	(*ActivateHL7PresetRequest)(nil),      // 7: grpc.api.v1.ActivateHL7PresetRequest
	(*ActivateHL7PresetResponse)(nil),     // 8: grpc.api.v1.ActivateHL7PresetResponse
	(*DeleteHL7PresetRequest)(nil),        // 9: grpc.api.v1.DeleteHL7PresetRequest
	(*DeleteHL7PresetResponse)(nil),       // 10: grpc.api.v1.DeleteHL7PresetResponse
	(*SaveHL7PresetMappingsRequest)(nil),  // 11: grpc.api.v1.SaveHL7PresetMappingsRequest
	(*SaveHL7PresetMappingsResponse)(nil), // 12: grpc.api.v1.SaveHL7PresetMappingsResponse
	(*GetActiveHL7MappingsRequest)(nil),   // 13: grpc.api.v1.GetActiveHL7MappingsRequest
	(*GetActiveHL7MappingsResponse)(nil),  // 14: grpc.api.v1.GetActiveHL7MappingsResponse
	(*HL7Demographics)(nil),               // 15: grpc.api.v1.HL7Demographics
	(*HL7TestQueryRequest)(nil),           // 16: grpc.api.v1.HL7TestQueryRequest
	(*HL7TestQueryResponse)(nil),          // 17: grpc.api.v1.HL7TestQueryResponse
	(*HL7PingRequest)(nil),                // 18: grpc.api.v1.HL7PingRequest
	(*HL7PingResponse)(nil),               // 19: grpc.api.v1.HL7PingResponse
	(*HL7Settings)(nil),                   // 20: grpc.api.v1.HL7Settings
	(*GetHL7SettingsRequest)(nil),         // 21: grpc.api.v1.GetHL7SettingsRequest
	(*GetHL7SettingsResponse)(nil),        // 22: grpc.api.v1.GetHL7SettingsResponse
	(*UpdateHL7SettingsRequest)(nil),      // 23: grpc.api.v1.UpdateHL7SettingsRequest
	(*UpdateHL7SettingsResponse)(nil),     // 24: grpc.api.v1.UpdateHL7SettingsResponse
	(*ForceHL7RunRequest)(nil),            // 25: grpc.api.v1.ForceHL7RunRequest
	(*ForceHL7RunResponse)(nil),           // 26: grpc.api.v1.ForceHL7RunResponse
	(*BulkRetryHL7Request)(nil),           // 27: grpc.api.v1.BulkRetryHL7Request
	(*BulkRetryHL7Response)(nil),          // 28: grpc.api.v1.BulkRetryHL7Response
}
var file_v1_hl7admin_proto_depIdxs = []int32{
	0,  // 0: grpc.api.v1.HL7Preset.mappings:type_name -> grpc.api.v1.HL7Mapping
	2,  // 1: grpc.api.v1.ListHL7PresetsResponse.presets:type_name -> grpc.api.v1.HL7Preset
	1,  // 2: grpc.api.v1.CreateHL7PresetRequest.mappings:type_name -> grpc.api.v1.HL7MappingInput
	2,  // 3: grpc.api.v1.CreateHL7PresetResponse.preset:type_name -> grpc.api.v1.HL7Preset
	1,  // 4: grpc.api.v1.SaveHL7PresetMappingsRequest.mappings:type_name -> grpc.api.v1.HL7MappingInput
	0,  // 5: grpc.api.v1.SaveHL7PresetMappingsResponse.mappings:type_name -> grpc.api.v1.HL7Mapping
	0,  // 6: grpc.api.v1.GetActiveHL7MappingsResponse.data:type_name -> grpc.api.v1.HL7Mapping
	15, // 7: grpc.api.v1.HL7TestQueryResponse.demographics:type_name -> grpc.api.v1.HL7Demographics
	20, // 8: grpc.api.v1.GetHL7SettingsResponse.settings:type_name -> grpc.api.v1.HL7Settings
	20, // 9: grpc.api.v1.UpdateHL7SettingsResponse.settings:type_name -> grpc.api.v1.HL7Settings
	3,  // 10: grpc.api.v1.HL7AdminService.ListPresets:input_type -> grpc.api.v1.ListHL7PresetsRequest
	5,  // 11: grpc.api.v1.HL7AdminService.CreatePreset:input_type -> grpc.api.v1.CreateHL7PresetRequest
	7,  // 12: grpc.api.v1.HL7AdminService.ActivatePreset:input_type -> grpc.api.v1.ActivateHL7PresetRequest
	9,  // 13: grpc.api.v1.HL7AdminService.DeletePreset:input_type -> grpc.api.v1.DeleteHL7PresetRequest
	11, // 14: grpc.api.v1.HL7AdminService.SavePresetMappings:input_type -> grpc.api.v1.SaveHL7PresetMappingsRequest
	13, // 15: grpc.api.v1.HL7AdminService.GetActiveMappings:input_type -> grpc.api.v1.GetActiveHL7MappingsRequest
	16, // 16: grpc.api.v1.HL7AdminService.TestQuery:input_type -> grpc.api.v1.HL7TestQueryRequest
	18, // 17: grpc.api.v1.HL7AdminService.Ping:input_type -> grpc.api.v1.HL7PingRequest
	21, // 18: grpc.api.v1.HL7AdminService.GetSettings:input_type -> grpc.api.v1.GetHL7SettingsRequest
	23, // 19: grpc.api.v1.HL7AdminService.UpdateSettings:input_type -> grpc.api.v1.UpdateHL7SettingsRequest
	25, // 20: grpc.api.v1.HL7AdminService.ForceRun:input_type -> grpc.api.v1.ForceHL7RunRequest
	27, // 21: grpc.api.v1.HL7AdminService.BulkRetry:input_type -> grpc.api.v1.BulkRetryHL7Request
	4,  // 22: grpc.api.v1.HL7AdminService.ListPresets:output_type -> grpc.api.v1.ListHL7PresetsResponse
	6,  // 23: grpc.api.v1.HL7AdminService.CreatePreset:output_type -> grpc.api.v1.CreateHL7PresetResponse
	8,  // 24: grpc.api.v1.HL7AdminService.ActivatePreset:output_type -> grpc.api.v1.ActivateHL7PresetResponse
	10, // 25: grpc.api.v1.HL7AdminService.DeletePreset:output_type -> grpc.api.v1.DeleteHL7PresetResponse
	12, // 26: grpc.api.v1.HL7AdminService.SavePresetMappings:output_type -> grpc.api.v1.SaveHL7PresetMappingsResponse
	14, // 27: grpc.api.v1.HL7AdminService.GetActiveMappings:output_type -> grpc.api.v1.GetActiveHL7MappingsResponse
	17, // 28: grpc.api.v1.HL7AdminService.TestQuery:output_type -> grpc.api.v1.HL7TestQueryResponse
	19, // 29: grpc.api.v1.HL7AdminService.Ping:output_type -> grpc.api.v1.HL7PingResponse
	22, // 30: grpc.api.v1.HL7AdminService.GetSettings:output_type -> grpc.api.v1.GetHL7SettingsResponse
	24, // 31: grpc.api.v1.HL7AdminService.UpdateSettings:output_type -> grpc.api.v1.UpdateHL7SettingsResponse
	26, // 32: grpc.api.v1.HL7AdminService.ForceRun:output_type -> grpc.api.v1.ForceHL7RunResponse
	28, // 33: grpc.api.v1.HL7AdminService.BulkRetry:output_type -> grpc.api.v1.BulkRetryHL7Response
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_hl7admin_proto_init() }
func file_v1_hl7admin_proto_init() {
	if File_v1_hl7admin_proto != nil {
		return
	}
	file_v1_hl7admin_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_hl7admin_proto_rawDesc), len(file_v1_hl7admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_hl7admin_proto_goTypes,
		DependencyIndexes: file_v1_hl7admin_proto_depIdxs,
		MessageInfos:      file_v1_hl7admin_proto_msgTypes,
	}.Build()
	File_v1_hl7admin_proto = out.File
	file_v1_hl7admin_proto_goTypes = nil
	file_v1_hl7admin_proto_depIdxs = nil
}
