// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/setup.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// System bootstrap status — public, used by the setup page before any account
// exists.
type GetSetupStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetupStatusRequest) Reset() {
	*x = GetSetupStatusRequest{}
	mi := &file_v1_setup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetupStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetupStatusRequest) ProtoMessage() {}

func (x *GetSetupStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_setup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetupStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSetupStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_setup_proto_rawDescGZIP(), []int{0}
}

type GetSetupStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Initialized   bool                   `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"` // true once at least one local/identity account exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSetupStatusResponse) Reset() {
	*x = GetSetupStatusResponse{}
	mi := &file_v1_setup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSetupStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSetupStatusResponse) ProtoMessage() {}

func (x *GetSetupStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_setup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSetupStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSetupStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_setup_proto_rawDescGZIP(), []int{1}
}

func (x *GetSetupStatusResponse) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

// Initialize creates the first local admin account. Public — only usable while
// the system is uninitialised (no local/identity account exists yet).
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_v1_setup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_setup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_v1_setup_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InitializeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_v1_setup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_setup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_v1_setup_proto_rawDescGZIP(), []int{3}
}

func (x *InitializeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InitializeResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InitializeResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_v1_setup_proto protoreflect.FileDescriptor

const file_v1_setup_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/setup.proto\x12\vgrpc.api.v1\"\x17\n" +
	"\x15GetSetupStatusRequest\":\n" +
	"\x16GetSetupStatusResponse\x12 \n" +
	"\vinitialized\x18\x01 \x01(\bR\vinitialized\"K\n" +
	"\x11InitializeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	"\x12InitializeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2\xb7\x01\n" +
	"\fSetupService\x12V\n" +
	"\tGetStatus\x12\".grpc.api.v1.GetSetupStatusRequest\x1a#.grpc.api.v1.GetSetupStatusResponse\"\x00\x12O\n" +
	"\n" +
	"Initialize\x12\x1e.grpc.api.v1.InitializeRequest\x1a\x1f.grpc.api.v1.InitializeResponse\"\x00B\x9f\x01\n" +
	"\x0fcom.grpc.api.v1B\n" +
	"SetupProtoP\x01Z2github.com/LIRYC-IHU/ecg-hub/internal/api/v1;apiv1\xa2\x02\x03GAX\xaa\x02\vGrpc.Api.V1\xca\x02\vGrpc\\Api\\V1\xe2\x02\x17Grpc\\Api\\V1\\GPBMetadata\xea\x02\rGrpc::Api::V1b\x06proto3"

var (
	file_v1_setup_proto_rawDescOnce sync.Once
	file_v1_setup_proto_rawDescData []byte
)

func file_v1_setup_proto_rawDescGZIP() []byte {
	file_v1_setup_proto_rawDescOnce.Do(func() {
		file_v1_setup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_setup_proto_rawDesc), len(file_v1_setup_proto_rawDesc)))
	})
	return file_v1_setup_proto_rawDescData
}

var file_v1_setup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_setup_proto_goTypes = []any{
	(*GetSetupStatusRequest)(nil),  // 0: grpc.api.v1.GetSetupStatusRequest
	(*GetSetupStatusResponse)(nil), // 1: grpc.api.v1.GetSetupStatusResponse
	(*InitializeRequest)(nil),      // 2: grpc.api.v1.InitializeRequest
	(*InitializeResponse)(nil),     // 3: grpc.api.v1.InitializeResponse
}
var file_v1_setup_proto_depIdxs = []int32{
	0, // 0: grpc.api.v1.SetupService.GetStatus:input_type -> grpc.api.v1.GetSetupStatusRequest
	2, // 1: grpc.api.v1.SetupService.Initialize:input_type -> grpc.api.v1.InitializeRequest
	1, // 2: grpc.api.v1.SetupService.GetStatus:output_type -> grpc.api.v1.GetSetupStatusResponse
	3, // 3: grpc.api.v1.SetupService.Initialize:output_type -> grpc.api.v1.InitializeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_setup_proto_init() }
func file_v1_setup_proto_init() {
	if File_v1_setup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_setup_proto_rawDesc), len(file_v1_setup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_setup_proto_goTypes,
		DependencyIndexes: file_v1_setup_proto_depIdxs,
		MessageInfos:      file_v1_setup_proto_msgTypes,
	}.Build()
	File_v1_setup_proto = out.File
	file_v1_setup_proto_goTypes = nil
	file_v1_setup_proto_depIdxs = nil
}
