// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/webhook.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Webhook is the API shape of a configured endpoint (no secret values).
type Webhook struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url                string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Enabled            bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	InsecureSkipVerify bool                   `protobuf:"varint,5,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	Events             []string               `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`   // empty = all
	Vendors            []string               `protobuf:"bytes,7,rep,name=vendors,proto3" json:"vendors,omitempty"` // empty = all
	HasSecret          bool                   `protobuf:"varint,8,opt,name=has_secret,json=hasSecret,proto3" json:"has_secret,omitempty"`
	HasAuthHeader      bool                   `protobuf:"varint,9,opt,name=has_auth_header,json=hasAuthHeader,proto3" json:"has_auth_header,omitempty"`
	LastStatusCode     int32                  `protobuf:"varint,10,opt,name=last_status_code,json=lastStatusCode,proto3" json:"last_status_code,omitempty"`
	LastError          string                 `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastDeliveredAt    string                 `protobuf:"bytes,12,opt,name=last_delivered_at,json=lastDeliveredAt,proto3" json:"last_delivered_at,omitempty"` // ISO 8601 UTC; empty when never
	CreatedAt          string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_v1_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *Webhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webhook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Webhook) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Webhook) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Webhook) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

func (x *Webhook) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Webhook) GetVendors() []string {
	if x != nil {
		return x.Vendors
	}
	return nil
}

func (x *Webhook) GetHasSecret() bool {
	if x != nil {
		return x.HasSecret
	}
	return false
}

func (x *Webhook) GetHasAuthHeader() bool {
	if x != nil {
		return x.HasAuthHeader
	}
	return false
}

func (x *Webhook) GetLastStatusCode() int32 {
	if x != nil {
		return x.LastStatusCode
	}
	return 0
}

func (x *Webhook) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Webhook) GetLastDeliveredAt() string {
	if x != nil {
		return x.LastDeliveredAt
	}
	return ""
}

func (x *Webhook) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Webhook) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// WebhookInput is the create/update body. The optional fields are tri-state on
// update: unset = leave unchanged, and for secret/auth_header "" = clear,
// value = set (encrypted).
type WebhookInput struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Enabled            *bool                  `protobuf:"varint,3,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	InsecureSkipVerify *bool                  `protobuf:"varint,4,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3,oneof" json:"insecure_skip_verify,omitempty"`
	Secret             *string                `protobuf:"bytes,5,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	AuthHeader         *string                `protobuf:"bytes,6,opt,name=auth_header,json=authHeader,proto3,oneof" json:"auth_header,omitempty"`
	Events             []string               `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	Vendors            []string               `protobuf:"bytes,8,rep,name=vendors,proto3" json:"vendors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebhookInput) Reset() {
	*x = WebhookInput{}
	mi := &file_v1_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookInput) ProtoMessage() {}

func (x *WebhookInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookInput.ProtoReflect.Descriptor instead.
func (*WebhookInput) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebhookInput) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebhookInput) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *WebhookInput) GetInsecureSkipVerify() bool {
	if x != nil && x.InsecureSkipVerify != nil {
		return *x.InsecureSkipVerify
	}
	return false
}

func (x *WebhookInput) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

func (x *WebhookInput) GetAuthHeader() string {
	if x != nil && x.AuthHeader != nil {
		return *x.AuthHeader
	}
	return ""
}

func (x *WebhookInput) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *WebhookInput) GetVendors() []string {
	if x != nil {
		return x.Vendors
	}
	return nil
}

type ListWebhooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksRequest) Reset() {
	*x = ListWebhooksRequest{}
	mi := &file_v1_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksRequest) ProtoMessage() {}

func (x *ListWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksRequest.ProtoReflect.Descriptor instead.
func (*ListWebhooksRequest) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{2}
}

type ListWebhooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhooks      []*Webhook             `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksResponse) Reset() {
	*x = ListWebhooksResponse{}
	mi := &file_v1_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksResponse) ProtoMessage() {}

func (x *ListWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksResponse.ProtoReflect.Descriptor instead.
func (*ListWebhooksResponse) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *ListWebhooksResponse) GetWebhooks() []*Webhook {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

type CreateWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *WebhookInput          `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookRequest) Reset() {
	*x = CreateWebhookRequest{}
	mi := &file_v1_webhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookRequest) ProtoMessage() {}

func (x *CreateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookRequest.ProtoReflect.Descriptor instead.
func (*CreateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWebhookRequest) GetInput() *WebhookInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type CreateWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookResponse) Reset() {
	*x = CreateWebhookResponse{}
	mi := &file_v1_webhook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookResponse) ProtoMessage() {}

func (x *CreateWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookResponse.ProtoReflect.Descriptor instead.
func (*CreateWebhookResponse) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type UpdateWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         *WebhookInput          `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebhookRequest) Reset() {
	*x = UpdateWebhookRequest{}
	mi := &file_v1_webhook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookRequest) ProtoMessage() {}

func (x *UpdateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebhookRequest.ProtoReflect.Descriptor instead.
func (*UpdateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWebhookRequest) GetInput() *WebhookInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UpdateWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebhookResponse) Reset() {
	*x = UpdateWebhookResponse{}
	mi := &file_v1_webhook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookResponse) ProtoMessage() {}

func (x *UpdateWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebhookResponse.ProtoReflect.Descriptor instead.
func (*UpdateWebhookResponse) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type DeleteWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookRequest) Reset() {
	*x = DeleteWebhookRequest{}
	mi := &file_v1_webhook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookRequest) ProtoMessage() {}

func (x *DeleteWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebhookRequest) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookResponse) Reset() {
	*x = DeleteWebhookResponse{}
	mi := &file_v1_webhook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookResponse) ProtoMessage() {}

func (x *DeleteWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebhookResponse) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{9}
}

type TestWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookRequest) Reset() {
	*x = TestWebhookRequest{}
	mi := &file_v1_webhook_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookRequest) ProtoMessage() {}

func (x *TestWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookRequest.ProtoReflect.Descriptor instead.
func (*TestWebhookRequest) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{10}
}

func (x *TestWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookResponse) Reset() {
	*x = TestWebhookResponse{}
	mi := &file_v1_webhook_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookResponse) ProtoMessage() {}

func (x *TestWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookResponse.ProtoReflect.Descriptor instead.
func (*TestWebhookResponse) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{11}
}

func (x *TestWebhookResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TestWebhookResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TestWebhookResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Options drive the webhook editor: the selectable event types + the known
// vendors (with their accepted file extensions).
type VendorOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Extensions    []string               `protobuf:"bytes,2,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorOption) Reset() {
	*x = VendorOption{}
	mi := &file_v1_webhook_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorOption) ProtoMessage() {}

func (x *VendorOption) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorOption.ProtoReflect.Descriptor instead.
func (*VendorOption) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{12}
}

func (x *VendorOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VendorOption) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type GetWebhookOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookOptionsRequest) Reset() {
	*x = GetWebhookOptionsRequest{}
	mi := &file_v1_webhook_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookOptionsRequest) ProtoMessage() {}

func (x *GetWebhookOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetWebhookOptionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{13}
}

type GetWebhookOptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []string               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Vendors       []*VendorOption        `protobuf:"bytes,2,rep,name=vendors,proto3" json:"vendors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebhookOptionsResponse) Reset() {
	*x = GetWebhookOptionsResponse{}
	mi := &file_v1_webhook_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebhookOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebhookOptionsResponse) ProtoMessage() {}

func (x *GetWebhookOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_webhook_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebhookOptionsResponse.ProtoReflect.Descriptor instead.
func (*GetWebhookOptionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_webhook_proto_rawDescGZIP(), []int{14}
}

func (x *GetWebhookOptionsResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetWebhookOptionsResponse) GetVendors() []*VendorOption {
	if x != nil {
		return x.Vendors
	}
	return nil
}

var File_v1_webhook_proto protoreflect.FileDescriptor

const file_v1_webhook_proto_rawDesc = "" +
	"\n" +
	"\x10v1/webhook.proto\x12\vgrpc.api.v1\"\xb7\x03\n" +
	"\aWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x120\n" +
	"\x14insecure_skip_verify\x18\x05 \x01(\bR\x12insecureSkipVerify\x12\x16\n" +
	"\x06events\x18\x06 \x03(\tR\x06events\x12\x18\n" +
	"\avendors\x18\a \x03(\tR\avendors\x12\x1d\n" +
	"\n" +
	"has_secret\x18\b \x01(\bR\thasSecret\x12&\n" +
	"\x0fhas_auth_header\x18\t \x01(\bR\rhasAuthHeader\x12(\n" +
	"\x10last_status_code\x18\n" +
	" \x01(\x05R\x0elastStatusCode\x12\x1d\n" +
	"\n" +
	"last_error\x18\v \x01(\tR\tlastError\x12*\n" +
	"\x11last_delivered_at\x18\f \x01(\tR\x0flastDeliveredAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\xbf\x02\n" +
	"\fWebhookInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\aenabled\x18\x03 \x01(\bH\x00R\aenabled\x88\x01\x01\x125\n" +
	"\x14insecure_skip_verify\x18\x04 \x01(\bH\x01R\x12insecureSkipVerify\x88\x01\x01\x12\x1b\n" +
	"\x06secret\x18\x05 \x01(\tH\x02R\x06secret\x88\x01\x01\x12$\n" +
	"\vauth_header\x18\x06 \x01(\tH\x03R\n" +
	"authHeader\x88\x01\x01\x12\x16\n" +
	"\x06events\x18\a \x03(\tR\x06events\x12\x18\n" +
	"\avendors\x18\b \x03(\tR\avendorsB\n" +
	"\n" +
	"\b_enabledB\x17\n" +
	"\x15_insecure_skip_verifyB\t\n" +
	"\a_secretB\x0e\n" +
	"\f_auth_header\"\x15\n" +
	"\x13ListWebhooksRequest\"H\n" +
	"\x14ListWebhooksResponse\x120\n" +
	"\bwebhooks\x18\x01 \x03(\v2\x14.grpc.api.v1.WebhookR\bwebhooks\"G\n" +
	"\x14CreateWebhookRequest\x12/\n" +
	"\x05input\x18\x01 \x01(\v2\x19.grpc.api.v1.WebhookInputR\x05input\"G\n" +
	"\x15CreateWebhookResponse\x12.\n" +
	"\awebhook\x18\x01 \x01(\v2\x14.grpc.api.v1.WebhookR\awebhook\"W\n" +
	"\x14UpdateWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x05input\x18\x02 \x01(\v2\x19.grpc.api.v1.WebhookInputR\x05input\"G\n" +
	"\x15UpdateWebhookResponse\x12.\n" +
	"\awebhook\x18\x01 \x01(\v2\x14.grpc.api.v1.WebhookR\awebhook\"&\n" +
	"\x14DeleteWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteWebhookResponse\"$\n" +
	"\x12TestWebhookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x13TestWebhookResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"B\n" +
	"\fVendorOption\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"extensions\x18\x02 \x03(\tR\n" +
	"extensions\"\x1a\n" +
	"\x18GetWebhookOptionsRequest\"h\n" +
	"\x19GetWebhookOptionsResponse\x12\x16\n" +
	"\x06events\x18\x01 \x03(\tR\x06events\x123\n" +
	"\avendors\x18\x02 \x03(\v2\x19.grpc.api.v1.VendorOptionR\avendors2\xa8\x04\n" +
	"\x0eWebhookService\x12]\n" +
	"\n" +
	"GetOptions\x12%.grpc.api.v1.GetWebhookOptionsRequest\x1a&.grpc.api.v1.GetWebhookOptionsResponse\"\x00\x12U\n" +
	"\fListWebhooks\x12 .grpc.api.v1.ListWebhooksRequest\x1a!.grpc.api.v1.ListWebhooksResponse\"\x00\x12X\n" +
	"\rCreateWebhook\x12!.grpc.api.v1.CreateWebhookRequest\x1a\".grpc.api.v1.CreateWebhookResponse\"\x00\x12X\n" +
	"\rUpdateWebhook\x12!.grpc.api.v1.UpdateWebhookRequest\x1a\".grpc.api.v1.UpdateWebhookResponse\"\x00\x12X\n" +
	"\rDeleteWebhook\x12!.grpc.api.v1.DeleteWebhookRequest\x1a\".grpc.api.v1.DeleteWebhookResponse\"\x00\x12R\n" +
	"\vTestWebhook\x12\x1f.grpc.api.v1.TestWebhookRequest\x1a .grpc.api.v1.TestWebhookResponse\"\x00B\xa1\x01\n" +
	"\x0fcom.grpc.api.v1B\fWebhookProtoP\x01Z2github.com/LIRYC-IHU/ecg-hub/internal/api/v1;apiv1\xa2\x02\x03GAX\xaa\x02\vGrpc.Api.V1\xca\x02\vGrpc\\Api\\V1\xe2\x02\x17Grpc\\Api\\V1\\GPBMetadata\xea\x02\rGrpc::Api::V1b\x06proto3"

var (
	file_v1_webhook_proto_rawDescOnce sync.Once
	file_v1_webhook_proto_rawDescData []byte
)

func file_v1_webhook_proto_rawDescGZIP() []byte {
	file_v1_webhook_proto_rawDescOnce.Do(func() {
		file_v1_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_webhook_proto_rawDesc), len(file_v1_webhook_proto_rawDesc)))
	})
	return file_v1_webhook_proto_rawDescData
}

var file_v1_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_webhook_proto_goTypes = []any{
	(*Webhook)(nil),                   // 0: grpc.api.v1.Webhook
	(*WebhookInput)(nil),              // 1: grpc.api.v1.WebhookInput
	(*ListWebhooksRequest)(nil),       // 2: grpc.api.v1.ListWebhooksRequest
	(*ListWebhooksResponse)(nil),      // 3: grpc.api.v1.ListWebhooksResponse
	(*CreateWebhookRequest)(nil),      // 4: grpc.api.v1.CreateWebhookRequest
	(*CreateWebhookResponse)(nil),     // 5: grpc.api.v1.CreateWebhookResponse
	(*UpdateWebhookRequest)(nil),      // 6: grpc.api.v1.UpdateWebhookRequest
	(*UpdateWebhookResponse)(nil),     // 7: grpc.api.v1.UpdateWebhookResponse
	(*DeleteWebhookRequest)(nil),      // 8: grpc.api.v1.DeleteWebhookRequest
	(*DeleteWebhookResponse)(nil),     // 9: grpc.api.v1.DeleteWebhookResponse
	(*TestWebhookRequest)(nil),        // 10: grpc.api.v1.TestWebhookRequest
	(*TestWebhookResponse)(nil),       // 11: grpc.api.v1.TestWebhookResponse
	(*VendorOption)(nil),              // 12: grpc.api.v1.VendorOption
	(*GetWebhookOptionsRequest)(nil),  // 13: grpc.api.v1.GetWebhookOptionsRequest
	(*GetWebhookOptionsResponse)(nil), // 14: grpc.api.v1.GetWebhookOptionsResponse
}
var file_v1_webhook_proto_depIdxs = []int32{
	0,  // 0: grpc.api.v1.ListWebhooksResponse.webhooks:type_name -> grpc.api.v1.Webhook
	1,  // 1: grpc.api.v1.CreateWebhookRequest.input:type_name -> grpc.api.v1.WebhookInput
	0,  // 2: grpc.api.v1.CreateWebhookResponse.webhook:type_name -> grpc.api.v1.Webhook
	1,  // 3: grpc.api.v1.UpdateWebhookRequest.input:type_name -> grpc.api.v1.WebhookInput
	0,  // 4: grpc.api.v1.UpdateWebhookResponse.webhook:type_name -> grpc.api.v1.Webhook
	12, // 5: grpc.api.v1.GetWebhookOptionsResponse.vendors:type_name -> grpc.api.v1.VendorOption
	13, // 6: grpc.api.v1.WebhookService.GetOptions:input_type -> grpc.api.v1.GetWebhookOptionsRequest
	2,  // 7: grpc.api.v1.WebhookService.ListWebhooks:input_type -> grpc.api.v1.ListWebhooksRequest
	4,  // 8: grpc.api.v1.WebhookService.CreateWebhook:input_type -> grpc.api.v1.CreateWebhookRequest
	6,  // 9: grpc.api.v1.WebhookService.UpdateWebhook:input_type -> grpc.api.v1.UpdateWebhookRequest
	8,  // 10: grpc.api.v1.WebhookService.DeleteWebhook:input_type -> grpc.api.v1.DeleteWebhookRequest
	10, // 11: grpc.api.v1.WebhookService.TestWebhook:input_type -> grpc.api.v1.TestWebhookRequest
	14, // 12: grpc.api.v1.WebhookService.GetOptions:output_type -> grpc.api.v1.GetWebhookOptionsResponse
	3,  // 13: grpc.api.v1.WebhookService.ListWebhooks:output_type -> grpc.api.v1.ListWebhooksResponse
	5,  // 14: grpc.api.v1.WebhookService.CreateWebhook:output_type -> grpc.api.v1.CreateWebhookResponse
	7,  // 15: grpc.api.v1.WebhookService.UpdateWebhook:output_type -> grpc.api.v1.UpdateWebhookResponse
	9,  // 16: grpc.api.v1.WebhookService.DeleteWebhook:output_type -> grpc.api.v1.DeleteWebhookResponse
	11, // 17: grpc.api.v1.WebhookService.TestWebhook:output_type -> grpc.api.v1.TestWebhookResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_webhook_proto_init() }
func file_v1_webhook_proto_init() {
	if File_v1_webhook_proto != nil {
		return
	}
	file_v1_webhook_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_webhook_proto_rawDesc), len(file_v1_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_webhook_proto_goTypes,
		DependencyIndexes: file_v1_webhook_proto_depIdxs,
		MessageInfos:      file_v1_webhook_proto_msgTypes,
	}.Build()
	File_v1_webhook_proto = out.File
	file_v1_webhook_proto_goTypes = nil
	file_v1_webhook_proto_depIdxs = nil
}
